### ISSUE TITLE
CI Not Working On Pull Requests to Master

### ISSUE THREAD

**Issue by adamkhazi** [tuist/tuist#1002]
**Describe the bug**
Having created a pull request recently I noticed that CI has no steps for building `tuist`, unit tests and integration tests.

**To Reproduce**

1. Make a small change in a branch of `tuist`
2. Submit a pull request for this branch 

Check the steps that CI runs in the pull request. Notice that it is missing builds and tests.

**Expected behavior**
To build and run tuist unit and integration tests.

**Screenshots**
![Image](https://user-images.githubusercontent.com/9820670/74424776-770b5800-4e4a-11ea-89a4-3184f85a38ac.png)

**Additional context**
I noticed that this commit (https://github.com/tuist/tuist/commit/313771e4271631cd750eec46d529470b01ed049e) was recently made to `.github/workflows/checks.yml` that disabled running CI on both push and the pull request redundantly. 

Maybe if the branch that a pull request is made on is "master" the CI can conditionally run?

The pull request where I noticed the missing steps https://github.com/tuist/tuist/pull/980.

**Comment by vytis** [comment]
I think the reason is that the PR is made from a fork - so no commits have landed to `tuist/tuist` repo and CI is not triggered. Adding a PR trigger would solve the issue but would run twice when PR is opened from a "local" branch. Maybe there is something mentioned about this in GitHub's documentation that would solve the problem, it seems to be pretty basic usecase...

**Comment by pepibumur** [comment]
I found [this](https://help.github.com/en/actions/reference/events-that-trigger-workflows#pull-request-events-for-forked-repositories-2) on the documentation. Should we change the event to be `pull_request` instead of `push`? Also notice that unless GitHub Actions is enabled in the forked repository, the workflow won't run.

**Comment by vytis** [comment]
However it would then not get triggered when commit is merged to master and no binaries would be produced. Ideally we would want to trigger on `pull_request` when it's a fork and `push` for "local" PRs
