### ISSUE TITLE
'tuist edit' should include every child Project.swift on the file system

### ISSUE THREAD

**Issue by asalom** [tuist/tuist#1057]
## Need/problem

Consider the following folder structure:
```swift
root/
  - Project.swift
  - Modules/
    - Core/
      - Project.swift
    - Login/
      - Project.swift
```

When I run` tuist edit`  at _root_, the temporary Xcode project tuist generates contains only the _Project.swift_ at root but doesn’t include all the children _Project.swift_ files from my modular application.

## Motivation

Modular applications consists of many modules which have external dependencies and inter module dependencies. This kind of projects are very hard to maintain by hand and tuist comes very handy because it handles the dependency graph for us.
At the moment, however, it's tedious to maintain every `Project.swift` file in the workspace because we have to edit them one by one with `tuist edit`.

## Detailed design

TBD

# Drawbacks

- Large projects might take some time to run `tuist edit`?

## Alternatives

TBD

# Adoption strategy

TBD

# How we teach this

TBD

# Unresolved questions

TBD

**Comment by pepibumur** [comment]
@asalom this is a good idea. Would you like to take a stab at it? Here are some pointers:
- [This is the file](https://github.com/tuist/tuist/blob/master/Sources/TuistKit/ProjectEditor/ProjectEditorMapper.swift) that contains the logic that returns the `Project` that is generated for editing the manifests.
- You'll need to extend [this](https://github.com/tuist/tuist/blob/master/Sources/TuistKit/ProjectEditor/ProjectEditorMapper.swift#L35) to generate a target per `Project.swift` instead of only the manifest in the current directory. 
- Also, you might want to [create a scheme](https://github.com/tuist/tuist/blob/master/Sources/TuistKit/ProjectEditor/ProjectEditorMapper.swift#L64) per project manifest, so that users can compile them independently. You can also have a scheme that compiles all the manifest targets.

**Comment by asalom** [comment]
Yeah I will give it a try
