### ISSUE TITLE
Reduce tuist edit delay

### ISSUE THREAD

**Issue by JulianAlonso** [tuist/tuist#1251]
## Need/problem

Since version 1.7.0 we introduced all Manifest inside the project that `tuist edit` generates.
This option can take a lot of time if there is no `Tuist` or `.git` folder in our repository, and will end up searching for all the Project & Workspace Manifest on our system. Also could take some time if we have a big project.

## Motivation

- Reduce `tuist edit` delay as many as we can. 

## Detailed design

- Maybe, if we don't find a `Tuist` of `.git` folder, we could take as Root Directory the given folder (where `tuist edit` has been executed) in `RootDirectoryLocator`
- As @pepibumur [suggests](https://tuistapp.slack.com/archives/CCXC295QS/p1587485101385900?thread_ts=1587480967.369800&cid=CCXC295QS) we may add an option to prevent `tuist edit` from traverse system folders. e.g: `tuist edit --no-traverse` or `tuist edit --only-current-directory`
- And last, maybe we can add some way to allow the user exclude paths, and/or exclude some paths by default (eg: `fastlane`, `Carthage`, `.build`, `Pods`).

# Drawbacks

Why should we *not* do this? Please consider:

None, AFIK

## Alternatives

I guess that only with the first option, we can remove the issue of locate all Manifest in the system, if there's no `.git` or `Tuist` directories.

# Adoption strategy

They will keep using tuist like now. But they will have the option of edit only one Manifest (and the ProjectDefinitionHelpers)

# How we teach this

Adding new documentation inside `Commands` `tuist edit` to ilustrate the user he has the option of run `tuist edit --no-traverse` for example.

**Comment by natanrolnik** [comment]
@JulianAlonso I had an idea yesterday and it might fix the delay problem, as well as Tuist picking any Project.swift file in the project, even though it’s not related to Tuist (which I showed to @pepibumur). 

So it goes like this: if Workspace.swift already contains the paths of the projects, couldn’t we use this list instead of the need to traverse the directories?

**Comment by ollieatkinson** [comment]
I originally noticed this after downloading a blob and trying to edit the project with `tuist edit`, the blob is not backed by git which meant tuist traversed back to the root folder `/` and scanned for Project.swift files.

I very much like what @natanrolnik is proposing! it fits very much in line with what I would expect, since this is the way that `tuist generate` also works and it would mean we do not need to rely on any particular usage of the system it's being run on.

To work around this issue for the time being, you should ensure that your project is under git control.

**Comment by JulianAlonso** [comment]
Maybe I'm a little bit out of context, but I think:
- To know the depedency graph, `tuist edit` will have to build the given `Manfifest`, I think this option could performance slower than fix `RootDirectoryLocator` to prevent return `/` as root directory and return given directory if not `.git` or `Tuist` found. Also I guess this could prevent other related bugs.
- Based on the given `Manifest` will cause `tuist edit` won't add `Manifest`s that user may be should want to edit but they aren't added as dependencies yet.

**Comment by pepibumur** [comment]
I kind of like the idea of first loading the graph and loading only the projects that belong to the graph. The problem with that is that if there are errors in the manifests, the loading of the graph will fail and therefore we won't be able to edit the project.

What if we only traverse down?

**Comment by JulianAlonso** [comment]
We would lost the ability of edit the whole project while we're for example, creating a new SPM, even if we have defined `.git` or `Tuist` folder 🤔
IMHO, editing the whole project even if we're some folders down it's a cool feature.

**Comment by pepibumur** [comment]
I haven't seen complains lately on this regard so I'll go ahead and close the issue. If this continues to be an issue, users will surface it again.
