### ISSUE TITLE
When using a .a library, Tuist doesn't copy headers and modulemap files correctly

### ISSUE THREAD

**Issue by natanrolnik** [tuist/tuist#1254]
## Describe the bug

When you have a library target and an app target, both with their own manifests and projects, Xcode will correctly link between them. However, the library product will not contain the needed headers and modulemap file. This needs to be fixed manually, everytime the project is generated, by adding the following build phase:

<img width="783" alt="Copy Files Build Phase" src="https://user-images.githubusercontent.com/1164565/80106461-92998a00-8582-11ea-9704-3c30d290b999.png">

## To Reproduce

Download the attached [sample project](https://github.com/tuist/tuist/files/4522874/tuist-lib-sample.zip), run `tuist focus` or open the existing workspace. Try to build the app target.
Notice there are 2 errors:

- In **AppDelegate.swift**, `import SampleLib`: No such module 'SampleLib'
- In **SomeOtherClass.m**, `#import <SampleLib/LibMainFile.h>`: `'SampleLib/LibMainFile.h' file not found`

## Expected behavior

No build error. Public headers and modulemap files are copied to the product.

## Possible Solutions/Step

1. Make Tuist accept a `.modulemap` as valid header file extension;
1. Add a `modulemap` parameter for `Product.library` or to `Headers`
1. When building library target build phases, add a Copy Files step with the needed files and correct path like the screenshot above.

## Desktop (please complete the following information):

- OS: macOS 10.15.3

**Comment by pepibumur** [comment]
Here are my thoughts:
- Considering a modulemap is related to headers, we can provide an API along the lines of: `Headers(modulemap: "./module.modulemap")`.
- If the target that we are generating represents a library, I'd add the necessary build phase that copies the headers into the product's `include/$(PRODUCT_NAME)` path.

What do you think @tuist/core ?

**Comment by kwridan** [comment]
Thats for flagging this @natanrolnik 

> Considering a modulemap is related to headers, we can provide an API along the lines of: Headers(modulemap: "./module.modulemap").

Perhaps it can be defined at the target level? 

```swift
let target = Target(
   name: "MyStaticLibrary",
   product: .staticLibrary,
   // ...
   headers: Headers(
       public: ["MyHeader.h"],
   ),
   modulemap: "module.modulemap"
)
```

While they are closely related to headers, they have [other constructs](https://clang.llvm.org/docs/Modules.html#id23) that allow customising and defining the module as a whole. For example, module maps allow you to define submodules that control how consumers of the library import it.

```swift
import MyModule.SubModule

```


> If the target that we are generating represents a library, I'd add the necessary build phase that copies the headers into the product's include/$(PRODUCT_NAME) path.

👍 

Here are the steps I needed to take to get the sample project working which we could consider for this work:

- Remove the generated headers phase (otherwise multiple phases will end up copying files to the same destination - which Xcode doesn't like 🤐)
- Add the copy files phase as suggested to `include/$(PRODUCT_NAME)` to include the `public` headers (do the `private` headers need to be copied across too?)
- Rename the module map to `module.modulemap` 
   - For static libraries, the file name needs to be `module.modulemap` 
   - For frameworks the name is typically `$(PRODUCT_NAME).modulemap` _(don't think this is a requirement though as Xcode automatically deals with copying the module map file and renaming it)_
   - We can introduce a lint rule that can warn / error if it detects the specified `modulemap` file isn't `module.modulemap` for `.staticLibrary` product types
- Add the module map to the copy files phase
- Set the build settings (those were already there in the sample project), we can automatically set those as part of this improvement

```
"DEFINES_MODULE": "YES",
"MODULEMAP_FILE": "path/to/module.modulemap"
```

Have I missed any steps @natanrolnik @pepibumur ?

**Comment by kervich** [comment]
Any news on this? Instagram's IGListKit won't work as tuist dependency, unless I add headers to the copy build phase in its generated subproject manually. A way to do that in Package.swift would be nice.

**Comment by fortmarek** [comment]
> Any news on this? Instagram's IGListKit won't work as tuist dependency, unless I add headers to the copy build phase in its generated subproject manually. A way to do that in Package.swift would be nice.

I tried using `IGListKit` from `main` and it builds correctly (not the latest released version but that seems to be an issue even with the vanilla Xcode integration).

@natanrolnik let me know if this issue still persists. This issue is very old and the modulemap integration has been quite battle-tested with the SPM integration, so I'm gonna close this. Please, create a new issue if you still experience any issues 🙏
