### ISSUE TITLE
Path to resources containing dots results in failure

### ISSUE THREAD

**Issue by andrespch** [tuist/tuist#1334]
**Describe the bug**

Adding a resource located in a directory whose path has a dot ('.') causes tuist to error with  `Couldn't find a reference for the file at path _path/to/resource_`

**To Reproduce**

- When defining a target, add a resource located inside a folder whose name contains a dot. like 

```swift
Target(
    ...,
    resources: [ "myapp/myframework.framework/myresource.json"],
    ...
```

**Expected behavior**

**Desktop (please complete the following information):**

- OS: macOS
- Version `10.15.4`

**Comment by kwridan** [comment]
Hi @andrespch, thanks for flagging this.

This sounds similar to #330. 

Tuist does support resources that have dot in the path, for example [`fixtures/ios_app_with_framework_and_resources/App`](https://github.com/tuist/tuist/tree/master/fixtures/ios_app_with_framework_and_resources/App) has a resource [`Folder.DotName/resource.txt`](https://github.com/tuist/tuist/blob/master/fixtures/ios_app_with_framework_and_resources/App/Resources/Folder.DotName/resource.txt).

That said, I believe the case you're facing is where the resource is from a framework that is also declared as a dependency.

```swift
Target(
   ...
   resources: [
      "SomeFramework.framework/SomeResource.json",
   ],
   dependencies: [
      .framework(path: "SomeFramework.framework")
 ])
```

That does yield the error you described as the same path ends up appearing twice. 

I guess it's worth asking if that is intended in the first place? Usually resources in frameworks can be accessed via `Bundle(for:)`

e.g.

```swift
let frameworkBundle = Bundle(for: SomeFrameworkClass.self)
let path = frameworkBundle.path(forResource: "SomeResource", ofType: "json")
// ...
```

If there's a genuine need to embed the framework's resource in the main app, a workaround can be used here while this issue is resolved. A symlink to the resource in question can be added in another directory, that way they are treated as two independent paths.

Hope this helps!

**Additional Context**

This may help us troubleshoot this in the future:

Within the `ProjectFileElements`

Resources get processed first

This creates the following elements:

- Group: `SomeFramework.framework`
   - File: `SomeFramework.framework/SomeResource.json`

Dependencies get processed last

This attempts to create this element:
- `File`: `SomeFramework.framework`

However, the logic internally skips this as the path `SomeFramework.framework` is already associated with the Group element for the resource earlier.

@tuist/core we could add a lint rule to flag that files that are also part of dependencies, this could help provide a better error message.

**Comment by andrespch** [comment]
This makes total sense @kwridan the reasons as to why we need to do that are very specific to our project configuration and will hopefully change in the near future, I like the idea about the Symlink, will give it a try, thanks a lot!
