### ISSUE TITLE
microfeatures and CocoaPods

### ISSUE THREAD

**Issue by jeroenleenarts** [tuist/tuist#1339]
**Describe the bug**
Is this documentation still up to date?

https://github.com/tuist/tuist/blob/master/website/markdown/docs/architectures/microfeatures.mdx#external-dependencies

**Additional context**
The project specification indicates you can use a CocoaPod dependency. While the microfeatures architecture document explicitly states you can not.

**Comment by pepibumur** [comment]
👋 @jeroenleenarts, what's the project specification that you are referring to?

**Comment by jeroenleenarts** [comment]
@pepibumur Here using CocoaPods is described: https://tuist.io/docs/usage/dependencies/#cocoapods-dependencies

And in the microfeatures document it states `There's one thing to keep in mind though: you won't be able to use CocoaPods dependencies with your µFeatures`

What is unclear to me is how a CocoaPod could/should be used from a micro framework. :)

**Comment by rowwingman** [comment]
I guess for the µFeatures you will probably have to specify your Podfile. This circumstances can produce some conflicts with Pods. That's why it's possible with to develop  µFeatures with Carthage or without third party dependencies.

To unblock µFeatures with cocoaPods I think one of the way is to write Project file for each dependency (something like this https://docs.bazel.build/versions/master/migrate-cocoapods.html). We can do the same for Tuist. So we will need to write a script that will create Project files from pod spec for each cocoa pods dependency. @pepibumur what do you think about it?
