### ISSUE TITLE
Can not build swift package in Release configuration

### ISSUE THREAD

**Issue by grigorye** [tuist/tuist#1419]
**Describe the bug**
Can not build the package in Release configuration.

**To Reproduce**

1. `swift build -c release`

2. See error:
```
.../tuist/Sources/TuistSupportTesting/Credentials/MockCredentialsStore.swift:2:18: error: module 'TuistSupport' was not compiled for testing
@testable import TuistSupport
```

**Expected behavior**
Build succeeds.

**Screenshots**

**Desktop (please complete the following information):**

- OS: macOS 10.15.5/Xcode 11.5
- Version 1.10.0

**Additional context**
This prevents building/using of Tuist with https://github.com/yonaskolb/Mint, as e.g. the following command fails with the above error.
```
mint run tuist/tuist
```

**Comment by pepibumur** [comment]
Hey @grigorye, you need to specify the product that you’d like to build, otherwise it’ll try to build frameworks that are not compatible with the release mode.

In regards to using Tuist with Mint, unfortunately that’s not supported. Tuist provides is own version installation and management that comes with optimizations to make the installation fast and deterministic.
