### ISSUE TITLE
Use RUNPATH_SEARCH_PATHS instead of embed precompiled frameworks

### ISSUE THREAD

**Issue by fortmarek** [tuist/tuist#1443]
## Need/problem

This issue is a continuation of [this](https://community.tuist.io/t/long-tests-build-times/42) discussion. Lately, we have battled with long build times of our tests since the introduction of microfeatures architecture (which meant a lot of new modules and test suites).
Currently, tuist embeds precompiled framework with a custom build phase where it copies the framework and debug symbols. But this has two issues:
a) wastes disk space
b) from what I have found, slows tests' build times

I have run some tests with [xclogparser](https://github.com/spotify/XCLogParser):
With embed precompiled frameworks
![Firefox_2020-06-11 15-29-24@2x](https://user-images.githubusercontent.com/9371695/84390800-5e446080-abf8-11ea-934a-fb47e6808446.png)

Without embed precompiled framework (leveraging `RUNPATH_SEARCH_PATHS`)
![Firefox_2020-06-11 15-28-15@2x](https://user-images.githubusercontent.com/9371695/84390679-38b75700-abf8-11ea-944b-c7ced854d7ae.png)

Not only using `LD_RUNPATH_SEARCH_PATHS` saves disk space, but it also seems to affect performance where the ratio of compilation time and build time is quite off for the build with embedding precompiled frameworks.

## Detailed design

I think we should be able to remove embed precompiled frameworks phase. Instead, we can use `LD_RUNPATH_SEARCH_PATHS` which apart from default paths would include the individual parent directories of embedded frameworks.
That means if I need to embed `Carthage/Build/ios/MyFramework.framework`, we'd add `Carthage/Build/ios` into `LD_RUNPATH_SEARCH_PATHS` of the given target (while making sure that there are not duplicate directories to keep list of search paths minimal)

# Drawbacks

Why should we *not* do this? Please consider:

- Hopefully, the proposed solution should work for *all* frameworks. If that turns out not to be the case, we can either revert this altogether or we can eg just apply this behavior for Carthage frameworks (if the issue is for frameworks that are not tied to Carthage)

## Alternatives

Alternative is to dig deeper into Embed precompiled frameworks phase and identify how we can improve it, rather than delete it. From my point of view, the proposed solution is more meaningful, but if we decide not to do it, it is a path we can definitely take.

# Adoption strategy

There may be potential issues, but otherwise it should not affect users in any way.

**Comment by kwridan** [comment]
Hi @fortmarek 

Thanks for preparing and outlining this in proposal.

Embedding dynamically linked frameworks is still needed especially when building applications and deploying them to a device. 

Regarding test targets, the additional linker flag suggestion may only work when building tests locally on a simulator, e.g. for tests that can run on a device (e.g. hosted test targets or UI tests) I believe this may not work and yield the infamous `dyld: Library not loaded` error as the path to the Carthage directory is local to the project, whereas embedded frameworks are copied to `/Frameworks` within the application bundle.

**Comment by kwridan** [comment]
I wonder if there are some additional rules we can come up with to remove some redundancies when it comes to embedding frameworks in test targets - e.g. we already do something similar for hosted test targets where we ensure we don't embed/link the same frameworks in the test target that the host app does.

**Comment by fortmarek** [comment]
> the additional linker flag suggestion may only work when building tests locally on a simulator

It might make sense to then apply the linker flag for only tests that do not have a host application?
It may sound overly specific, but for example in our case all tests but one do not have a host application.

**Comment by thedavidharris** [comment]
> Regarding test targets, the additional linker flag suggestion may only work when building tests locally on a simulator, e.g. for tests that can run on a device (e.g. hosted test targets or UI tests) I believe this may not work and yield the infamous dyld: Library not loaded error as the path to the Carthage directory is local to the project, whereas embedded frameworks are copied to /Frameworks within the application bundle.

This is correct, it's pretty much only an option for unit tests.

> It might make sense to then apply the linker flag for only tests that do not have a host application? It may sound overly specific, but for example in our case all tests but one do not have a host application.

_If_ tuist were to go that route then yes.

This is a local optimization done specifically for unit tests cause it scales really poorly with the number of dynamic frameworks. As @fortmarek said the copies of every .framework into every test bundle takes time in space; we actually ran out of space on our CI with some regularity before moving to this (test hosts make this problem even worse). 

Buck/Bazel don't run into this because they just static link all the objects, so you end up with some larger test bundles still, but generally don't have to think about the embeds. I've always wondered if there's some better way to structure modular xctest bundles but never settled on anything.

The biggest concern I have around this is that it isn't the default behavior of how things are linked via XCTest. I'm wondering if a better option would be to detect the present of this flag in a targets configurations, and if so skip the embedding step. This would still allow for local control.

As another aside, I've noticed that Tuist adds any local frameworks to an embed step as well, but if things are compiled into the built product folder then for _unit_ tests they don't need to be embedded either.

**Comment by fortmarek** [comment]
> As another aside, I've noticed that Tuist adds any local frameworks to an embed step as well, but if things are compiled into the built product folder then for unit tests they don't need to be embedded either.

That is true, I think that's something we can do, too!

> I'm wondering if a better option would be to detect the present of this flag in a targets configurations, and if so skip the embedding step

The decision if the embedded step is added or not should be an implementation detail. This is obviously quite a difficult topic, so I think we should try to make the right decision for the tuist users. I say let's implement it and we'll deal with any issues that come up.

But otherwise I agree with what you said @thedavidharris and thanks for your insights!

If there are not any other drawbacks, I will try to add this behavior, will let you know once there is a PR 🙂

**Comment by thedavidharris** [comment]
We do have one framework where no matter what we do, it _has_ to be embedded otherwise it throws dyld errors. It's closed source and something we never quite figured out. Just something to be aware of.

I do wonder whether having some options along these lines would be a good way to handle.

![image](https://user-images.githubusercontent.com/5666250/84534718-6fed3d00-acb8-11ea-9adf-3f3bb36cea53.png)
