### ISSUE TITLE
Environment values for generated Schemes

### ISSUE THREAD

**Issue by dcordero** [tuist/tuist#151]
**Is your feature request related to a problem? Please describe.**

I am not really sure if this is something that can be already done...

Is there a way to define environment variables in the generated schemes definitions via Project.swift?

**Describe the solution you'd like**

I am trying to provide an env variable when running UITests, that I can use to allow starting my tests with the App starting in a predictable status. 

**Additional context**

In that context, I would love to be able to set environment values directly from my Project.swift definition, so that the generated schema for my tests include my env variable.

To make it clearer, I am trying to achieve something like 👇

```
Target(name: "DummyUITests",
    platform: .iOS,
    product: .uiTests,
    bundleId: "io.tuist.DummyUITests",
    infoPlist: "Tests.plist",
    sources: "Tests/**",
    dependencies: [
        .target(name: "Dummy"),
    ],
    scheme: {
        "run": {
            "env": {
                // Env variable used by the app to start in a predictable status for UI tests
                "CLEAN_STARTUP": true    
            }
        }
    })
```

Same could be also useful when integrating third-party dependencies which relay on env variables, (i.e. [uber/ios-snapshot-test-case](https://github.com/uber/ios-snapshot-test-case))

```
Target(name: "DummyTests",
    platform: .iOS,
    product: .unitTests,
    bundleId: "io.tuist.DummyUnitTests",
    infoPlist: "Tests.plist",
    sources: "Tests/**",
    dependencies: [
        .target(name: "Dummy"),
        .framework(path: "Carthage/Build/iOS/FBSnapshotTestCase.framework")
    ]),
    scheme: {
        "run": {
            "env": {
                "FB_REFERENCE_IMAGE_DIR": "$(SOURCE_ROOT)/$(PROJECT_NAME)Tests/ReferenceImages",
                "IMAGE_DIFF_DIR": "$(SOURCE_ROOT)/$(PROJECT_NAME)Tests/FailureDiffs"
            }
        }
    })
```

**Comment by pepibumur** [comment]
> Is there a way to define environment variables in the generated schemes definitions via Project.swift?

There isn't 😛. This would show up sooner or later.

We should definitively add support for this because as you pointed out, snapshot testing libraries rely on environment variables being passed through schemes.

I've been pondering what'd be the best way to introduce the concept of schemes into the manifest without replicating the same models and properties that Xcode projects expose. I'll dump some of my thoughts to start a brainstorm exercise:

- **Project or target schemes:** Should schemes be specified per target *(as you suggested)*, or should projects contain a list of schemes? In the aim of having simple schemes, I lean more towards schemes that are associated to one target. Besides the ones that Xcode generates for you, you can generate extra ones with some custom propertiesl.
- **Which properties expose:** In my experience, the most commonly used properties from schemes are environment variables and some checks that are used for debugging things like push notifications or extensions. We could expose them in the root level of the scheme model. Settings like the list of targets that need to be built, or the find implicit dependencies flag can be inferred.
- **Should we call them schemes:** Schemes in the name that Xcode uses. Although the developers that have worked with Xcode before know what a scheme means, for a developer landing on developing apps with Xcode for the first time the term might be confusing. Since we are building an abstraction, we could take opportunity to reduce any ambiguity the Xcode term might have. Formula? Recipe?

```swift
Target(
  name: "Whatever",
  schemes: [
    Scheme(
      env: ["a", "b"]
    )
  ]
)
```

Thoughts @tuist/contributors ?

**Comment by dcordero** [comment]
Thanks a lot for clarifying @pepibumur.

Those are really good points about the format to describe Schemes into Tuist.

tbh I did not think too much about the format when I initially wrote the issue, I just wanted to make it more clear what I wanted to achieve providing an example as a reference. So here are my ~~2 cents~~ thoughts about the format:

- **Project or target schemes**: I do agree that Target and Schemes in a 1to1 relationship on their definition are probably more than enough for most of the projects, at least in my case I would be very happy with the schemes automatically generated by Tuist except on projects which need custom env variables. Nevertheless, something that might be confusing is that we are actually inverting the order of the elements here. In terms of Xcode, the Schemes are actually the ones wrapping Targets and not the other way around, so I think it might be confusing having a Schemes definition inside a Target definition in Project.swift. This might be palliated anyways with the usage of a different name (Formula, Recipe, etc...) for this configuration in Project.swift as you proposed.

- **Should we call them schemes:** I do agree that having a different name might avoid some misunderstandings.

- **Which properties expose**: I think that supporting env variables might indeed cover most of the cases of using custom properties from schemes. Because of that, I wonder if adding just this env variables to the configuration without any reference to the Schemes might be enough. I think it would make it more simple to use. That would mean keeping all the magic to automatically generate the Schemas hidden, as it is now, but adding the support the optionally define custom properties for those schemes.

```swift
Target(
  name: "Whatever",
  environment: {
      MY_ENV_VARIABLE: 'hello world'
 })
```

**Comment by pepibumur** [comment]
Thank you very much for sharing your thoughts @dcordero. I think we can start by what you suggesting, defining the environment within the target and making sure it's Tuist who generates the scheme for each of those targets with the right configuration.

If we see this is limiting in the future, we can consider extracting them into another element that the target or the project has a reference to.

There's already some [groundwork](https://github.com/tuist/tuist/pull/113) done to generate schemes  but I didn't finish it. We can continue the work on that PR and get this done so that you can set up your projects with the testing framework.

**Comment by pepibumur** [comment]
PR ready @dcordero. I'd appreciate a review from you before merging it whenever you have time. Happy Christmas btw 🎄
