### ISSUE TITLE
Command completion for `bash` and `zsh`

### ISSUE THREAD

**Issue by jeroenleenarts** [tuist/tuist#1592]
## Need/problem

I've been working with Tuist and I've noticed command completion is not available yet. 

As a reference, we are using the same command line helper classes (`TSCUtility`) as the swift package manager. This SPM pull request introduced command completion: https://github.com/apple/swift-package-manager/pull/1256/files

Of interest, there is one tool in Tuist already providing a `ShellCompletion`: https://github.com/tuist/tuist/blob/e1c122d2c73b201eafe4f04325e929f7b506fe04/tools/tuistbench/Sources/TuistBenchmark/Commands/BenchmarkCommand.swift#L20

## Motivation

This change is not a breaking  change, it helps to educate users by providing better discovery of commands and arguments.

## Detailed design

So basically, the required tooling is in place, we only need to add `ShellCompletion` to commands and create some helper logic that helps install the completion scripting at the proper location. I think we should consider two cases here, vanilla and homebrew available.

# Drawbacks

A drawback is that we need to provide some integration outside of the tuistenv tooling to activate the completion.
We need to keep new commands up to date. But we are basically already doing this because the `--help` contents are already gathered and generated as well. Code completion is closely related to help content generation. So it might add some complexity there.

## Alternatives

An alternative would be to provide a manually written completion script or bash and zsh.

# Adoption strategy

Change is non breaking.

# How we teach this

It teaches itself. Just press tab. ;)

We would need to add some documentation on how to install/activate the code completion scripts.

**Comment by fortmarek** [comment]
Hi, thanks for the issue!

autocomplete would be definitely a nice-to-have, but unfortunately, we don't use `TSCUtility` for command definition anymore, we use [Argument parser](https://github.com/apple/swift-argument-parser).

You are referring to `tuist benchmark` but that is a separate tool from tuist itself and has not been migrated to the new argument parser.

I believe that rather than generating the scripts somehow ourselves, we should help push [this PR](https://github.com/apple/swift-argument-parser/issues/1)

**Comment by jeroenleenarts** [comment]
Let's see what this pull brings us: https://github.com/apple/swift-argument-parser/pull/123

**Comment by fortmarek** [comment]
Aaand the PR is merged 🎉  I think we can start implementing it with pointing to master and see when the next release comes out (or we can point to master for a little while if the release does not come soon enough).

Do you want to take a stab it, @jeroenleenarts? Otherwise, I don't mind implementing this.

**Comment by fortmarek** [comment]
And the [new version](https://github.com/apple/swift-argument-parser/releases/tag/0.2.1) of argument parser is in town. I have talked it over with @jeroenleenarts and as he is busy with introducing microfeatures to their team, I'll go ahead and implement it 🙂
