### ISSUE TITLE
SWIFT_ACTIVE_COMPILATION_CONDITION is not overriden if specified in configuration level with `.recommended` or `.essential` global settings

### ISSUE THREAD

**Issue by AlbertMontserrat** [tuist/tuist#1626]
**Describe the bug**
If I setup a `SWIFT_ACTIVE_COMPILATION_CONDITION` setting at configuration level it's not overriden the default setting configuration if we use `.recommended` or `.essential`.

**To Reproduce**

1. Setup a project with settings like this:
```swift
Project(
            name: name,
            settings: Settings(
                base: settings,
                configurations: [
                    .debug(
                        name: "DEBUG-1",
                        settings: ["SWIFT_ACTIVE_COMPILATION_CONDITION": "CUSTOM-1"]
                    ),
                    .debug(
                        name: "DEBUG-2",
                        settings: ["SWIFT_ACTIVE_COMPILATION_CONDITION": "CUSTOM-2"]
                    ),
                    .release(
                        name: "RELEASE-1",
                        settings: ["SWIFT_ACTIVE_COMPILATION_CONDITION": "CUSTOM-1"]
                    ),
                    .release(
                        name: "RELEASE-2",
                        settings: ["SWIFT_ACTIVE_COMPILATION_CONDITION": "CUSTOM-2"]
                    )
                ],
                defaultSettings: .recommended
            ),
            ....
```
2. `tuist generate`
3. Open Project -> Build Settings -> Active Compilation Condition
4. For the release configurations it's fine, for the debug one, there's just `DEBUG`
5. If I hit delete in that field, it appears the custom one

**Expected behavior**
My settings at configuration level should override the default ones, no matter which ones it is (recommended or essential).

**Desktop (please complete the following information):**

- OS: macOS
- Version 10.15.3
- Tuist version: 1.11.0

**Comment by kwridan** [comment]
Hi @AlbertMontserrat, thanks for flagging this!

I believe what you are witnessing is due to `SWIFT_ACTIVE_COMPILATION_CONDITIONS` being classed as a [Target level essential setting](https://github.com/tuist/tuist/blob/master/Sources/TuistGenerator/Settings/DefaultSettingsProvider.swift#L47) and is added by default to the target level settings when selecting `. recommended` or `.essential`.

To override it, you'd need to specify the setting at the target level:

e.g.

https://github.com/tuist/tuist/blob/master/fixtures/ios_app_with_multi_configs/Framework2/Project.swift#L29

```swift

let targetSettings = Settings(
                base: settings,
                configurations: [
                    .debug(
                        name: "DEBUG-1",
                        settings: ["SWIFT_ACTIVE_COMPILATION_CONDITIONS": "CUSTOM-1"]
                    ),
                    .debug(
                        name: "DEBUG-2",
                        settings: ["SWIFT_ACTIVE_COMPILATION_CONDITIONS": "CUSTOM-2"]
                    ),
                    .release(
                        name: "RELEASE-1",
                        settings: ["SWIFT_ACTIVE_COMPILATION_CONDITIONS": "CUSTOM-1"]
                    ),
                    .release(
                        name: "RELEASE-2",
                        settings: ["SWIFT_ACTIVE_COMPILATION_CONDITIONS": "CUSTOM-2"]
                    )
                ],
                defaultSettings: .recommended
            )
// ...
Target(
   name: "MyTarget",
   // ...
   settings: targetSettings
 )
```

Another option is, you could opt out of default settings all together via specifying `.none` that way the values you specify at the project level take effect - but does mean you may need to ensure some of other settings are manually set.

Both don't sound ideal 😞 but may help you make some further progress. Leveraging [`ProjectDescriptionHelpers`](https://tuist.io/docs/usage/helpers/) may help reduce repetition and ensure all your projects/targets are consistent.

There's been a long standing request to somehow opt out of specific build settings (e.g. #920 and #954).

---
cc: @tuist/core 

Some ideas for potential improvements which require more thought 💭

- Mark certain setting internally as "extendable" and set them using `$(inherited) <DEFAULT_VALUE>`
  - e.g. for `SWIFT_ACTIVE_COMPILATION_CONDITIONS` at the target level it would be set as `$(inherited) DEBUG` which should allow values specified at the project level or even in xcconfig to pass through
  - This would need to be considered setting / setting basis (not all values are extendable, some need to be overriden all together e.g. `SWIFT_VERSION`)
- Find a mechanism / way to opt out of specific default settings e.g. `Settings(defaultSettings: .recommended(excluding: ["SWIFT_ACTIVE_COMPILATION_CONDITIONS", "SWIFT_VERSION"]))`, `Settings(defaultSettings: .essential(excluding: ["SWIFT_ACTIVE_COMPILATION_CONDITIONS", "SWIFT_VERSION"]))`
