### ISSUE TITLE
[RFC] UpCarthage should perform bootstrap instead of update

### ISSUE THREAD

**Issue by LukasHromadnik** [tuist/tuist#1634]
## Need/problem

I would like to integrate Carthage setup into `tuist up` action. Currently `UpCarthage` performs `carthage update` which updates all dependencies and doesn't use the `Cartfile.resolved` file with resolved dependencies.

To be able to set the project up with the resolved dependencies it's necessary to perform `carthage bootstrap` instead of `carthage update`.

## Motivation

By updating all dependencies everytime `tuist up` is run, we can end with different version of dependencies. We can also introduce breaking changes to the codebase by updating some dependency that is not well maintained.

Also I think that updating dependencies should be always performed explicitly by the programmer and `tuist up` it's not IMO the right place where to update dependencies.

## Detailed design

From the client's side there should be no change. All changes should be performed under the hood by rewriting `UpCarthage` action and updating `Carthage` interface to support bootstrap.

# Drawbacks

The only drawback comes from the change where current users of `UpCarthage` with the new version have to perform the update of Carthage dependencies by themselves.

## Alternatives

Another option is to add new up action `UpCarthageBootstrap` (or similar naming) and create the `bootstrap` there.

# Adoption strategy

It's a breaking change in terms of the behavior of the up action – `carthage update` and `carthage bootstrap` do very different things.

**Comment by pepibumur** [comment]
Hey @LukasHromadnik, thanks for bringing this up.
You are right on `update` not being the most appropriate command for this. Up tasks are intended to be idempotent, and based on the behavior thar you described, that doesn't seem to be the case for `update`.

As you pointed out, it might be a breaking change for some users, but I don't think it justifies the creation of a major build.

Having said that, feel free to contribute this yourself and make sure the update of the CHANGELOG flags this as a breaking changes. Otherwise we can try to prioritize but I can't promise anything on when it'll be tackled.

**Comment by pepibumur** [comment]
I’ll start working on this one

**Comment by softmaxsg** [comment]
Hey, @pepibumur, did you already start working on the fix? 

I have solved this issue for myself and can make a PR here if you need help with this.

**Comment by fortmarek** [comment]
👋 @softmaxsg I think you can create a PR, it'd be great to get this resolved 🙂
