### ISSUE TITLE
cache warm - does not support CocoaPods

### ISSUE THREAD

**Issue by zdnk** [tuist/tuist#1649]
**Describe the bug**
Cache warm generates the project, but does not take into account that you might have cocoapod dependencies.

**To Reproduce**
Create a project with dynamic framework target linked to the app, create Podfile with some dependency for the framework. 
Use the pod in the framework code.
Run `tuist cache warm`. You will get error that the pod module cannot be found/imported.

**Expected behavior**
Tuist installs pods or uses already generated workspace.

**Desktop (please complete the following information):**

- OS: macOS big sur beta 4
- Version 1.15

**Comment by pepibumur** [comment]
Hey @zdnk,
Thanks for bringing this up. Unfortunately, we don't support caching CocoaPods frameworks because Tuist has no knowledge on CocoaPods dependency graph. My recommendation is that you turn those frameworks into pre-compiled binaries, either by using Carthage, or using a plugin like [CocoaPods Rome](https://github.com/CocoaPods/Rome) or [PodBuilder](https://github.com/Subito-it/PodBuilder). Once they are binaries, they can be declared as binary dependencies and be taken into account from the caching logic.

We plan to add page to the documentation to document how to integrate with CocoaPods in a way that is compatible with the cache.

**Comment by zdnk** [comment]
You misunderstood me. If I want to pre-build/warm a target (dynamic framework) that has a CocoaPod dependency, it is not possible. I dont want to cache cocoapods.
