### ISSUE TITLE
[Feature Request] Support Intent extensions

### ISSUE THREAD

**Issue by andrespch** [tuist/tuist#1676]
## Need/problem

Currently Tuist lacks support for Intent extensions.

## Motivation

Projects setup with Tuist are currently unable to add these extensions as everytime tuist is run, the extension setup is overwritten.

**Comment by kwridan** [comment]
Hi @andrespch, thanks for flagging this.

I believe this is already supported by tuist (there's room for improvement of course).

Most app extensions have a single product type `.appExtension` see [example fixture](https://github.com/tuist/tuist/blob/master/fixtures/ios_app_with_extensions/Project.swift)

The only difference between the different app extensions is some of the attributes in the `Info.plist` (e.g. `NSExtensionPointIdentifier`, for intents it's `com.apple.intents-service`), you can copy those across so that Tuist generates them, or perhaps re-use an existing Info.plist file if you already have one for your intents extension.

Here is an example for intents:

```swift
Target(name: "App",
       // ...
        dependencies: [
            .target(name: "MyIntentsExtension"),
        ]),
Target(name: "MyIntentsExtension",
        platform: .iOS,
        product: .appExtension,
        bundleId: "io.tuist.App.MyIntentsExtension",
        infoPlist: .extendingDefault(with: [
                "CFBundleDisplayName": "$(PRODUCT_NAME)",
                "NSExtension": [
                         "NSExtensionAttributes": [
                                "IntentsSupported": [
                                       // ...
                                ]
                        ],
                        "NSExtensionPointIdentifier": "com.apple.intents-service",
                        "NSExtensionPrincipalClass": "$(PRODUCT_MODULE_NAME).IntentHandler"
                ]
        ]),
        sources: "MyIntentsExtension/**",
        dependencies: [
            
        ]),
```

As I mention there is room for improvement here, but hopefully you should be able to get started generating projects with intents extensions. Let us know if there are any other missing aspects.

Hope this helps

**Comment by andrespch** [comment]
Awesome! Thanks for your message. Will give this a try soon and open a new issue if I a run into issues or if I can think of potential improvements. Will close this now

**Comment by kwridan** [comment]
Thanks @andrespch, I think at the very least updating the docs about this could be useful - I've raised #1678 for this.
