### ISSUE TITLE
tuist feedback

### ISSUE THREAD

**Issue by kwridan** [tuist/tuist#172]
# Tuist Feedback

I wanted to share some feedback from experimenting with `tuist` on one of the projects I’m currently working on. This isn't intended to be a list of issues or things to change per se but just a knowledge share which may be of use.

Some quick background, we're evaluating various tools and libraries to aid us with generating Xcode projects for our modules. Mostly looking at features, workflow and how it could be incrementally adopted. 

## Sample Structure
For the sake of the feedback let’s picture the following simplified working tree.

- Applications
	- Application A
	- Application B
	- ...
- Modules
	- Module A
	- Module B
	- Module C
	- ...
- Third Party
	- External Library A
	- External Library B
	- ...

### Generating Workspaces

The workflow is fantastic, the fact a workspace is always generated is great, allowing you to focus on only the scope of interest. For example, calling `tuist generate` within Module B’s directory will generate a workspace and pull in all the required dependent projects.

We currently have a single workspace, but having projects and workspaces easily generated in a consistent manner makes the multi-workspace workflow more appealing. Only catch here is you won't be able to benefit from any derived data cache for modules built within other workspaces. Given the aim is to build only the modules of interest, i.e. less, this isn't a big problem.

### Defining Projects

Having project definitions in Swift is a great choice!

- Provides syntax error feedback developers are already used to
- Allows defining variables to tidy up the configuration

```swift
let debug = Configuration(xcconfig: "configs/debug.xcconfig")
let release = Configuration(xcconfig: "configs/release.xcconfig")
let customSettings = [
	"SETTING_A": "VALUE_1",
   // ...
]
```

After adding descriptions for a few more modules, I noticed a recurring theme where I repeated certain settings like bundle IDs (in our case it's `${PRODUCT_BUNDLE_IDENTIFIER_PREFIX}.${PRODUCT_NAME:rfc1034identifier}`), build configurations, and some custom build settings (like which warnings to enable / disable). Repetition isn't necessarily a bad thing, however did spark the idea of somehow supporting 3rd party project descriptions / helpers to help simplify the definitions and keep them consistent.

For example, we have the notion of "strict" and "relaxed" warnings, the former is for all new modules and the latter is for some of our older modules. As such we'd like to be able to simplify how that is defined for our projects:

```swift
import CustomProjectDescription

let project = CustomProject(name: "MyNewPorject"
                                   warningsMode: .strict
                                   // ...
                      )
```

I spotted [issue #170](https://github.com/tuist/tuist/issues/170) proposing "include" support in project definitions, that may help alleviate some of these needs.

## Sources & Headers

For an incremental adoption approach, I found myself needing to tweak my local copy of `tuist` to support the following features in order to work with some of our existing modules:

- multiple sources
- excluded sources
- excluded headers

e.g.

```swift
public class Target: Codable {
    // ...
    let sources: [String]
    let excludedSources: [String]
    
    // ...
    let excludedHeaders: [String]
    // ...
}
```

I didn't get as far as resources, but they too would probably need the same treatment for our project.

I appreciate `tuist` is trying to encourage simplifying the project structure, for existing projects however it may prove a little challenging without some flexibility.

## Configurations

In our project we actually have 5 different configurations (arguably a bit excessive) for the different build variants (e.g. Debug, Enterprise Distribution(s), App Store, etc...). It appears `tuist` only supports debug and release. 

I noticed the topic of multiple configurations was brought up in [issue #159](https://github.com/tuist/tuist/issues/159)

I agree, we rarely use the other build configurations locally, however for a largish project like ours, where we are incrementally adopting project generation for our modules, we’re not quite ready to ditch checking in Xcode projects just yet, as such having all the configurations there would help ease the migration. I'm glad to see [#165](https://github.com/tuist/tuist/pull/165) to include support for generating both `debug` and `release` configurations as opposed the previous behavior where only one of them was generated.

## Mixed Language Modules
We have a few mixed language modules that include C++! I noticed the [sources list](https://github.com/tuist/tuist/blob/master/Sources/TuistKit/Models/Target.swift#L8) doesn’t account for `.cpp` files. Is this omission intended?  

Additionally for some of those modules we use custom build scripts which `tuist` supports via actions. However attempting to link against the generated libraries also requires linking `libc++.tbd` which `tuist` doesn’t support. The workaround is to leverage additional linker flags:

`”OTHER_LD_FLAGS”: “-lc++"`

For system frameworks (e.g. `Foundation`), while they are usually resolved implicitly by the build system. For modules with custom build scripts however, sometimes linking against system frameworks is needed explicitly (e.g. Linking in static libraries that reference system frameworks which the module itself doesn't reference). The workaround here again is to leverage additional linker flags:

`”OTHER_LD_FLAGS”: “-framework Foundation"`

Would adding the ability to link against system frameworks and libraries be a welcomed addition to `tuist`? We could perhaps borrow the [implementation from `XcodeGen`](https://github.com/yonaskolb/XcodeGen/blob/master/Sources/XcodeGenKit/PBXProjGenerator.swift#L540)

## Static Libraries
Some of our modules produce static libraries that are only required by a dynamic framework. As such, we do often have scenarios where we require linking frameworks against static libraries.

Currently it appears this is prevented by the [linter rules](https://github.com/tuist/tuist/blob/master/Sources/TuistKit/Linter/GraphLinter.swift#L129)

## Structure

The generated workspace is flat, which is fine for smaller projects, however for larger ones with many projects, this can be overwhelming. 

It would be nice to be able to define the structure in `Workspace.swift` or perhaps it can be inferred via the file system. Would that be something worth proposing / contributing to `tuist`?

It's nice to see that `tuist` favors conventions over configurations. That said different teams may have slightly different conventions, e.g. I see a `Playgrounds` group is generated even though the project may not have one.

## `tuist` as a library

Based on the observations from my experimentation, there are several points which probably wouldn't make sense for `tuist` to adopt (why convolute it for our complex and weird cases). As such I started looking into the feasibility of leveraging `tuist` as a library to cater for our conventions and use cases while still benefiting from the core functionality of `tuist`.

I noticed, `TuistKit` doesn't expose many public classes aside from the commands, I guess it wasn't intended to be used as a library? I do wonder if this is something that would be considered? 

I wanted to see how far I can get by using the internal classes. Most if not all layers had sufficient abstractions, as such writing a custom implementation for some of them should be possible to aid leveraging `tuist` as a library with some adjustments. I can research this further if there's interest.

# Conclusion

I really liked working with `tuist` and can see its great potential! 👍 Thank you for all your hard work on this project.

Happy to contribute and provide further feedback.

**Comment by pepibumur** [comment]
First of all, thank you very much for providing such a detailed and valuable feedback, I appreciate a lot that you took the time to share it with us. I'll answer to your feedback:

### Generating Workspaces

> The workflow is fantastic, the fact a workspace is always generated is great, allowing you to focus on only the scope of interest.

That's exactly what we aim for with the generated format, bringing you focus. We don't generate anything that your project doesn't need. 

> Only catch here is you won't be able to benefit from any derived data cache for modules built within other workspaces. Given the aim is to build only the modules of interest, i.e. less, this isn't a big problem.

That's a good catch, I didn't think about this. I wrongly assumed that the Xcode build system would have a cache per project. I don't think this drawback is that bad though because most of the time you focus on a single project. 

### Defining Projects

> Repetition isn't necessarily a bad thing, however did spark the idea of somehow supporting 3rd party project descriptions / helpers to help simplify the definitions and keep them consistent.

That's something someone brought up as you pointed out. We'd like to add support for it but we haven't had time to implement it yet. Since we leverage the Swift compiler to read the manifest, we can support defining the manifest in multiple files tha are part of the same module. 

To me this is one of the key advantages compared to other formats like json or yaml.

### Sources & Headers

> I appreciate tuist is trying to encourage simplifying the project structure, for existing projects however it may prove a little challenging without some flexibility.

I agree with you. I designed it to encourage simplicity in new projects but I disregarded what that entailed for projects adopting Tuist. Would you mind opening an issue and add any API ideas you might have?

### Configurations

> I agree, we rarely use the other build configurations locally, however for a largish project like ours, where we are incrementally adopting project generation for our modules, we’re not quite ready to ditch checking in Xcode projects just yet, as such having all the configurations there would help ease the migration.

I agree with you. We have already an [issue in the backlog](https://github.com/tuist/tuist/issues/160) to tackle this. Don't hesitate to add your ideas there. Also if you feel like contributing with anything, you are more than welcome.

😜 I'll answer the rest of the feedback later on

**Comment by pepibumur** [comment]
### Mixed Language Modules

> We have a few mixed language modules that include C++! I noticed the sources list doesn’t account for .cpp files. Is this omission intended?

Not really, I've [opened an issue](https://github.com/tuist/tuist/issues/173) to add support for it.

> Would adding the ability to link against system frameworks and libraries be a welcomed addition to tuist?

Definitively. We can add support for specifying linking against system frameworks. [Here's](https://github.com/tuist/tuist/issues/174) the issue to work on this. This is a great idea 👏 

### Static Libraries

> Some of our modules produce static libraries that are only required by a dynamic framework. As such, we do often have scenarios where we require linking frameworks against static libraries.

Don't know what made me think that that type of linking is not possible. That's why I encoded that restriction in a linting rule. I've opened [another issue](https://github.com/tuist/tuist/issues/175) to remove that check and make sure that the linking is properly configured.

### Structure

> It would be nice to be able to define the structure in Workspace.swift or perhaps it can be inferred via the file system. Would that be something worth proposing / contributing to tuist?

Do you think it'd make sense to replicate the same system structure in the workspace? That's feasible but I'm wonderin whether that's something that developers would find valuable. In my experience, most of the projects only have a few projects, so you can navigate through them easily keeping all of them at the root level of the workspace.

> It's nice to see that tuist favors conventions over configurations. That said different teams may have slightly different conventions, e.g. I see a Playgrounds group is generated even though the project may not have one.

The Playgrounds group shouldn't be there if there are no playgrounds *([here](https://github.com/tuist/tuist/issues/176) is another issue for that.)*. Regarding favouring convention over configuration, I'd like to know more from your experience in which areas do you think it'd make sense to be less strict, offering a bit more of configuration. In my experience, I think enforcing a comany-wide convention is challenging but possible. Not only simplifies things but allows developers jump from one project to another without having to re-learn new conventions.

### tuist as a library

> I noticed, TuistKit doesn't expose many public classes aside from the commands, I guess it wasn't intended to be used as a library? I do wonder if this is something that would be considered?

Exactly, I'd rather not expose any internal component as public because we'd need to maintain two public APIs, the command line tool and the API of those components. I'd encourage you to bring your concerns, ideas and proposals that we can discuss and introduce into the project. The original design of Tuist might be restrictive but that doesn't me it's not open to modifications or iterations.

### Conclusion

> I really liked working with tuist and can see its great potential! 👍 Thank you for all your hard work on this project.

Thanks for giving it a try and sharing your experience like this. I can't describe how much I appreciate this gesture from you. Out of curiosity, would you be interested in contributing to the project? If so, just wanted to say that feel free to do it, and if you are not sure, we can discuss the approach that you'd like to take beforehand and then get your hands dirty.

**Comment by kwridan** [comment]
Thanks again for taking the time to write up a thorough reply to all the points and for spawning the follow ups.

Some further replies, 

## Configurations
> I agree with you. We have already an  [issue in the backlog](https://github.com/tuist/tuist/issues/160)  to tackle this. Don’t hesitate to add your ideas there. Also if you feel like contributing with anything, you are more than welcome.

Sure! Will take a look.

## Mixed Language Modules
> Not really, I’ve  [opened an issue](https://github.com/tuist/tuist/issues/173)  to add support for it.

👍

## Static Libraries

> Don’t know what made me think that that type of linking is not possible. That’s why I encoded that restriction in a linting rule. I’ve opened  [another issue](https://github.com/tuist/tuist/issues/175)  to remove that check and make sure that the linking is properly configured.

Will reply in the issue you created, there are some funny cases to consider 🙂

## Structure
> Do you think it’d make sense to replicate the same system structure in the workspace?

It’ll be familiar, and it keeps with the conventions paradigm. Additionally it’ll be consistent to how the files / groups are setup for the sources. 

>  That’s feasible but I’m wondering if that’s something that developers would find valuable. In my experience, most of the projects only have a few projects, so you can navigate through them easily keeping all of them at the root level of the workspace.

I agree for smaller projects *(forgive my overloading of the term ‘project’)* with a handful of Xcode projects this is true and simplicity is more favourable.  

However once you scale up the number of Xcode projects, this rapidly becomes overwhelming - especially for the top level nodes in the tree like the application target.

## tuist as a library
> I'd encourage you to bring your concerns, ideas and proposals that we can discuss and introduce into the project. The original design of Tuist might be restrictive but that doesn't me it's not open to modifications or iterations.

👍 I’ll spawn a separate thread for this after collect some further notes. In fact this may help with the other points,  **Defining Projects**, **Sources & Headers** and **Structure**.

## Conclusion 
> Thanks for giving it a try and sharing your experience like this. I can’t describe how much I appreciate this gesture from you. 

No worries, glad it was well received! 🙂

> Out of curiosity, would you be interested in contributing to the project? If so, just wanted to say that feel free to do it, and if you are not sure, we can discuss the approach that you’d like to take beforehand and then get your hands dirty.

Sure, happy to help where I can. I'll start by contributing further ideas/feedback.

p.s. Feel free to close this issue, we can follow up in the spawned items.
