### ISSUE TITLE
Linting prevents dynamic framework from linking static libraries

### ISSUE THREAD

**Issue by pepibumur** [tuist/tuist#175]
**Describe the bug**
As [reported here](https://github.com/tuist/tuist/issues/172), Tuist prevents dynamic frameworks from linking static libraries. We wrongly assumed that that's not possible, however, it is. We should remove that linting check and make sure Tuist defines the build settings and phases properly for that type of linking.

**Comment by kwridan** [comment]
This does bring with in some additional complexity or rather cases to think about:

- **DynamicFrameworkA**
	- links **StaticLibraryA**
- **DynamicFrameworkB**
	- links  **StaticLibraryA**
- **Application**
	- links **DynamicFrameworkA**
	- links **DynamicFrameworkB**

This will in the simple case actually compile, however Xcode will leave a nice trace at runtime:

```
Class <StaticLibraryClassNameHere> is implemented in /path/to/DynamicFrameworkA and /path/to/DynamicFrameworkB. One of the two will be used. Which one is undefined.
```

We actually end up with a duplicate **StaticLibraryA**, one within each target it's linked into. 

The linter may need to traverse the graph and ensure no other dependency links against the same static library. 

The thing I’m not sure on is if there are cases where a conscious decision is being made to link a static library more than once. I suppose, the lint rule can be changed to warn instead of error out if such a case surfaces in the future.

**Comment by ollieatkinson** [comment]
I would like to tackle this one - what do we think is the best route forward?

I personally think lift the restriction and warn if you link a static library more than once.

**Comment by kwridan** [comment]
There's one more bit, currently we transitively link static libraries to the top level target e.g. (app / unit tests etc...)

```swift
// Graph.swift
    
func linkableDependencies(...) {
     // ...
     switch targetNode.target.product {
        case .staticLibrary, .dynamicLibrary, .framework, .staticFramework:
            // Ignore the products, they do not want to directly link the static libraries, the top level bundles will be responsible.
            break
        case .app, .unitTests, .uiTests:

            let staticLibraries = findAll(targetNode: targetNode, test: isStaticLibrary)
                .lazy
                .map(\.target.productName)
                .map(DependencyReference.product)

            references.append(contentsOf: staticLibraries)
        }
```

We'd need to tweak that slightly to firstly allow frameworks to link static libraries (or static frameworks) and secondly to be aware of linked vs. unlinked static libraries to transitively include.

So in this example: 

![static-dynamic-application](https://user-images.githubusercontent.com/11914919/54067833-f658da80-423c-11e9-843a-2348ae9e332e.png)


The Application shouldn't need to transitively link the Static library
