### ISSUE TITLE
`tuist version` returns the wrong version

### ISSUE THREAD

**Issue by danyf90** [tuist/tuist#1908]
**Describe the bug**
Running `tuist version` using the last tuistenv binary returns `1.18.0` instead of `1.21.0`

**To Reproduce**
1. Go to https://github.com/tuist/tuist/releases/tag/1.21.0
2. Download `tuistenv.zip`
3. Unzip `tuistenv.zip`
4. Run `./tuistenv version`

**Expected behavior**
`1.21.0` should be printed

**Desktop**
- OS: macOS
- Version: 10.15.7

**Comment by yabenatti** [comment]
May I work on this?

**Comment by fortmarek** [comment]
Hi @yabenatti - I think you are more than welcome to try this on! Let us/me know if you need any help with this 🙂

**Comment by yabenatti** [comment]
Okay! Starting to look at it :)

**Comment by yabenatti** [comment]
Hey! 

I was debugging and I noticed that on `TuistEnvKit/Commands/CommandRunner`, the logic is to get the version according to this order:

```func run() throws {
        if case let ResolvedVersion.bin(path) = resolvedVersion {
            try runAtPath(path)
        } else if case let ResolvedVersion.versionFile(_, version) = resolvedVersion {
            try runVersion(version)
        } else {
            try runHighestLocalVersion()
        }
    }
```

So apparently, for me, it tried to install a version (cause I didn't have any), then it showed `1.22.0` (the highest local version) 

Is it possible that you have a pinned version set for your environment? And that's why it shows `1.18.0` ? 
https://tuist.io/docs/usage/managing-versions/#running-tuist

*Kind of offtopic, but on the same version topic*

When running `tuist version` with the source code of the tag `1.21.0`, the version on the `Constants` file is `1.19.0`

```
    public static let version = "1.19.0"
```

Please let me know if I missed anything, this is my first contact with the project ☺️

**Comment by fortmarek** [comment]
Hi! Sorry for the longer response, @yabenatti 🙁 Anyways:

> Is it possible that you have a pinned version set for your environment? And that's why it shows 1.18.0 ?

The only way how to pin the version should be via `.tuist-bin` directory or `.tuist-version` file in the current directory. Are we sure it shows 1.18.0, and not 1.19.0? Because if it was 1.19.0, then the explanation would be down below 👇 

> When running tuist version with the source code of the tag 1.21.0, the version on the Constants file is 1.19.0

That was a mistake, for sure - good catch! I think we should be able to automate this in the release process as it's quite error-prone to update that value manually.

**Comment by yabenatti** [comment]
> Are we sure it shows 1.18.0, and not 1.19.0? 

@danyf90 could you confirm that?

**Comment by danyf90** [comment]
> > Are we sure it shows 1.18.0, and not 1.19.0?
> 
> @danyf90 could you confirm that?

I can confirm I get `1.18.0`

**Comment by danyf90** [comment]
Works fine on 1.30.0
