### ISSUE TITLE
RFC: Add support for copy files phase

### ISSUE THREAD

**Issue by hebertialmeida** [tuist/tuist#2075]
## Need/problem

On Xcode build phases you can add a `New Copy Files Phase` I tried to do that with Tuist while experimenting with my project but I couldn't find a way. It's common for macOS apps, specially document-based that have template files to use that to copy files to folders like `Shared Support`.

This is how it looks like: 
![image](https://user-images.githubusercontent.com/103670/100298958-76b6f600-2f60-11eb-8892-ff0d1d87daf0.png)

## Motivation

Enable more flexibility for macOS project dealing with resources like templates for document-based apps.

## Detailed design

I've started digging inside the current `.pbxproj` to understand how this is composed and it looks something like this:
```c
/* Begin PBXCopyFilesBuildPhase section */
	1A4A39C2220D431400BFBC51 /* Copy Templates */ = {
		isa = PBXCopyFilesBuildPhase;
		buildActionMask = 2147483647;
		dstPath = Templates;
		dstSubfolderSpec = 12;
		files = (
			BFA3F0D42398C4B700FCC1EB /* Alice.pinery in Copy Templates */,
			BF3F6647238CC6400039D642 /* Empty.pinery in Copy Templates */,
			BF3F6646238CC6360039D642 /* Data-science-at-command-line.pinery in Copy Templates */,
		);
		name = "Copy Templates";
		runOnlyForDeploymentPostprocessing = 0;
	};
/* End PBXCopyFilesBuildPhase section */
```

The api for `PBXCopyFilesBuildPhase` implemented on [XcodeProj](https://github.com/tuist/XcodeProj) and is being used by [BuildPhaseGenerator.swift#L348](https://github.com/tuist/tuist/blob/main/Sources/TuistGenerator/Generator/BuildPhaseGenerator.swift#L348) and [LinkGenerator.swift#L182](https://github.com/tuist/tuist/blob/main/Sources/TuistGenerator/Generator/LinkGenerator.swift#L182). I believe that the ideal would be to expose that for the `Target`, perhaps as a `TargetAction`.

Following the current API we could have something like that:
```swift
public struct TargetAction: Codable, Equatable {
    //...

    public static func post(
        destination: PBXCopyFilesBuildPhase.SubFolder,
        subpath: String,
        name: String,
        resources: [Path]
    ) -> ProjectDescription.TargetAction

    //...
}
```

Usage:
```swift
Target(
    name: "App",
    platform: .macOS,
    product: .app,
    bundleId: "io.tuist.App",
    actions: [
        .post(
            destination: .sharedSupport,
            subpath: "Templates",
            resources: ["App/SharedSupport/**"],
            name: "Copy Templates"
        )
    ]
)
```

# Drawbacks

I don't thing `PBXCopyFilesBuildPhase.SubFolder` is exposed, so this should be wrapped by a local type and/or exposed.

## Alternatives

I don't have any alternatives in mind, but I'm might be wrong and this is already possible somehow.

# Adoption strategy

This would not be a breaking change, easy to adopt.

# How we teach this

As everything else this should be well documented.

# Unresolved questions

- I'm not very sure about this API I've suggests, would that would be possible?
- I don't know if it makes sense to have a pre and post actions, from my experience this is usually post.
- The Xcode implementation has a `Copy only when installing`, that's probably something to consider adding as well.

**Comment by fortmarek** [comment]
Hi @hebertialmeida, thanks for writing up this RFC!

I believe that this is currently not possible, unfortunately.

Therefore, a new API will be necessary - I think the implementation of it can be similar to `resources`. Both in terms of API and implementation.

> I believe that the ideal would be to expose that for the Target, perhaps as a TargetAction.

I don't think it should be a `TargetAction`, but rather a build phase? I think we should really do something similar as we do for `resources`.

> Following the current API we could have something like that:

This seems to me like it unnecessarily exposes complexity to the user - I believe we can do better and let the user specify what they want to copy and create the appropriate build phase ourselves.

Maybe something similar to this would be better:
```swift
/// In ProjectDescriptionModule
public struct Target {
....
   let bundledFiles: [BundledFile]
....
}

public struct BundledFile {
   let destination: AppFileDestination
   let subpath: String
   let file: AbsolutePath
}
```

If it makes sense for `file` to be a directory, maybe we can change `AbsolutePath` to `FileElement`.

I am not 100 % sure about `BundledFile` naming, too - does it capture the intent well enough? 

Anyways, we can then create a build phase internally - grouping the files by destination and subpath, instead of forcing the user to do that and lowering the complexity of adding bundled files.

> The Xcode implementation has a Copy only when installing, that's probably something to consider adding as well.

I personally would keep this unchecked - if users find a need to configure this, we can try to add support for configuring this.

I don't much experience with this, though, so I'd appreciate some input from @tuist/core @pepibumur @kwridan 🙂

**Comment by hebertialmeida** [comment]
Hey @fortmarek, thanks for the feedback! That makes sense to not be part of actions, I'm opening a draft PR so you can take a look and we can discuss naming and API
