### ISSUE TITLE
RFC: Plugins Edit

### ISSUE THREAD

**Issue by fortmarek** [tuist/tuist#2094]
## Need/problem

As [plugins PR](https://github.com/tuist/tuist/pull/2026) nears its completion, we should think about how to enhance this feature further. Currently, users expect to be able to edit their manifests and project description helpers in Swift with the power of autocompletion - unfortunately that does not work right now for plugins.

## Detailed design

If you run `tuist edit` inside a folder (or some of its subfolders) that contains `Plugin.swift`, we should generate a project where user could conveniently edit it. As more plugins will be available, we should make a structure similar to one in the repository:
```
| -- Plugin.swift
|     | -- ProjectDescriptionHelpers
|     |     | -- SomeHelperfile.swift
|     | -- Templates
....
```

Then there is a case when you run `tuist edit` in a tuist project (with `Project.swift`) and you have `.local` plugin - in this case, I'd expect that it'd be copied to the edit project, too. I'd do a new folder on the same level as `Manifests`, so the structure would then be something similar to this:
```
| -- Manifests
|     | -- Project.swift
|  -- Plugins
|     | MyPlugin
|     |     | -- Plugin.swift
```

The reason for adding this additional support for local plugins is that it's extremely useful for faster iteration of your plugins development.

# Adoption strategy

This will be purely additive, so we'll just have to update the documentation

# Unresolved questions

- What happens when you have `Plugin.swift` and `Project.swift` *in the same directory*? (I'd lean to, at least for now, to generate edit project for `Project.swift` and ignore plugin structure in this case)

cc @luispadron

**Comment by luispadron** [comment]
This looks great and exactly what I was expecting from `tuist edit`.

Think we should update the repository structure to more closely match this:
```
.
├── Mappers
├── OtherPluginType
├── Plugin.swift
├── ProjectDescriptionHelpers
│   ├── Project+Helpers.swift
│   └── ProjectExtensions.swift
└── Templates
    ├── Feature
    │   └── feature.swift
    └── Framework
        └── framework.swift
```

But otherwise this will be awesome to have so we can provide users with autocomplete and suggestions. 

> What happens when you have Plugin.swift and Project.swift in the same directory? (I'd lean to, at least for now, to generate edit project for Project.swift and ignore plugin structure in this case) @fortmarek 

What would be wrong about loading both here? From what I understand there shouldn't be a reason `Project.swift` and `Plugin.swift` can't coexist in the same directory no? We could load it similarly to how we have it for local plugin:

```
| -- Manifests
|     | -- Project.swift
|  -- Plugins
|     | MyPlugin
|     |     | -- Plugin.swift
```

If we instead want to wait on adding support for loading both that's fine! Just want to make sure we're not missing an issue here.

Another thought: 💭
- Maybe we want to add a ticket for `tuist init --type=plugin` or something like that? If we can init a project we should be able to do the same for a plugin.
