### ISSUE TITLE
Getting Unexpected Duplicate Task Build Failure After Generating Project

### ISSUE THREAD

**Issue by jsorge** [tuist/tuist#2153]
**Describe the bug**
When using Tuist to generate a project which has a Firebase Swift Package dependency, I'm getting an error that says:

```
Showing All Messages
Unexpected duplicate tasks:
1) Target 'MyApp' (project 'MyApp') has copy command from '/Users/q1214382/Library/Developer/Xcode/DerivedData/MyApp-cyibxnzjvgbjdmcpeedjlxfkbohm/SourcePackages/artifacts/Firebase/FIRAnalyticsConnector.xcframework/ios-i386_x86_64-simulator/FIRAnalyticsConnector.framework' to '/Users/q1214382/Library/Developer/Xcode/DerivedData/MyApp-cyibxnzjvgbjdmcpeedjlxfkbohm/Build/Products/Debug-iphonesimulator/MyApp.app/Frameworks/FIRAnalyticsConnector.framework'
2) Target 'MyApp' (project 'MyApp') has copy command from '/Users/q1214382/Library/Developer/Xcode/DerivedData/MyApp-cyibxnzjvgbjdmcpeedjlxfkbohm/SourcePackages/artifacts/Firebase/FIRAnalyticsConnector.xcframework/ios-i386_x86_64-simulator/FIRAnalyticsConnector.framework' to '/Users/q1214382/Library/Developer/Xcode/DerivedData/MyApp-cyibxnzjvgbjdmcpeedjlxfkbohm/Build/Products/Debug-iphonesimulator/MyApp.app/Frameworks/FIRAnalyticsConnector.framework'
```

**To Reproduce**
Using the [Getting Started](https://tuist.io/docs/usage/getting-started/) example as a starting point, do the following:

1. Add the Firebase Swift Package to the project:

```
 extension Package {
    static var firebase: Package {
        return Package.remote(url: "https://github.com/firebase/firebase-ios-sdk.git", requirement: .exact("7.1.0"))
    }
}
``` 

2. Add dependencies to the `MyApp` target for the `FirebaseCrashlytics` product:

```
.package(product: "FirebaseAnalytics")
```

3. Run `tuist generate` and open the workspace
4. Attempt to build the project

**Expected behavior**
The project should build

**Screenshots**

**Desktop (please complete the following information):**

- OS: macOS 10.15.7
- Version: 1.26.0

**Additional context**
Below is a link to my project. You'll notice all the changes that I made from the base template are in the Tuist/ProjectDescriptionHelpers/Project+Templates.swift file.

[MyApp.zip](https://github.com/tuist/tuist/files/5704005/MyApp.zip)

**Comment by jsorge** [comment]
I made a quick XcodeGen project and added the Firebase package to it, and it generates & builds as I would expect (I'll attach it at the bottom of this comment).

I also ran xcdiff on the two projects and got this output, which I hope will be helpful:

❌ FILE_REFERENCES
❌ BUILD_PHASES > "MyApp" target
✅ COPY_FILES > "MyApp" target
❌ TARGETS > NATIVE targets
✅ TARGETS > AGGREGATE targets
✅ HEADERS > "MyApp" target
❌ SOURCES > "MyApp" target
❌ RESOURCES > "MyApp" target
✅ CONFIGURATIONS > Root project
❌ SETTINGS > Root project > "Debug" configuration > Base configuration
❌ SETTINGS > Root project > "Debug" configuration > Values
❌ SETTINGS > Root project > "Release" configuration > Base configuration
❌ SETTINGS > Root project > "Release" configuration > Values
❌ SETTINGS > "MyApp" target > "Debug" configuration > Base configuration
❌ SETTINGS > "MyApp" target > "Debug" configuration > Values
❌ SETTINGS > "MyApp" target > "Release" configuration > Base configuration
❌ SETTINGS > "MyApp" target > "Release" configuration > Values
❌ SOURCE_TREES > Root project
❌ DEPENDENCIES > "MyApp" target
❌ LINKED_DEPENDENCIES > "MyApp" target

XcodeGen app:
[MyApp-XcodeGen.zip](https://github.com/tuist/tuist/files/5704654/MyApp-XcodeGen.zip)

**Comment by ferologics** [comment]
I reproduced your issue error:
![image](https://user-images.githubusercontent.com/5576161/102402781-8f597f80-3fe5-11eb-81ea-f5a34b1b9029.png)
I don’t see any problems with how you are setting up the dependencies. It must be an issue specific to the Firebase SPM package. My best guess is that inside of those two products they use some shared dependency, and because of it the static libraries duplicate some tasks? You could try defining a local package that implements both dependencies and exports them as one package. This is just a hypothesis, I’m not sure if it would work once you link this local package.

**Comment by ferologics** [comment]
This seems to be related: https://stackoverflow.com/questions/64129750/swift-package-manager-unexpected-duplicate-tasks-target-apptests-project-app

**Comment by ferologics** [comment]
Looks like other Tuist users have experienced this issue https://community.tuist.io/t/unexpected-duplicated-tasks-when-adding-firebase-sp/147 @jmbene @tuist/core

**Comment by kwridan** [comment]
Thanks for flagging this and the investigation into this.

It was really helpful having the sample project to replicate and troubleshoot the issue. From comparing the working cases in manually created projects, XcodeGen and Tuist I spotted a few differences:

**1) Package products in Xcode contain a reference to their host package**

e.g.

```diff
/* Begin XCSwiftPackageProductDependency section */
		42CAAC52258A8E770054121C /* FirebaseAnalytics */ = {
			isa = XCSwiftPackageProductDependency;
+			package = 42CAAC51258A8E770054121C /* XCRemoteSwiftPackageReference "firebase-ios-sdk" */;
			productName = FirebaseAnalytics;
		};
		42CAAC54258A8E770054121C /* FirebaseCrashlytics */ = {
			isa = XCSwiftPackageProductDependency;
+			package = 42CAAC51258A8E770054121C /* XCRemoteSwiftPackageReference "firebase-ios-sdk" */;
			productName = FirebaseCrashlytics;
		};
/* End XCSwiftPackageProductDependency section */
```

Currently the Tuist generated projects do not include this - that said, that didn't seem to be the cause of this issue.


**2) Embed Frameworks build phase**

I noticed oddly that removing the "Embed Frameworks" build phase in the Tuist generated project fixes the build issue. This was [first reported](https://github.com/tuist/tuist/pull/1907#issuecomment-718750200) by @olejnjak. 

Digging a bit further I noticed that when manually creating the "Embed Frameworks" build phase in Xcode (e.g. when marking a dependency as needing be be embed) - there's a very subtle difference in the build phase created.

```diff
/* Begin PBXCopyFilesBuildPhase section */
		42D8C77D258A95F800C9B82A /* Embed Frameworks */ = {
			isa = PBXCopyFilesBuildPhase;
			buildActionMask = 2147483647;
+			dstPath = "";
			dstSubfolderSpec = 10;
			files = (
				42D8C77C258A95F800C9B82A /* MyFramework.framework in Embed Frameworks */,
			);
			name = "Embed Frameworks";
			runOnlyForDeploymentPostprocessing = 0;
		};
/* End PBXCopyFilesBuildPhase section */
```

I noticed even in the Tuist generated project attempting to embed a new framework, Xcode created a whole new Embed frameworks build phase - it doesn't recognise the one already added by Tuist due to this small mismatch.

I tested fixing this in #2156 and it seems to have resolved this particular issue.

---

The interesting thing is, we already have a [fixture](https://github.com/tuist/tuist/tree/main/fixtures/ios_app_with_remote_swift_package) that verifies generated projects with remote dependencies builds fine, however it looks like this issue surfaces specifically for `FirebaseAnalytics`. Looking at the `Package.swift` it seems the difference thee is that `FirebaseAnalytics` is a binary target, it could very well be the cause of surfacing this issue.

The fix #2156 should hopefully solve this, but worth noting the current Swift Packages integration in Tuist is quite simplistic and doesn't cover many of the edge cases which you may hit once you start having multiple targets depending on the same packages (see https://github.com/tuist/tuist/issues/1820 https://github.com/tuist/tuist/issues/1648). The work on https://github.com/tuist/tuist/issues/1674 may help address some of those shortcomings in the future.

**Comment by pepibumur** [comment]
Thanks for such a thorough investigation @kwridan. I believe more issues will surface as SPM adds supports for more target and dependency types. Some of which, like Firebase, have an upstream effect on the graph. This explains why Apple integrates the dependencies at build time.
As you pointed out, until we support a direct integration with SPM, there will be cases that we won't fully support.

**Comment by ferologics** [comment]
Found a related radar, though it mentions that the issue only happens for unit test target https://bugs.swift.org/browse/SR-13739

**Comment by jsorge** [comment]
Thank you so much!

**Comment by AndrewSB** [comment]
I'm noticing a similar problem to this for the Instabug SPM framework distributed over at https://github.com/Instabug/Instabug-SP
