### ISSUE TITLE
tuist archive

### ISSUE THREAD

**Issue by akun1** [tuist/tuist#2160]
**Expected behavior**
use the command `tuist archive` to archive a project/scheme

**Additional context**
Is this possible?

Can't seem to find in docs, but there is some code around archiving using xcodebuild [here](https://github.com/tuist/tuist/blob/main/Sources/TuistCore/Automation/XcodeBuildControlling.swift), just not sure where/how to use it.

**Comment by fortmarek** [comment]
Hi @akun1!

Unfortunately, no such command is available. The code you are referring to is currently used for `tuist cache`.

But ☝️ such a feature could definitely be added! I think we could add `tuist archive`. Would you be interested in contributing such a feature? I'd gladly give you introduction to the project, so it's easier for you.

**Comment by akun1** [comment]
Yes, I would be interested! How do I sign up for this introduction to the project? 😃

**Comment by fortmarek** [comment]
It'd probably best if you hit me up on our [slack](https://slack.tuist.io/) for a more synchronous communication 🙂 . We can either have a quick call or I can give you some pointers, whatever you prefer!

**Comment by akun1** [comment]
Awesome, will reach out!

**Comment by ivanglushko** [comment]
Hey guys! Asking the same 😅
The feature would be extremely helpful for our ci pipeline.
I've migrated fully to Tuist now and it's been amazing so far ❤️

What exactly doest **tuist build** command do? 
Builds a project in a release mode but no archive action run right?

P.S all I have is a basic **Config** file generated by **Tuist** so no custom configurations here.
Thanks in advance!

**Comment by fortmarek** [comment]
Thanks for the interest @ivanglushko!

> Builds a project in a release mode but no archive action run right?

Depends on the scheme's default. It will be probably debug IMHO, though.

I believe this command would make sense as it's similar to `tuist build`. We were also thinking about adding `tuist release` but I honestly think that this should probably be a "Task" (API that does not exist, yet, but that we'd like to add and that'd work similar to `Fastfile` with some important differences, though) as it will be hard to make `tuist release` work for all the teams out there.

I can give you some pointers if we decide to implement it (no prior contributing experience with tuist development is needed!). @pepibumur @kwridan thoughts about adding `tuist archive`? While it's a yet-another-command, I think the knowledge of the graph will make for a more convenient API than eg. `xcodebuild` offers. In the future we could also re-use cache and so if user ran `tuist archive MyApp`, it'd build only `MyApp` and otherwise used already cached frameworks.

**Comment by fortmarek** [comment]
After some consideration, this is probably a good candidate to become a [task](https://docs.tuist.io/commands/task/). AFAICT, this won't use anything from the core of tuist and therefore can be done via a [plugin](https://docs.tuist.io/plugins/creating-plugins/#tasks). I can give pointers to anyone who'd like to implement this 🙂

**Comment by danyf90** [comment]
You can use standard `xcodebuild` command to archive a project generated with tuist.
If you want, you can create a plugin that would wrap this in a `tuist archive` command.
