### ISSUE TITLE
Test coverage not enable for xxx-Project when setting enableCodeCoverage on the options of the project

### ISSUE THREAD

**Issue by unxavi** [tuist/tuist#2185]
**Describe the bug**
Test coverage not enable for scheme `xxx-Project` when using option `. enableCodeCoverage `

**To Reproduce**

1. Create a directory **example** and go to this path
2. Init a new Tuist project` tuist init --platform ios`
3. `tuist edit` and enable `.enableCodeCoverage` on the project options
4. Review the scheme for `xxx-Project`

**Expected behavior**
`xxx-Project` should have code coverage enable and the targets to collect coverage should be define

**Screenshots**
![image](https://user-images.githubusercontent.com/3817679/102862871-0d78b480-4432-11eb-8d5f-1a508cfdbd6e.png)

**Desktop (please complete the following information):**

- OS: macOS
- Version 11.1

**Additional context**
I've a little concern about running unit test on all targets, in this example project for example, if we enable test coverage for the targets:

![image](https://user-images.githubusercontent.com/3817679/102863647-2b92e480-4433-11eb-9278-2254cc180257.png)

And run the test with `swift test Example-Project`, the coverage shows up wrong:

![image](https://user-images.githubusercontent.com/3817679/102864051-cc819f80-4433-11eb-8e35-264cbf61accd.png)

This two example frameworks actually have 0% coverage, I image it's because the target with the app is running on the test and the AppDelegate calls code from the **ExampleUI** and **ExampleKit** and that mess up the coverage report

![image](https://user-images.githubusercontent.com/3817679/102864240-123e6800-4434-11eb-937c-e8b477d26221.png)

Lines 19 and 20

I am not sure how to overcome this issue

**Comment by kwridan** [comment]
Hi @unxavi - indeed it seems the enableCondeCoverage flag isn't respected the the `-Project` scheme, something that could be added to ensure consistency with the other schemes.

As for the concern you raised, it's an interesting one. To my understanding, the way coverage is if the code paths are exercised during a test run, that isn't necessarily the same as there is a dedicated unit test for that code paths performing a logical test on it. 

> This two example frameworks actually have 0% coverage, I image it's because the target with the app is running on the test and the AppDelegate calls code from the ExampleUI and ExampleKit and that mess up the coverage report

Indeed that is what in the example the coverage reports 100%

A few options to mitigate this:

- In a non trivial app like the example, this may not be an issue as the default app launch code paths will most likely not exercise 100% of the code paths 😅
- If that is still a concern, another (slightly controversial) approach could be to detect you are running under test and display skip spinning up the app main code paths _(e.g. via checking if `ProcessInfo.processInfo.environment["XCTestConfigurationFilePath"]` exists)_
- A safer approach could be to have a dedicated dummy host app for tests should you need a host app rather than your production application 
- Create custom fine grained workspace level schemes where you control which test targets are run _(we actually do something similar to this option rather than rely on `-Project` scheme, e.g. we have `AllUnitTests`, `AllUITests`, `AllIntegrationTests` etc..., which have different CI rules and we get to see the coverage results for each classification of tests)_ 

Hope this helps!

ps. if you're interested in helping fix the issue of respecting the configuration option, happy to guide you through it.
