### ISSUE TITLE
No project configuration is created by default

### ISSUE THREAD

**Issue by danyf90** [tuist/tuist#2370]
**Describe the bug**
When defining a project without specifying a custom `Settings` parameter, no configurations are created

**To Reproduce**
1. Define a project without specifying the `settings` parameter (and hence use the `nil` default
2. try to run `tuist build --configuration release` (Or any variant, like `Release`)
3. Error `The scheme's targets don't have the given configuration Release. Defaulting to the scheme's default` is shown

**Expected behavior**
Debug and Release configuration should be created if no specific configurations are defined in the project (as done by SPM)

**Screenshots**

**Desktop (please complete the following information):**

- OS: macOS
- Version 1.31.0

**Additional context**

**Comment by danyf90** [comment]
cc @pepibumur

**Comment by fortmarek** [comment]
Hi @danyf90, thanks for raising this!

This does seem to be an issue, but the problem is not that the configuration is not generated - it is.
The problem is in [BuildGraphInspector](https://github.com/tuist/tuist/blob/main/Sources/TuistAutomation/Utilities/BuildGraphInspector.swift#L61) if I understand the issue properly - and the reason is that there we actually look at `target.settings` which is, indeed, nil if not specified.

In the function in `BuildGraphInspector` what we need is not only get the `Target` but also the `Project` that the `Target` is defined in. You could then do `target.settings ?? project.settings` where `project.settings` is always defined. 

The same is necessary for `TestService`, too.

Would you be willing to make a fix for this? Otherwise, I could do it as well 🙂
