### ISSUE TITLE
Linting with Tuist returns wrong exit code, always returns 0

### ISSUE THREAD

**Issue by parse** [tuist/tuist#2421]
**Describe the bug**
Use Swiftlint and setup a config in `Tuist/.swiftlint.yml`. If you have violations you should receive an exit code that is non-zero. However, it seems like the return code is always 0. 

**To Reproduce**

1. Setup Swiftlint with a config file
2. Have no violations and run `tuist lint code` and get `Done linting! Found 0 violations, 0 serious in 94 files.`, return code is 0 (can be seen by using `echo $?`)
3. Create some violations and run `tuist lint code` and get `Done linting! Found 4 violations, 0 serious in 94 files.`, return code is 0 (can be seen by using `echo $?`)

**Expected behavior**
A failing case should return e.g. 1 as return code.

**Desktop (please complete the following information):**

- OS: macOS
- Version: 1.31.0

** Context**
Trying to use this command instead of using a standalone swiftlint installation in my CI.

**Comment by pepibumur** [comment]
Thanks for reporting this @parse. It seems a legit error. Would you like to take a stab at debugging and fixing this? 

[This is the line](https://github.com/tuist/tuist/blob/main/Sources/TuistLinting/Utilities/CodeLinter.swift#L36) where we run `swiftlint` passing the right arguments. Notice that it's an asynchronous observable that we then make synchronous using `toBlocking()`. If the command raises that should lead to an error that bubbles ups. My 2 guesses are:

- Errors are not propagated. I don't think this is the issue because we have tests in place to test this.
- Swiftlint is not returning the expected exit status.

**Comment by parse** [comment]
> Thanks for reporting this @parse. It seems a legit error. Would you like to take a stab at debugging and fixing this?
> 
> [This is the line](https://github.com/tuist/tuist/blob/main/Sources/TuistLinting/Utilities/CodeLinter.swift#L36) where we run `swiftlint` passing the right arguments. Notice that it's an asynchronous observable that we then make synchronous using `toBlocking()`. If the command raises that should lead to an error that bubbles ups. My 2 guesses are:
> 
> * Errors are not propagated. I don't think this is the issue because we have tests in place to test this.
> * Swiftlint is not returning the expected exit status.

I found something regarding warnings being treated as errors: https://github.com/realm/SwiftLint/issues/2130#issuecomment-377801406

It seems like one can pass in the flag `--strict` and that would trigger them as errors. In that case I guess the question is if tuist would like to support the command line flags that `swiftlint` itself does?

**Comment by laxmorek** [comment]
I think we can add `--strict` to `tuist lint code`.

Some `tuist`'s commands supports flags (like: https://tuist.io/docs/commands/graph/).

For sure we don't want to mimic every `SwiftLint CLI` flag in `tuist` but IMO `--strict` flag is a good candidate to add.
