### ISSUE TITLE
Custom UI Test scheme not executing tests

### ISSUE THREAD

**Issue by jakeatoms** [tuist/tuist#2430]
**Describe the bug**
When replacing an auto-generated test `Scheme` with a custom `Scheme` added to the `Project`, the resulting scheme sets `shouldUseLaunchSchemeArgsEnv` in the test action to `NO` while the auto-generated `Scheme` sets that to `YES`. The end result is that the tests fail to execute in Xcode.

**To Reproduce**

1. Create a `Scheme` to run UI tests that has custom arguments and environment variables.
2. Add to the `Project` definition.
3. Generate the workspace.
4. Execute the Test action for the scheme.

**Expected behavior**
App should build, install, and execute UI tests.

**Actual behavior**
App builds, but fails to execute any tests (though Xcode says it ran successfully)

**Screenshots**
<img width="352" alt="image" src="https://user-images.githubusercontent.com/3605966/106793172-22e22080-6625-11eb-9eec-b8d2909f89d6.png">

<img width="338" alt="image" src="https://user-images.githubusercontent.com/3605966/106793619-b156a200-6625-11eb-9cc8-cd4089b4d36f.png">

**Desktop (please complete the following information):**

- OS: macOS
- Version 10.15.7
- Xcode 11.7

**Comment by jakeatoms** [comment]
I've started in on exposing this flag and discovered this logic in the Scheme mapper:
```swift
let shouldUseLaunchSchemeArgsEnv: Bool = args == nil && environments == nil
```

This is undocumented behavior and I'd like to propose an alternative API for the `TargetAction` initializer. Rather than accepting an optional `Arguments` value and then keying on that, what would you think of using an enum like this?

```swift
enum ArgumentBehavior {
    case custom(Arguments)
    case inherit
}
```

This communicates the intent in the API and eliminates impossible state. I would keep the existing initializer for backwards compatibility, but deprecate the API in favor of this approach. Please let me know what you think!

**Comment by kwridan** [comment]
Thanks for the follow up on this @jakeatoms 

If I understood the issue you are experiencing, the UI tests target is failing due to missing launch arguments and environment in it's scheme?

Mind sharing a snippet of your project manifest? _(you can obscure/replace any sensitive data you don't wish to share of course)_

If it helps we have a few examples you can also compare with in [`fixtures/ios_app_with_custom_scheme`](https://github.com/tuist/tuist/tree/main/fixtures/ios_app_with_custom_scheme) and  [`fixtures/ios_app_with_tests`](https://github.com/tuist/tuist/tree/main/fixtures/ios_app_with_tests) (this one has UI tests). If you're able to reproduce the issue you're witnessing in any of those may help get a better grasp as to what is happening.

> This is undocumented behavior and I'd like to propose an alternative API for the TargetAction initializer.

Indeed we can do a better job at documenting this https://github.com/tuist/tuist/pull/2432

>  Rather than accepting an optional Arguments value and then keying on that, what would you think of using an enum like this?

Indeed this could help clarify the intention, that said specifying the arguments is optional:

e.g.

```swift
let userScheme = Scheme(name: "CustomScheme",
                        shared: false,
                        buildAction: BuildAction(targets: ["App"]),
                        testAction: TestAction(targets: ["AppTests"]),
                        runAction: RunAction(executable: "App"))
```

This means having a default value of `nil` or `.inherit` (which I agree clarifies the intention much better) both convey the "pick the default behaviour" as it hasn't been explicitly specified - I may be missing the issue you are articulating?

Thanks again @jakeatoms !

**Comment by danyf90** [comment]
Close because we are not getting answer from the author
