### ISSUE TITLE
How to set if I have custom name of AppIcon?

### ISSUE THREAD

**Issue by jinuman** [tuist/tuist#2439]
Hi. First of all, I really appreciate what you guys have done. 😄

**Describe the bug**
I have AppIcon name like `AppIcon-Winter` and the path is something like `MyProject/Resources/Images.assets/`

My main target looks like below.
```Swift
Target(
    name: "Playground",
    platform: .iOS,
    product: .app,
    bundleId: "com.jinuman.Playground",
    infoPlist: "Playground/Supporting Files/Playground-Info.plist",
    sources: ["Playground/Sources/**"],
    resources: ["Playground/Resources/**"],
    dependencies: [
        .cocoapods(path: ".")
    ]
),
```

My project xcconfig saids 
* ASSETCATALOG_COMPILER_APPICON_NAME=AppIcon-Winter

And I cannot find how to figure this out from [document](https://tuist.io/docs/usage/project-description/#configuration)

Could anyone help me find solution?

**Comment by kwridan** [comment]
Hi @jinuman - thanks for raising this.

I believe the issue you're seeing relates to Tuist specifying some default settings at the target level which override the one you have specified in the xcconfig.

![Screenshot 2021-02-05 at 06 59 56](https://user-images.githubusercontent.com/11914919/107000903-964c7500-6780-11eb-9968-7a46628fdf73.png)


There are a few options to help you set custom App Icon names depending on your use case.

### 1) Via Target Settings

To override Tuist's default value for that target build setting, you can explicitly specify it as a target level setting:

```swift
let targetSettings = Settings(base: ["ASSETCATALOG_COMPILER_APPICON_NAME": "AppIcon-Winter"])

// ...
Target(
    name: "Playground",
    platform: .iOS,
    product: .app,
    bundleId: "com.jinuman.Playground",
    infoPlist: "Playground/Supporting Files/Playground-Info.plist",
    sources: ["Playground/Sources/**"],
    resources: ["Playground/Resources/**"],
    dependencies: [
        .cocoapods(path: ".")
    ],
    settings: targetSettings
)
```

### 2) Change the `DefaultSettings` to opt out of some defaults

If you'd like to continue relying on your xcconfig file for this build settings instead of specifying in the manifest file, you can change the [`DefaultSettings`](https://tuist.io/docs/usage/project-description/#defaultsettings) behaviour of Tuist.

By default, Tuist will add `.recommended`  settings for the project and its targets, one of those settings is the `ASSETCATALOG_COMPILER_APPICON_NAME` at the target level. 

You can change the default for your project setting (which applies to all targets within it) or to specific target via:

```swift
let settings = Settings(defaultSettings: .recommended(excluding: ["ASSETCATALOG_COMPILER_APPICON_NAME"]))
```

Hope this helps

**Comment by jinuman** [comment]
Hi @kwridan 

Thank you very much for the great explanation!
It really helped a lot. 👍
