### ISSUE TITLE
How to do tuist init with a custom template?

### ISSUE THREAD

**Issue by sarunw** [tuist/tuist#2445]
## Context 🕵️‍♀️

I try to create a custom template to bootstrap my project. I tried `tuist init -h` and see that I can specify `-t` with the name of my template.

```
-t, --template <template>
                          The name of the template to use (you can list
                          available templates with tuist scaffold list) 
```

So, I go ahead and create my custom scaffold following this article https://tuist.io/docs/commands/scaffold/#scaffold-command

Everything seems to work, I can run `tuist scaffold my_template_name` and everything got generated. I run `tuist scaffold list` and my template shows up.

```
Name     Description     
───────  ────────────────
default  Default template
swiftui  Default template
my_template_name   Custom template 
```

## What 🌱

So, my folder has only `Tuist/Templates/my_template/my_template.swift` and I run `tuist init -t my_template` expecting everything will generate like when I did with `tuist scaffold my_template_name`, but it's not.

## Result

I got the following error.

`Can't initialize a project in the non-empty directory at path my_project_path`

## Expected
The project should generate the same way as a scaffold.

## Question
1. Does `tuist init -t` preserve for the official template only?
2. If the answer is yes, how should I bootstrap my project with a template?
3. If the answer is no, what did I do wrong?
4. I can use `scaffold` to bootstrap my project, but the flow would be to create a new project directory and copy my template to `Tuist/Templates`, but I don't think it is the way right?

**Comment by fortmarek** [comment]
Hi @sarunw!

This is actually not a bug.
It's something I have thought about but never got to actually implementing it. For `tuist init`, I don't think it really makes sense to define the template locally as you'd always need to copy it to the given location.

Instead, I think what we could do is put them in a global location - probably `~/.tuist/Custom/Templates` - we could then just extend where tuist looks for init templates. We should also enable user easily creating/editing these new templates. It could maybe be a flag for `tuist edit --custom` which would let you edit all the files in `~/.tuist/Custom` (in the future we could add more global custom features in there)

The only way to do it right now - which is a *hacky* way - is to copy your template to `~/.tuist/Versions/x.y.z/Templates`.

Let me know if you are interested in implementing this, I could help you with creating RFC and with the introduction to the project.

Otherwise, I'd be up for implementing this, too, but I am not sure when I can get to it.

**Comment by sarunw** [comment]
Hi @fortmarek, I'm happy to try implementing this. Where should I start? And what is RFC?

**Comment by luispadron** [comment]
Looking at this I think we could break it into two separate problems:

- Adding support for `tuist init -t` to support paths of some sort, or at least take into account the local directory. This would be additive change and something that I actually would expect to work as the author described. 
- Adding support for shared templates. This is something we can use plugins, this is something I plan on working on very soon now that the plugin system is ready!

@sarunw I recommend you take up #1 if you're interested as it probably doesn't involve a ton of changes! We ask that you create an RFC (request for comments) so that we can discuss the implementation and other users can give some feedback before any work is started. For example, here is an RFC we have open right now: https://github.com/tuist/tuist/issues/2094

**Comment by fortmarek** [comment]
Right, plugins would be a great candidate for this!

That is definitely better than `~/.tuist/Custom/Templates`, so I would not go down that path.

But, as you mentioned, it is reasonable to add support for a custom path of the template, something like `--templates-path` could be useful to others, too.

**Comment by sarunw** [comment]
Let me play around with Plugin a bit, then I will create RFC based on #1. I want to make sure this won't duplicate what the Plugin feature provided.

**Comment by sarunw** [comment]
Here is the [RFC](https://github.com/tuist/tuist/issues/2456).

**Comment by sarunw** [comment]
I end up moving `Tuist/Templates` one step up in the hierarchy and it works the way I want. I write a detailed post here https://sarunw.com/posts/tuist-init/ for those who struggle with the same issue.
