### ISSUE TITLE
Presence of $(SRCROOT)  in INFOPLIST_FILE breaks agvtool usages

### ISSUE THREAD

**Issue by SergeyKovalenko** [tuist/tuist#2645]
**Describe the bug**
Looks like starting from 1.35.0  the logic for generation INFOPLIST_FILE path has been changed and now includes $(SRCROOT).  When I run `agvtool` to update build numbers I got:

```
agvtool new-version -all 98
▸ Also setting CFBundleVersion key (assuming it exists)
▸ Updating CFBundleVersion in Info.plist(s)...
▸ $(SRCROOT)/App-Info.plist
▸ Cannot find "$(SRCROOT)/App-Info.plist"
Cannot set build number with plist path containing $(SRCROOT)
Please remove $(SRCROOT) in your Xcode target build settings
```
`InfoPlist.file(path: "App-Info.plist")` 
For tuist version  1.34.0 results in: INFOPLIST_FILE = App-Info.plist 
For tuist version  =>1.35.0 results in: INFOPLIST_FILE = $(SRCROOT)/App-Info.plist

Is it intentional change?

**Comment by fortmarek** [comment]
Hi @SergeyKovalenko!

Yes, this was intentional change and I am aware of this issue but have not been able to get to this (@thedavidharris has already reported this on Slack).

This is more of a bug in `agvtool` but since it seems there are a lot of teams using it, we could drop `$(SRCROOT)` prefix when `SRCROOT` has the same path as the Xcode project.

It should be a small change, I'll try to fix this soon.

**Comment by SergeyKovalenko** [comment]
Hi @fortmarek!
Thank you!

**Comment by armandRobled** [comment]
CBJCHBCAABAA3Z_gLXyKW7dn-AcChyZroqVBMDVIMWp5
