### ISSUE TITLE
Add support for Xcode Build Rules

### ISSUE THREAD

**Issue by Gruppio** [tuist/tuist#2702]
## Context 🕵️‍♀️
It would be nice having the support for the Xcode build rules.
These are useful for project that use metal shaders for example.
Do you think that this feature is easy to implement ?

**Comment by fortmarek** [comment]
Hi @Gruppio!

There is support for this in XcodeProj [here](https://github.com/tuist/XcodeProj/blob/ad2d6cbdfade93e3dd95813786c6b78910ab8339/Sources/XcodeProj/Objects/BuildPhase/PBXBuildRule.swift), so that makes it a little bit easier.

Implementing this would consist of:
- Proposing API to be used in `ProjectDescription` - most of it will more-or-less copy `PBXBuildRule` from `XcodeProj` but we should try to make optimizations and convenience types where possible.
- Creating a new `BuildRule` type (with properties from the proposal), adding this to `Project`
- Actually generating the build rules
- Adding the build rules to copy files build phase (as per the example changes in `.pbxproj` below 👇)

This is an example diff after I added an empty metal shader build rule:
<img width="1328" alt="image" src="https://user-images.githubusercontent.com/9371695/113348922-89d73980-9337-11eb-8f8a-ee56aa8b1494.png">

If you would like to go ahead and implement this, I'd gladly give you some pointers.

**Comment by klememi** [comment]
any update on this, please?

**Comment by fortmarek** [comment]
We haven't had time to work on this feature, unfortunately. Would you like to give it a try @klememi? We can give you some pointers and introduce you to the project 🙂

**Comment by klememi** [comment]
Actually why not :) I can give it a try at least.

**Comment by fortmarek** [comment]
Thanks @klememi 👌  feel free to ping me in Slack if you run into any issues.

**Comment by zenangst** [comment]
Any movement on this issue? 🤔

**Comment by danyf90** [comment]
> Any movement on this issue? 🤔 

Hello 👋 would you like to try moving this forward? 🚀
