### ISSUE TITLE
Auto-generated schemes now broken

### ISSUE THREAD

**Issue by jakeatoms** [tuist/tuist#2796]
**Describe the bug**
The auto-generated scheme heuristic change in #2641 breaks existing projects, but is only a minor update (1.37 -> 1.38). We suffix our test targets with `*UnitTests` and this worked prior to 1.38. It no longer works and all our schemes are broken. We use `UnitTests` because we also have `SnapshotTests` targets. It'd be nice if this was a configurable option rather than hardcoding just a few suffixes.

It also highlights the need to adhere more strictly to the semantic versioning pattern, IMO. A change like this that will break existing projects should ideally be a major version change.

**To Reproduce**
Define a project that adds a unit test target with the `UnitTests` suffix and generate.

**Expected behavior**
The `UnitTests` target should be included in the framework target's test action.

**Comment by kwridan** [comment]
Hi @jakeatoms - apologies for the hassle caused by this change 😞

>  It'd be nice if this was a configurable option rather than hardcoding just a few suffixes.

Agreed, worth noting any custom defined schemes should have not been impacted by this change - it was only for the defaults. For example for any of our CI jobs we rely on custom defined workspace schemes to ensure they remain stable between Tuist versions to protect against any default changes like this. 

> It also highlights the need to adhere more strictly to the semantic versioning pattern, IMO. A change like this that will break existing projects should ideally be a major version change.

It's a tricky one, Tuist currently follows semantic versioning for the `ProjectDescription` definitions to ensure source compatibility in manifests between minor versions. It doesn't strictly follow it for the generated projects or its defaults at the moment but is a valid concern.
