### ISSUE TITLE
2.0 deprecations

### ISSUE THREAD

**Issue by pepibumur** [tuist/tuist#2981]
## What 🌱
Since we are doing a major release, it's a good opportunity to remove some features that have been deprecated for a while.

- [ ] Global configuration through `Config.swift`. To share a value across project helpers should be used instead.
- [ ] Settings and Configuration have many initializers. We probably don't need that many.
- [ ] `environment` and `launchArguments` in targets in favor of custom schemes.

**Comment by kwridan** [comment]
Possible tidy up / consolidations for the manifest types that aren't strictly deprecations we could consider:

- Removing `testPlans(_ testPlans: Path...)` in favour of `testPlans(testPlans: [Path])` 
- Making `TestAction` public initialiser internal in favour of static methods _(`.testPlan(...)` and a new `.targets(...)` for consistency)_
- Flattening `Configuration` & `CustomConfiguration` into a single type `Configuration` 
- Removing `PresetBuildConfigurations` in favour of `configurationName` 
    - Possible enhancement would be to unify `PresetBuildConfigurations` and `configurationName` under a dedicated type `ConfigurationName` which has a string raw value. That way `.debug` and `.release` can be provided as default types _(replacing what `PresetBuildConfigurations` does today)_ and allows developers to define their own strongly typed custom configuration names in project description helpers

e.g.

```swift
struct ConfigurationName {
    var rawValue: String
}

// Defaults provided by Tuist

extension ConfigurationName {
    static var debug: ConfigurationName {
        ConfigurationName(rawValue: "Debug")
    }
    static var release: ConfigurationName {
        ConfigurationName(rawValue: "Release")
    }
}

// Custom types defined by developers in their project manifests / helpers

extension ConfigurationName {
    static var myBetaConfig: ConfigurationName {
        ConfigurationName(rawValue: "MyBetaConfig")
    }
}

// Usage

AnalyzeAction(configurationName: .myBetaConfig)
```

**Comment by laxmorek** [comment]
### My candidates to remove/deprecate:

I list my candidates to remove/deprecate below. Some of them I mentioned during our last meetup. 

#### 1. `Carthage` support in the `Setup.swift` manifest file.

Today we allow to define the `Carthage` dependencies installation setup in the `Setup.swift` manifest file:

```swift
let setup = Setup(
    actions: [
        .carthage(platforms: [.iOS], useXCFrameworks: true, noUseBinaries: true)
    ]
)
```

Alternatively we are developing a new approach for handling 3rd party dependencies. For today the `Dependencies.swift` supports enough the `Carthage` to meet the needs of users who use the `Carthage` step in the `Setup.swift`.

The users will have to update theirs `Carthage` dependencies in `Project.swift` manifest files with new paths. 

```swift
let project = Project(
    name: "App",
    organizationName: "tuist.io",
    targets: [
        Target(
            name: "App",
            platform: .iOS,
            product: .app,
            bundleId: "io.tuist.app",
            deploymentTarget: .iOS(targetVersion: "13.0", devices: .iphone),
            infoPlist: .default,
            sources: ["Targets/App/Sources/**"],
            dependencies: [
                .xcFramework("Tuist/Dependencies/Carthage/Alamofire.xcframework"), // `Tuist/Dependencies/` prefix has been added
            ]
        ),
    ]
)
```

I think it is a good opportunity to start learning users that the `Dependences.swift` is our target solution of handling 3rd party dependencies. 

#### 2. `.framework` support for `Carthage` installations using the `Dependencies.swift`.

By default `Carthage` builds dependencies as `.framework`. In the version `0.37.0` they introduced possibly to build dependencies as `. xcframework` by passing `--use-xcframeworks` flag to `Carthage` run.

We added support for that in the `Dependencies.swift` and the `Setup.swift` in this [PR #2532](https://github.com/tuist/tuist/pull/2532).

```swift
let dependencies = Dependencies(
    carthage: .carthage(
        [
            .github(path: "Alamofire/Alamofire", requirement: .exact("5.0.4"))
        ],
        options: [
            .useXCFrameworks,
            .noUseBinaries,
        ]
    ),
    swiftPackageManager: .swiftPackageManager(
        [
            .package(url: "https://github.com/SnapKit/SnapKit.git", .upToNextMajor(from: "5.0.1"))
        ]
    ),
    platforms: [.iOS]
)
```

I think we could drop support for `Carthage` in versions lower than `0.37.0` and build `Carthage` dependencies always as a `.xcframework`. I will simplify the work on building dependences graph a lot since we don't have to handle platform specific a `.framework`.  We'd remove `options` from the `Dependencies.swift` as well.

#### 3. `CocoaPods` from `TargetDependency`.

The most tricky candidate because we don't have any alternatives when we delete it. During the last meetup there was an idea of `post-hooks` actions for `tuist generate`. I think it may be a good replacement.

**Comment by fortmarek** [comment]
Use `SchemeLanguage` for language in `TestAction` and `RunAction` as mentioned [here](https://github.com/tuist/tuist/pull/3231#pullrequestreview-714998377)

**Comment by kwridan** [comment]
Some additional candidates :) 

context: https://github.com/tuist/tuist/pull/3231#pullrequestreview-714998377

**Consolidate scheme options**

- Migrate `RunAction.language` > `RunActionOptions.language`
- Create `TestActionOptions` to host `region` and `language`
- Migrate `TestAction.language` > `TestActionOptions.language`
- Migrate `TestAction.region` > `TestActionOptions.region`
- Migrate `TestAction.codeCoverageTargets` > `TestActionOptions.codeCoverageTargets`

**Comment by fortmarek** [comment]
Hey y'all!

I have created a new branch [release-2.0](https://github.com/tuist/tuist/tree/release-2.0), so we can start implementing these deprecations as the 2.0 release nears.

**Comment by pepibumur** [comment]
> I have created a new branch release-2.0, so we can start implementing these deprecations as the 2.0 release nears.

With so many deprecations planned for 2.0, I think it'll become unmanageable soon. What do you think if we do a code-freeze to focus on removing the deprecations instead?

**Comment by wattson12** [comment]
In [this](https://github.com/tuist/tuist/pull/3337) PR I made a change to the environment value fetching which preserved current behaviour by checking 2 keys (`TUIST_XYZ` and `XYZ`). It could be a good candidate for a breaking change to make it clearer if you are checking a prefixed or "global" key (comment from @pepibumur with some more context [here](https://github.com/tuist/tuist/pull/3337#pullrequestreview-736336762))

**Comment by danyf90** [comment]
In 2.0 we should also remove deprecated `xcFramework` helpers, which are basically an alias for `xcframework`

**Comment by danyf90** [comment]
And given it will probably result in a breaking change, would be nice to address this issue: https://github.com/tuist/tuist/issues/3173

**Comment by laxmorek** [comment]
Ive found one more thing [here](https://github.com/tuist/tuist/blob/e403a179e30f36e1b6cef55fabf759cd9e90c167/Sources/TuistLoader/Models/Manifest.swift#L16). Could we remove it in 2.0? 

@kwridan @pepibumur  🤔

**Comment by fortmarek** [comment]
> Ive found one more thing here. Could we remove it in 2.0?

Yes, I'd definitely remove this, good catch, @laxmorek!

**Comment by luispadron** [comment]
Id like to get the changed defined in https://github.com/tuist/tuist/discussions/2775 in to 2.0. Need to setup some time to do this but believe it would make editing the project easier. Would also be neat to consider auto-generating a target with every project for editing the project manifest, for some users the `tuist edit` command might be difficult to find about.

**Comment by danyf90** [comment]
https://github.com/tuist/tuist/issues/3402

**Comment by fortmarek** [comment]
2.0 has been already released 🙂
