### ISSUE TITLE
Don't set code signing defaults when style is manual

### ISSUE THREAD

**Issue by dtorres** [tuist/tuist#3058]
**Describe the bug**

Tuistio writes code signing settings by default, shadowing any xcconfig settings, regardless of code signing style

**To Reproduce**

- Create project with signing configs in a xcconfig
- Set the code signing style to manual
- Generate project

**Expected behavior**

I expect tuist to not shadow/replace values set in xcconfigs. There should be a setting to opt-out of defaults so the xcconfig can take precedence 

**Screenshots**

**Desktop (please complete the following information):**

- OS: [e.g. macOS]

**Additional context**

**Comment by fortmarek** [comment]
Hi @dtorres!

This is true and has already been raised [here](https://github.com/tuist/tuist/issues/954#issue-558264862).

The issue with `CODE_SIGN_IDENTITY` is that it is part of `essentialSettings` because it needs to be a part of the final `.pbxproj` that gets generated. We could probably read the xcconfig to mitigate this issue.

For now, I suggest that you either use settings as `.none` or define this property in `Project.swift`.

I'll close this as it's a duplicate and we can continue the discussion in the aforementioned issue.

**Comment by dtorres** [comment]
Thanks @fortmarek for the explanation :D I’ll go with .none
