### ISSUE TITLE
📦 [Dependencies.swift][SPM] Fix `Nimble` import

### ISSUE THREAD

**Issue by danyf90** [tuist/tuist#3171]
When a target links [Nimble](https://github.com/Quick/Nimble), we are getting an error because some headers are not found.
`Tuist` searches for headers in the default folder for a target named Nimble (i.e. `Sources/Nimble`) because in the Package.swift there isn't any indication to search them anywhere else. However, the headers are in `Sources/NimbleObjectiveC` and hence Tuist doesn't detect them, while SPM loads them correctly

```
/tmp/nimbletest/Tuist/Dependencies/SwiftPackageManager/checkouts/Nimble/Sources/Nimble/Nimble.h:2:9: 'Nimble/NMBExceptionCapture.h' file not found
```

The issue can be reproduced using the following project:
[nimbletest.zip](https://github.com/tuist/tuist/files/6784163/nimbletest.zip)

**Comment by thedavidharris** [comment]
I'm actually really confused how Nimble is even building. Shouldn't NimbleObjectiveC effectively be it's own target? How is it not explicitly declared? 

There's not even an include/ folder for public framewroks, everything seems weird.

**Comment by mgray88** [comment]
This was never actually "fixed" right? Because it wasn't actually "broken," since Nimble defines different files for SPM targets vs cocoapods targets? I'm facing an issue where I'd like to bring Nimble in with Dependencies.swift, but I still need access to its Objective C code and headers. Is that possible?

**Comment by fortmarek** [comment]
> Is that possible?

Is this possible if you integrate Nimble via Xcode (aka if you have not used tuist)?

**Comment by mgray88** [comment]
It works through Cocoapods, since the included files are different, as well as the fact that some of the swift files have compiler conditionals on `SWIFT_PACKAGE`. I can probably change the conditionals using the `targetSettings` but there are files that aren't included in the generated project. I haven't tried it using Xcode, mainly because I assumed it would have the same behavior looking at the Package.swift and Nimble.podspec files

**Comment by fortmarek** [comment]
We are trying to be close to the Xcode's SPM integration, so I would consider this to be a bug only if we deviate from what Xcode is doing.

**Comment by mgray88** [comment]
That's what I figured, it didn't work with Xcode SPM. Unfortunately it didn't work with Dependencies.swift Carthage integration either
