### ISSUE TITLE
Dependencies.swift - Disable --no-use-binaries option to Carthage

### ISSUE THREAD

**Issue by AlexanderNaumov** [tuist/tuist#3195]
**Describe the bug**
Why can't --no-use-binaries and other flags for carthage be changed?

**Comment by fortmarek** [comment]
Hi @AlexanderNaumov!

This is because right now `Dependencies.swift` only supports xcframeworks and some binaries are not compatible with that at the moment (this will have to be resolved on Carthage side).

Please, also note that `Dependencies.swift` is still WIP, so you might want to define Carthage dependencies via `Cartfile` instead for the time being (although we will start recommending `Dependencies.swift` very soon!)

**Comment by eelcokoelewijn** [comment]
Hi @fortmarek,

I'm wondering if the above statement is still true or if it would be possible to start supporting setting different flags for Carthage when using `Dependencies.swift`.
At the moment our project is using the Adyen framework, which has some of it's dependencies only available as xcframeworks, for example: [adyen-wechatpay-ios](https://github.com/Adyen/adyen-wechatpay-ios). Running Carthage with `--no-use-binaries` results in an error, therefore doesn't build the framework, causing missing framework errors down the line... it outputs:

```
*** Skipped building adyen-wechatpay-ios due to the error:
Dependency "adyen-wechatpay-ios" has no shared framework schemes for any of the platforms: iOS
```

Would be great to hear what Tuist's ideas are in this regards.
