### ISSUE TITLE
FR: Make workspace using Project entity

### ISSUE THREAD

**Issue by jesus-mg-ios** [tuist/tuist#3232]
## Context 🕵️‍♀️

I want to make a custom workspace from Project variable inside the manifest. Making from strings and filling all is a little weird.

## What 🌱

I want to create a custom workspace from an array of Projects instances, moreover, I don't want to create a Workspace from scratch, there is a default Workspace generated automatically, so maybe I should to modify it. 

## Proposal 🎉

Make something like this:

```
init(from projects: Project ..., ...) {
 .... 

}
```

the use 

```
let project1 = Project(...)
let project2 =  Project(...)
let workspace = Workspace(from: project1, project2)
```

Nowadays there is a default workspace, maybe we can include something like this to mutate

```
var workspace = Workspace.default

workspace.whateverVariable = whatever
```

**Comment by fortmarek** [comment]
Hi @jesus-qt!

The issue with `init(from projects: Project)` is that we don't have access to projects - and we _can't_ have it AFAICT. While `var workspace = Workspace.default` should be possible in theory, I'm not sure if this is the best API. I'm thinking more along the lines of:
```swift
let workspace = Workspace(
    projects: .default,
   ....
)
```

Where `projects` would no longer be of type `[String]` but `enum Projects { case default, custom([String]) }`.

If I may ask, what do you need to change in `Workspace`? Ideally, we'd like to push users not to use it at all and rather rely on `Project.swift` whenever possible.

**Comment by jesus-qt** [comment]
I need to change pre and post actions (build and test) from the scheme autogenerated. with is defined and inside of the workspace. *****-project scheme (build and test all targets)

**Comment by fortmarek** [comment]
For the `****-project` scheme, I think we can add an API to configure that directly.

However, having `Workspace(projects: .default)` might still be useful as it's IMHO rare case where one would want to deviate from the default. Thoughts @kwridan?

**Comment by kwridan** [comment]
Thanks for flagging this @jesus-qt and @fortmarek for the follow up!

The auto generated workspace is currently done at the individual project level

for example:

- App
  - Project.swift  

Calling `tuist generate` within the `App` directly will automatically create a workspace there for the project. 

Note that this is slightly different from the scenario where a Workspace manifest is used, typically in a multi-project setup.

for example:

- Root
  - Workspace.swift
  - App
    - Project.swift  
  - Modules
    - ModuleA
      - Project.swift
    - ModuleB
      - Project.swift
    - ...
  - Documenation
    - Guide.md  
 
Where `Workspace.swift` references paths to the one or more of those project manifests _(some of which may not be dependent, e.g. sample / demo app projects)_. Calling `tuist generate` at the `Root` directory would generate a workspace there referencing the appropriate projects. In this scenario, `tuist` doesn't have knowledge of where the projects live unless referenced. 

A `.default` could be implemented today via [ProjectDescriptionHelpers](https://docs.tuist.io/guides/helpers) if needed as it's akin to 

```swift
import ProjectDescription

let workspace = Workspace(
   name: "MyWorkspace"
   projects: "**" // `projects` supports glob patterns
)
```

```swift
// ProjectDescriptionHelpers
import ProjectDescription

func makeDefaultWorkspace(name: String) -> Workspace {
  Workspace(
     name: name
     projects: "**",
     // ... other params
  )
}
```

Or alternatively an extension of `[Path]`:

```swift
// ProjectDescriptionHelpers
import ProjectDescription

extension Array where Element == Path {
   static var allPaths: [Path] {
      return ["**"]
   }
}
```

> Making from strings and filling all is a little weird.

Note the types used here are `Path` which has a more features / use cases - see https://docs.tuist.io/manifests/project#path

> While var workspace = Workspace.default should be possible in theory

Sadly this a little tricky to achieve today due to small implementation detail, currently need all information at initialization time - as the manifest `dumpIfNeeded` occurs in the init of the top level structures 🤐

>  Ideally, we'd like to push users not to use it at all and rather rely on Project.swift whenever possible.

Workspace.swift has it's place in the ecosystem 🙂 I wouldn't necessarily discourage its usage. There are certain items that are only applicable at the workspace level rather than the project level _(multi project schemes, workspace level additional files for example)_.

> For the ****-project scheme, I think we can add an API to configure that directly.

It depends on the nature of the customisation, a challenge is workspace wide customisations can't take place in an individual project manifest as there could be several project manifests.

> However, having Workspace(projects: .default) might still be useful as it's IMHO

Possibly, internally it would be converted to `**`. That said, given it's equally as easy to define a glob pattern without referencing each project, would there be a big need to have another mechanism to achieve this as part of the public API?

**Comment by danyf90** [comment]
I don't think that specifying the path of the projects is so weird:
- if you need to specify them, you must know where they are
- if you don't need it, you can use the `**` approach suggested by Kas

Closing the issue, feel free to reopen if you have any follow up question
