### ISSUE TITLE
Commit generated project for fixtures

### ISSUE THREAD

**Issue by adellibovi** [tuist/tuist#3308]
This is more a suggestion/open question.

Do we have a specific reason for not committing generated xcodeproj for our fixtures?

I personally find it useful to see the git diff for the fixture as it may help to detect unexpected changes in xcodeproj file or easily check if a new change generates the expected diff. 

cc @kwridan , @pepibumur

**Comment by kwridan** [comment]
Something like this would be quite handy as it will also help with: 

- Ensuring project generation stability
- Avoiding the introduction of absolute paths

A few challenges I can think of with this 😞

- Fixtures would need to be re-generated on every PR
- Additional CI checks would need to be introduced to enforce / check this
- Some fixtures may take more time to generate than others (e.g. any of the ones with external dependencies)

**Comment by pepibumur** [comment]
Although there's value in committing them, the value doesn't outweigh the costs significantly and therefore I don't think it's worth it because the experience of contributing to the project will suffer. We have already some inconveniences caused by the formatting and lining tools, so this would add up to that. 

I like the motivation behind the idea, but I don't think the execution is the right one. The only thing I can think of is to have a single and complete project that we can commit to the repository. I'd only do it with that repository and not with all the fixtures.

**Comment by adellibovi** [comment]
Fair enough, I will close this and give a thought about what we could do to improve the "detection problem"
