### ISSUE TITLE
[Cache] Avoid building unnecessary binaries during `tuist cache warm`

### ISSUE THREAD

**Issue by danyf90** [tuist/tuist#3309]
With the current commands set, if we want to focus on a few targets (let's say `TargetX`, `TargetY`, `TargetZ`) we need to run:
- `tuist cache warm TargetX TargetY TargetZ` to build the cache
- `tuist focus TargetX TargetY TargetZ` to create the focused project

The first command will also build binaries for `TargetX TargetY TargetZ`, which are not really needed in our scenario.

To avoid that we could either:
- add a parameter to `tuist cache warm`, so that `tuist cache warm TargetX TargetY TargetZ --dependencies-only` does NOT build `TargetX TargetY TargetZ`
or
- add a parameter to `tuist focus`, so that `tuist focus TargetX TargetY TargetZ --warm-cache` also generates binaries for `TargetX TargetY TargetZ`

**Comment by danyf90** [comment]
Proposed alternatives:
- define a different `tuist cache` subcommand: `tuist cache warm-for-focus TargetX TargetY TargetZ`
- use `--for-focus` instead of `--dependencies-only` for the new `tuist cache warm` parameter

**Comment by pepibumur** [comment]
Just to make sure I understood the **use-case** here:

> As a user, I want to cache as binaries the dependencies of the targets I want to focus on.

If that's the use-case, I think it's a valid one that we can support. Here are my **thoughts**:

- I'd not extend `tuist focus` to include warming as part of the focus. Having two commands is more explicit and easier to compose.
- I'd not include `focus` in the name of the flag to keep both commands as independent as possible. Therefore I'd rule out the idea of using `--for-focus`.
- A new command is not necessary because what we are doing, in the end, is the same as `tuist warm`. 
- I like the idea of using a flag to filter out the "focused" targets. I think `--dependencies-only` is a good name for the flag because it describes very well the type of filtering we are doing.

That being said, I'm on board with the idea of using `--dependencies-only`. I'd curious to see what other users/contributors think about this. Thoughts @fortmarek / @kwridan / @adellibovi

**Comment by adellibovi** [comment]
I am on board as well, as far it is clear how `--dependencies-only` works with multiple targets:
Example: `tuist cache warm A B C` having B as a dependency of A.
Should we cache B because of being a dependency of A? Or should we not because we want only the dependencies of B?
As per the parameter's name, I would say we should, if we look from the PoV of the use case instead, maybe we should not.
I may prefer to go for including that dependency if we stick with this name (it feels more coherent with how it is described).

**Comment by fortmarek** [comment]
If I run `tuist cache warm A B C --dependencies-only`, I'd expect to be able to run `tuist focus {A,B,C}` and have all their dependencies cached. Therefore, I think in the scenario @adellibovi outlined, we should cache B as well. In other words, `tuist cache warm A B C` should IMHO result in the same as if you ran `tuist cache warm A && tuist cache warm B && tuist cache warm C`.

As far as the `--dependencies-only` flag goes, I'm definitely onboard 👍

**Comment by danyf90** [comment]
Makes sense, and you 100% convinced me that `tuist cache warm A B C --dependencies-only` should build `B` as well 🙌

**Comment by danyf90** [comment]
Makes sense, and I agree with your point about warming `B` as well, but it might defeat the improvement for scenario I have in mind 🙌

In our scenario we have a project which depends on other projects (either tuist or SPM projects). What we would like to do is to focus only on our project and its tests, so we would do:
```
tuist cache warm MyProject MyProjectTests --dependencies-only
```

where of course MyProjectTests depends on MyProject.

In this case, if we warm the cache also for MyProject (as it is a dependency of one of the specified targets), we would defeat the purpose of this change, which is to NOT build MyProject

**Comment by fortmarek** [comment]
Yeah, that's tricky. One thing we could do is add a flag `--excluding`, so you could do `tuist cache warm MyProjectTests --excluding MyProject`. Optionally, we could skip creating `--dependencies-only` as you could do `tuist cache warm MyProject --excluding MyProject`, however, it does not read well, so for readable purposes, it still might make sense.

I don't like that `--excluding` will further complicate the command, however, I can't think of a better way.

**Comment by danyf90** [comment]
I think `--dependency-only` is clearer in all scenario apart from the one defined by Alfredo.
Maybe we can live with it and try to explain it well in the argument and command documentation.

Or we should find another name (like `--excluding-defined-targets`) which might be much less clear in the common case :D
