### ISSUE TITLE
[RFC] Split `tuist clean` 

### ISSUE THREAD

**Issue by danyf90** [tuist/tuist#3402]
When something goes wrong in project generation, I sometimes try to run `tuist clean` to be sure it's not due to some wrong cached manifests or something similar. This has the undesired side effect of also clearing the build artifacts cache.

Given they are 2 very distinct concept, what do you think if we:
- change `tuist clean` logic to not clear build artifacts
- add a `tuist cache clean` command to only clear build artifacts

Given we are approaching a 2.0 release, this might be a good moment to change this

**Comment by luispadron** [comment]
Splitting this up into more obvious ones makes sense to me! Maybe we do `tuist clean all` instead? This way `tuist clean` has three options:

- `tuist clean manifests` (or something else) 
- `tuist clean builds`
- `tuist clean all`
- `tuist clean` --> defaults to `tuist clean manifests`

But maybe this is too verbose? If so: I'd say `tuist clean cache` vs. `tuist cache clean` so that the `clean` command can be grouped together.

**Comment by pepibumur** [comment]
I'm more inclined towards @luispadron's proposal where we keep the verb in the first position and use a new argument to specify what to cache. I'd make `tuist clean` clean all, and then use the argument to make it more specific.

**Comment by fortmarek** [comment]
> I'd make tuist clean clean all, and then use the argument to make it more specific.

I am also inclined to this. But otherwise, @luispadron proposal seems reasonable, so +1 from me!

**Comment by danyf90** [comment]
Implemented [here](https://github.com/tuist/tuist/pull/3407) and it's not even breaking 🙌
