### ISSUE TITLE
⏱ [Manifest Cache] Manifests are never cached when using remote caching 

### ISSUE THREAD

**Issue by bolismauro** [tuist/tuist#3467]
**Describe the bug**
When computing the hash of the manifests, Tuist uses the environment variables prefixed with `TUIST_`. You can see the logic [here](https://github.com/tuist/tuist/blob/main/Sources/TuistLoader/Loaders/CachedManifestLoader.swift#L204) and [here](https://github.com/tuist/tuist/blob/main/Sources/TuistLoader/ProjectDescriptionHelpers/ProjectDescriptionHelpersHasher.swift#L33).

This makes absolutely sense, as manifests can leverage these env variables to conditionally change the resulting graph.

However, some env variables are not meant to be used there, and in particular `TUIST_CLOUD_TOKEN` changes on every run. This makes so the manifests are never cached, hence increasing the time Tuist takes of several seconds.

**To Reproduce**

1. Create a project.swift
2. run `TUIST_CLOUD_TOKEN=A tuist cache warm`
3. check the time
4. run `TUIST_CLOUD_TOKEN=A tuist cache warm` once again, and observe that the time is lower
5. run `TUIST_CLOUD_TOKEN=B tuist cache warm` and observe an higher time

**Proposed solutions**

I have a couple of suggestions here:

1. let's have a set of env variables that are not considered in the hash. This has the big disadvantage that relies on the fact that no one will use these variables inside the `Project.swift`

2. differentiate env variables meant to be used in the manifests, from the one that Tuist uses (e.g., we can rename  `TUIST_CLOUD_TOKEN` to `TUIST_SOMETHING_CLOUD_TOKEN`)

3. Don't use `TUIST_CLOUD_TOKEN`, but pass the value as a parameter instead

**Comment by danyf90** [comment]
I think we are safe to go for option 1 which is just simpler as I don't see any scenario in which anyone wants to use that variable for project definition.

If we want to stay 100% on the safe side, we can add a check in `ProjectDescription.Environment` that the `TUIST_CLOUD_TOKEN` key is not read.
Another possibility is to rename the variable to a value that doesn't start with `TUIST_`, so it's not considered in the caching logic.

Also, [here](https://github.com/tuist/tuist/pull/3337) we removed the requirements for having `TUIST_` as prefix for variables. Now that I see the full picture I think we should revert that as it would break our caching logic, right @pepibumur ?

**Comment by pepibumur** [comment]
👋🏼 
I was not aware of the fact that we were hashing the variables starting with `TUIST_`. Because the plan is to make that more flexible and allow developers to read any variable, even if they don't start with `TUIST_`, I don't think the approach we follow makes sense anymore.
What I proposed doing instead if, removing that logic, and instead give developers an API where they can explicitly indicate what variables are being read from their manifests. Because environment variables are dynamically read from the manifests, there's no way for us to know that. What about something along the lines of:

```swift
let project = Project(
  cacheConfiguration: .cacheConfiguration(
    hasheableEnvVariables: ["MY_VARIABLE"]
  )
)
```

**Comment by bolismauro** [comment]
In principle it makes sense. However, from the dev point of view, what's the reason why they should have this configuration? They already have an API to read any variable they need.

In practice we're surfacing to devs an implementation detail done only for speeding-up the Tuist. Moreover, it is extremely easy to forget about adding a new variable, and having weird results when running commands.

We may crash if devs access variables not listed in the config, or we may generate swift-getters rather than accessing a dictionary. TBH none of the two really satisfies me

**Comment by danyf90** [comment]
I am not sure that "passing the responsibility" to the users is the best UX for them.

In [our documentation](https://docs.tuist.io/guides/environment) we already explain that `TUIST_*` variables can be used to   make generation-time configuration, so it makes sense that they are taken into account automatically when computing the manifest hash.

The problem here is that we have some internal variables, which are supposed to be used internally (not only `TUIST_CLOUD_TOKEN`, but also `TUIST_OS_LOG`, `TUIST_DETAILED_LOG` and many others).
Ideally those variables should not be accessible from the ProjectDescription (hence preventing the user to have logic on top of them in the manifest), and they should not be considered in the hash of the Project manifest.

I think that an easy and clean solution, would be that either:
- those variables don't start with `TUIST_`, but with a different prefix (e.g. `TUISTCONFIG`). (we can keep the old ones until 2.0 to don't make breaking changes)
or
- those variables are not accessible from the `Environment.something` helpers (which would filter out "known" internal variables) and are ignored by the hashing logic

Also, regarding your proposal, I'm not sure I understood how it would work implementation-wise.
The current logic to calculate the hash of the manifest is something like `hash(manifestContentHash + environmentVariables)`. if we need to read the content to calculate its hash (because it contains the info about which variables need to be considered), doesn't it defeat the purpose of the cache as we need to read and parse the file anyway?

**Comment by pepibumur** [comment]
> I am not sure that "passing the responsibility" to the users is the best UX for them.

This already happened the moment we allowed users to use environment variables that don't have the `TUIST_`, so we'd either reconsider that decision, or we need to expose an API for users to indicate what environment variables they are using. Bear in mind this is a change coming to 2.0 and the motivation was that it was inconvenient for users to prefix their variables with `TUIST_`

Sooner or later, we'll need an API for users to extend the hashing logic. Imagine you add a custom script build phase that generates a file into the final bundle. That build phase has an implicit dependency with the environment that Tuist is not aware of. That'll lead to the generation of hashes that are not accounting for all the input that influences the built artifact.

A summary of the situation is **projects can implicitly depend on the environment, and therefore we need APIs to explicitly extend the hashing logic**. We'd need to discuss what's the best API and whether it should be at the workspace, project, or target level. These are the things users would need to specify:

- Environment variables.
- Extra files.

**Comment by danyf90** [comment]
The problem is that we are talking about the hash of the project manifests used for the tuist generate caching.
Hence, we can't make it dependent on its content, otherwise we would need to read the file anyway, defeating the purpose of the cache.
Is it clearer?

Regarding the other point, I agree that if we follow my proposal we should revert the change we did about accessing variables not starting with TUIST_.
I don't think it's a big deal for the user to prefix the variables they need.

What if we follow a simple solution now (as the ones I have proposed), and discuss bigger changes for the 2.0 release?

**Comment by danyf90** [comment]
Just wanted to add that I have tried, and looks like the change we did [here](https://github.com/tuist/tuist/pull/3337) doesn't actually work, probably the env variables are filtered keeping only the ones starting with TUIST_ before reaching the piece of code changed there 🤔 

With the [attached sample project](https://github.com/tuist/tuist/files/7192075/Sample.zip), a `TUIST_SAMPLE=Sample tuist generate --open` correctly generates the target name as `Sample`, while `SAMPLE=Sample tuist generate --open` generates the target name as `CANT_READ`.

**Comment by pepibumur** [comment]
> The problem is that we are talking about the hash of the project manifests used for the tuist generate caching.
Hence, we can't make it dependent on its content, otherwise we would need to read the file anyway, defeating the purpose of the cache.
Is it clearer?

Yes! I was not seeing it before. Let's do the following:

- Revert the change that allows non-prefixed variables to be read through `Environment.xxxx`
- Expose an interface in `Config` for those users that find it inconvenient to prefix their variables with `TUIST_`
- Update the Tuist-owned variables to have `TUIST_CONFIG` as a prefix instead.

Regarding the second, the API it could be something along the lines:

```SWIFT
let config = Config(generationOptions: [
  .mapEnvVariableToTuist(["MY_VARIABLE"])
])
```
