### ISSUE TITLE
Feature Request: Add ability to derive full file path from relative paths within manifest files

### ISSUE THREAD

**Issue by hisaac** [tuist/tuist#3605]
## Enhancement Idea

Initial discussion of this topic was here in the Tuist Slack: https://tuistapp.slack.com/archives/C018QG7U7SN/p1635287939013600

Tuist itself has the ability to handle file paths relative to the directory of the `Project.swift` file when creating a `Target` and other things. For instance, when creating a `Path` object, you can specify if it is `relativeToCurrentFile`, `relativeToManifest`, or `relativeToRoot`.

If we need to do any custom file processing of our own during project generation though, we would need to be able to access the full file-path on disk of whatever file we're referencing, which would be different depending on the device the code is running on.

My current workaround is to use the `#file` reference, and lop off the end of the path:

```swift
public static let projectRoot = #file.replacingOccurrences(of: "Tuist/ProjectDescriptionHelpers/Globals.swift", with: "")
```

This works, but it would be nice if we could instead pull this from `Path` objects themselves. I'm thinking something like:

```swift
// On a given `Path` object
let relativePathObject = Path("Source/ModuleA/File.swift")

// The full file path could be accessed as a property (which could itself be a `Path` as well)
relativePathObject.fullPath

// And a static property on `Path` to the project root and/or Manifest location would also be handy
Path.projectRoot
Path.projectManifest
```

## Additional Context

My specific use-case is that, we are exploring migrating from Bazel to Tuist. Currently, there is a `BUILD.bazel` within every module directory that contains a list of that module's dependencies. While migrating, I'm just reading that file, and pulling the dependencies list from there, so that we only have to update the list in one place.

**Comment by pepibumur** [comment]
> If we need to do any custom file processing of our own during project generation though, we would need to be able to access the full file-path on disk of whatever file we're referencing, which would be different depending on the device the code is running on.

Am I right understanding that what you'd like to do is to read the value from the manifest to perform IO directly from there? We could expose that information to you, but I'm afraid people will leverage the API to do IO from manifests and this is something we discourage doing (in your case it makes sense because you are migrating from Bazel). What if we expose it but don't document it and give it a name that makes it obvious that it shouldn't be used?

**Comment by hisaac** [comment]
> We could expose that information to you, but I'm afraid people will leverage the API to do IO from manifests and this is something we discourage doing.

Can I ask why this is discouraged? I feel like there are likely other instances where this would be useful.

> What if we expose it but don't document it and give it a name that makes it obvious that it shouldn't be used?

I think if there's a good reason to discourage this type of use case, then it's probably not worth exposing it at all. There is always the `#file.replacingOccurrences(of:...)` workaround that I'm using if someone does need to do it.

**Comment by pepibumur** [comment]
> Can I ask why this is discouraged? I feel like there are likely other instances where this would be useful.

Tuist's generation pipeline is functional. We take the input described in the manifests, apply a bunch of functions, and get Xcode primitives at the end that we write to disk. Because the input is a declarative layer, we know what influences the output and then we can deterministically provide workflows. If we allow IO in a declarative layer, we are allowing the introduction of side effects, and Tuist is not aware of them. 

> I think if there's a good reason to discourage this type of use case, then it's probably not worth exposing it at all. There is always the #file.replacingOccurrences(of:...) workaround that I'm using if someone does need to do it.

In that case, I'd suggest keeping the workaround documented here in case someone else runs into the same need in the future. If this turns out to be useful for many users, we can invest in building the use-case into the API.

**Comment by hisaac** [comment]
Fair enough! Thanks for considering it and the good explanation. 👍
