### ISSUE TITLE
Impossible to compile Tuist for contributors on M1

### ISSUE THREAD

**Issue by AlbertMontserrat** [tuist/tuist#3633]
**Describe the bug**
Following those steps in this page: https://docs.tuist.io/contributors/get-started

I'm not able to compile Tuist project from Xcode. 

```
Build target Signals of project Signals with configuration Debug
/Users/albert.montserrat/Projects/tuist/Tuist/Dependencies/SwiftPackageManager/.build/checkouts/BlueSignals/Signals.xcodeproj: warning: The macOS deployment target 'MACOSX_DEPLOYMENT_TARGET' is set to 711.0, but the range of supported deployment target versions is 10.9 to 11.3.99. (in target 'Signals' from project 'Signals')
```

and much more:

![image](https://user-images.githubusercontent.com/10175651/140083800-ec685335-6a51-45b8-92a9-f0a2e0d90ad7.png)

**To Reproduce**

1. `git clone git@github.com:tuist/tuist.git `
2. `bundle install `
3. `./fourier up`
4. `./fourier generate tuist --open`
5. Build `ProjectDescription` and `ProjectAutomtation`
6. Build `tuist`

**Expected behavior**
Build succeed

**Desktop (please complete the following information):**

- OS: macOS 11.4
- Version: current master branch (v. 2.1.1)
- Xcode 13.0

**Additional context**

**Comment by ezraberch** [comment]
This is indeed not an M1-specific issue.

The cause is some code added in #3602. To find the minimum deployment target, the following is run:

`xcrun vtool -show-build /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/Library/Frameworks/XCTest.framework/XCTest`

Then, the number after "version" is extracted. On at least some systems, that number is "711", so it tries to build things for MacOS 711. Obviously, that doesn't work.

This looks to be blocking #3627.

CC @danyf90

**Comment by danyf90** [comment]
Thanks for reporting, that's definitely an issue with that logic, we'll have a look ASAP 🙌

**Comment by pepibumur** [comment]
@AlbertMontserrat / @adri4silva until we can figure out a better way to get the version, you can open the `Package.swift` directly and remember to compile `ProjectDescription` before compiling `tuist`. Sorry for the inconveniences.

**Comment by pepibumur** [comment]
[Here](https://github.com/tuist/tuist/pull/3639) is my attempt to fix it.
