### ISSUE TITLE
buildAction, targets, and runAction do not allow String variables

### ISSUE THREAD

**Issue by dimitarnestorov** [tuist/tuist#3910]
**Describe the bug**

I have `String` variables defined at the top of the configuration to make forking and renaming easy. However when I use these variables in `.buildAction(targets:)`, `.targets()`, and `.runAction(executable:)` I get the errors shown in the screenshots.

```swift
let name = "Cool Project"
let testsTargetName = "\(name) Tests"
let iosName = "\(name) (iOS)"
let macosName = "\(name) (macOS)"
```

**To Reproduce**

**Expected behavior**

No error

**Screenshots**

![image](https://user-images.githubusercontent.com/8790386/147471504-c700a666-ef41-4bd1-9766-dba621a2f242.png)
![image](https://user-images.githubusercontent.com/8790386/147471600-5990e3f0-bd03-47f5-91d2-03788b1dc8c4.png)

**Desktop (please complete the following information):**

- OS: macOS
- Version 11.4
- Xcode 13.2
- Tuist 2.4.0

**Additional context**

 If I wrap them in an interpolated string it's all good.
 
![image](https://user-images.githubusercontent.com/8790386/147471892-6d916ad6-ff04-43e8-babd-b2313cd03794.png)

**Comment by kwridan** [comment]
Hi @dimitarnestorov - thanks for raising this

The reason you are witnessing this is due to `targets` and `executable` not being of type `String` but rather of type [`TargetReference`](https://docs.tuist.io/manifests/project#target-reference) - _see https://docs.tuist.io/manifests/project#build-action_

The reason is for this is, when referencing targets, both the project and the target name is needed - this especially important when writing workspace schemes that can references targets from different projects. As a convenience however, `TargetReference` conforms to `ExpressibleByStringInterpolation` to allow specifying literal strings and interpolated strings for target names when defining schemes within a project where the project is already known. 

Without duplicating the interface for all scheme methods, I'm not sure there's a way to accept a `String` variable directly 😞

**Comment by fortmarek** [comment]
Thanks Kas for the response here - indeed, that is the reason. I'd close it as a known limitation but we can revisit this in the future.
