### ISSUE TITLE
Add support for nested project generation alongside flat workspaces

### ISSUE THREAD

**Issue by pavel-trafimuk** [tuist/tuist#3962]
**Describe the bug**
When `frameworkB.targetB` depends on `frameworkA.targetA`, 
it doesn't have explicit target dependency in project settings

**To Reproduce**

1. Create app with two embedded frameworks: `frameworkA`, `frameworkB` (by tuist of cause)
2. Make `frameworkB.targetB` depends on `frameworkA`
3. Regenerate all xcodeproj by `tuist`
4. Open `frameworkB proj file -> Build Phases -> Target Dependency`
5. It will be empty

**Expected behavior**
If I declared that framework depends on other frameworks, they should be explicitly declared in "`target dependency`" section

**Screenshots**
<img width="1093" alt="Zrzut ekranu 2022-01-5 o 17 56 37" src="https://user-images.githubusercontent.com/5096762/148551629-84e9cb3a-cba5-43e5-adc1-0e4ff5691cec.png">

**Sample Project**
https://github.com/pavel-trafimuk/tuist-target-dependency

**Additional context**
1) Tuist enables "**Find Implicit Dependencies**" in schemes to build all dependencies (its a reason why frameworks could be compiled). 
But it's not optimized way (Apple recommends disable it), also it doesn't work if I open framework xcodeproj, instead of workspace

2) To make it possible - adds all dependencies to needed section, first of all we should add depended `xcodeproj`s to our framework `xcodeproj`

**Comment by pavel-trafimuk** [comment]
I want to start this feature by expanding 
`enum TargetDependency {
    case project(target: String, path: Path, **asExplicitDependency: Bool = false**)
}`

**Comment by kwridan** [comment]
Thanks for raising this @pavel-trafimuk 

I don't believe Xcode supports this the way you expect (unless I misunderstood the request). Within the Target Dependencies build phase, Xcode can only reference targets within the same project, It can't reference those in other projects. You'll notice even attempting to manually do this in the Xcode UI may not be possible.

Tuist is correctly handling this already _(no changes needed)_:

- For dependencies within targets in the same project, it adds it to the `Dependencies` build phase + adds it to the linked libraries
- Fro dependencies within other projects, it only links those targets (if applicable - e.g. dynamic frameworks, test targets) or adds a custom `Dependencies` build phase to ensure Xcode builds those tendency targets

It's worth articulating the issue / motivation behind this? e.g. did a particular project setup result in a failing build?

Thanks

**Comment by kwridan** [comment]
Ah I missed the context part

> Tuist enables "Find Implicit Dependencies" in schemes to build all dependencies (its a reason why frameworks could be compiled).
> But it's not optimized way (Apple recommends disable it), also it doesn't work if I open framework xcodeproj, instead of workspace

When dealing with multi-project workspaces you do need to open the workspace to get a successful build, the alternative to this is nested projects which Tuist doesn't support. 

> To make it possible - adds all dependencies to needed section, first of all we should add depended xcodeprojs to our framework xcodeproj

Not sure I follow this part.

**Comment by pavel-trafimuk** [comment]
@kwridan Xcode supports it, we use this way on our project (150+ modules). What we do - we link project files where our target dependences to current framework `xcodeproj`, after that I can do add to dependencies all needed targets. And they will be explicit. Already discussed with @fortmarek about it

**Comment by fortmarek** [comment]
> Not sure I follow this part. Typically you'll need to explicitly declare all the direct dependencies of your target, the generation logic will ensure to include transitive dependencies where appropriate (e.g. in a Test target, or an App target).

The dependencies are declared in the `Project.swift` manifest but if the dependency are across `xcodeproj`, they will not be added to the `Dependencies` list - in other words, they will not be explicit. It is a bummer that you have to link the `xcodeproj` to get access to the dependencies.

**Comment by kwridan** [comment]
Thanks @fortmarek & @pavel-trafimuk !

If I followed along, you're trying to leverage nested projects instead of a Workspace of projects?

For example to achieve the following graph _(where each target lives within an independent project)_:

![graph](https://user-images.githubusercontent.com/11914919/148660231-63c6b75e-2178-4c74-a500-6c51a80f0291.png)

The following structure is needed:

<img width="255" alt="dependencies" src="https://user-images.githubusercontent.com/11914919/148660481-1b7db70d-2607-4a3c-baea-022f158e74e4.png">

Only then would Xcode allow you to explicitly select the targets as dependencies:

<img width="415" alt="workspace" src="https://user-images.githubusercontent.com/11914919/148660274-f194305c-7138-482b-85fc-dac7ee647bc9.png">

This is a valid alternate mechanism to achieve cross project dependencies. That said it has its own downsides and doesn't scale very well sadly. For each cross project dependency the project needs to be nested - as such the same project can appear in several locations. This can grow wildly out of control very fast in larger codebases where there's a lot of cross project dependencies. In the simple example above the `Framework2` project appears 4 times! 

<img width="255" alt="annotated" src="https://user-images.githubusercontent.com/11914919/148660541-0ef3e358-f516-4e48-b7d1-2cb904a817a4.png"> 

I'd suggest one two approaches:

- If you'd rather have explicit target dependencies, then generate a single project with all your targets in it
- If we feel strongly about supporting nested projects - we need to think through it a bit more methodically, it's a little more than a simple dependency flag. It would be an alternate generation model (e.g. generate a flat workspaces vs nested projects)

It would be helpful to understand what issues / limitation the current setup has before making changes which may have other knock-on effects.

_Note: This is based on my past experience, we used to use nested projects many years ago but we ended up migrating to a flat workspace due the issues it had. Of course I may have missed something - so please fill in any blanks I have 😅._

**Comment by pavel-trafimuk** [comment]
> _Note: This is based on my past experience, we used to use nested projects many years ago but we ended up migrating to a flat workspace due the issues it had. Of course I may have missed something - so please fill in any blanks I have 😅._

As I said before, we use "nested projects" model in our project (with 150+ frameworks, where 1 framework = 1 xcodeproj)). I don't want to say that it's the best solution, but I believe it has better compiler performance by, again, explicit dependencies. As tuist-influencer in our company, I can't even imagine how I can promote migration from `nested` to the `workspace` model. Maybe with trying to move all modules on the workspace and check compilation times (from-zero and incrementals).

Also for now I can't migrate on tuist in project-nested model, because main(final) app depends on `xcodeproj` files, which couldn't not be compiled well because could not find needed dependences (workspaces ignored by main app). 
As temporary solution, I prepared extension for `Target` with flow: "if a target dependency is local-our framework, we also add `xcodeproj` via additional files". Hope other team will detect "find implicit dependences" when almost will be migrated (and they will not fire me)

**Comment by pavel-trafimuk** [comment]
@kwridan if you can write short intro, which classes should be changed and how, I can try to start with draft WIP

**Comment by kwridan** [comment]
Thanks for the interest in progressing this @pavel-trafimuk 

I'm still not a 100% sure it's a good fit for Tuist to support this as things stand - as it will most likely will be a big effort 😞 

To support nested projects, we would need to change the core generation logic or possibly have another generator implementation! To my knowledge, to support nested projects we need the concrete `pbxproj` references of all projects, if that is case we have the following challenges:

- Today we generate all projects in parallel as they don't share any state between each other (this allows us to speed up the generation process)
  - This means we would need to either topologically sort projects according to their target dependencies and sequentially generate them in reverse order to allow projects to to obtain concrete references to their dependency projects
  - Alternatively have 2 generations passes - 1 parallel generation to generate everything except dependencies and another sequential one to perform the nesting / linking of dependencies
- The current generation paradigm (flat workspace + implicit dependencies) is still valid and we want to continue to support that - as such would need to create an alternate generator implementation to support this and switch based on a config option

Unless there's a strong reason to add support for this, I'm inclined to hold off this particular feature _(e.g. we discover that flat workspace no longer work in Xcode 14 - or some new product types don't build etc...)_

Open to suggestions / comments @tuist/core

**Comment by pepicrft** [comment]
I'm chiming in in this discussion. Just to make sure I understood your need well. You want to stick to the nested-projects model for performance reasons (because you can declare dependencies explicitly) and Tuist's modeling of dependencies is not compatible with it.

Have you explored having a single project with all the targets (assuming you no longer include the .pbxproj in your Git repositories), or using Tuist built-in features for improving build times like binary caching? 

As @kwridan pointed out it's a huge undertaking that touches many core components of the project. We can't commit to that undertaking, and even if we could, I'm a bit concerned about the complexity this will bring to the generation process and the maintenance cost associated with it. Would you mind sharing more about other things that you might have explored to see if we can land on a solution that addresses your concerns but in a different way?

**Comment by pavel-trafimuk** [comment]
@kwridan @pepicrft adding all depended `xcodeproj`s to current `xcodeproj` is not big deal - it already works via `additionalFiles` without any issues (maybe only small improvement - groups them in one group, e.g. "Dependencies")
And even this small hack allows me to have compiled main target which depends on `xcodeproj` (without workspaces). 
Main app target is not on tuist yet (we migrate only 6 frameworks on tuist, 153 total).

But I need anyway still set "find dependency implicitly" (in main app target). 
So as I see (I know that my PoV doesn't cover all edge cases): 
1) expand 
```swift 
enum TargetDependency { 
    case project(target: String, path: Path, asExplicitDependency: Bool = false) 
}
```
2) if project marked as explicit, add his xcodeproj, like we do the same with `additional files` flow
3) add him to "Target Dependencies" section

I don't see how it could affect all other generation rules (e.g. dependency analyzer or something else). Workspace works correctly.
I can try play with new case of TargetDependency instead of expanding current to encapsulate all logic. 
Or maybe I can implement it somehow with plugins? If you afraid to do it publically for all tuist-ers?

p.s. again why I want to continue with it - for now I see that it's a potential blocker for our company and maybe my boss will ask me to change tuist on something else by performance reasons. I don't like it and want to find solution before it will become a problem

**Comment by pavel-trafimuk** [comment]
https://developer.apple.com/documentation/xcode/improving-the-speed-of-incremental-builds

Apple recommendations: 
1) Verifying that your targets have accurate dependencies ensures they build correctly and in a timely manner. Out-of-date dependencies might force Xcode to build targets serially when it might have built them in parallel. Missing dependencies might cause correctness issues or even build errors. For example, if your app doesn’t have an explicit dependency to a separate code module, like an app extension, Xcode might build the app with an older version of the module that doesn’t work properly.
2) When you know a dependency exists between two targets in your Xcode project, create an explicit dependency between them. 
3) If a target depends on code in a different Xcode project, create a reference to that project by dragging it into the navigator pane of your current project. The presence of the other project in the navigator pane gives Xcode the information it needs to track dependencies on items in the other project. Without this reference, Xcode doesn’t know to build your target when the remote project changes.

**Comment by kwridan** [comment]
Thanks for the additional info @pavel-trafimuk 

I don't think we're suggesting your approach is invalid - nested projects is a *valid* approach, it's more a case of it being tricky for us to support this paradigm in Tuist due to the reasons previously mentioned. 

To clarify, is the intention to add a Tuist generated project as a nested project? or an existing `.xcodeproj` that is not generated via Tuist? 

For the former, keep in mind when generating from a clean slate the `.xcodeproj` files may not yet be on disk - as such even the `additionalFiles` approach may not work 😞

**Comment by pavel-trafimuk** [comment]
> 

I know that I have trick with adding not-tuist projects, but I don't want to go this way - we're working on migrating on tuist one-by-one - so let's focus only on tuist-proj-files only.

I found that `xcodeproj` via `additional files` works well because tuist generates dependent proj-files before adding them to the current - otherwise I will be first who will raise this issue :).

What I see and want to prepare as requests:
**1) add abitility to use specific group in `xcodeproj`s for additional files:**
I already opened the request https://github.com/tuist/tuist/pull/4027 (had some local issues with compilation - will improve request bit later)

**2) add auto mode for explicit dependencies** (to hide API changes): 
If the target dependents on other targets and their `xcodeproj` files are already linked to current `xcodeproj` (via additional files) - tuist adds them not only to `linked` section, but to `target dependency` too.
I don't see that it will affect any current behaviors. It will work silently and only for all, who use `additional files` hack.

3) after several weeks of massive testing (e.g. in my project) - we can expose this feature for all by adding "**explicitDependency**" flag to `TargetDependency` cases as I mentioned before

**Comment by danyf90** [comment]
@pavel-trafimuk have you solved this in the end? closing if for now but feel free to reopen if it's still an issue

**Comment by Speakus** [comment]
@pavel-trafimuk did you solve this issue in the end? I completely agree with you: the explicit dependencies is prefer. Not only to improve compile speed but also for fix some old apple issues for multiplatform targets compilation: https://openradar.appspot.com/20490378
