### ISSUE TITLE
Request: enable embedding CLI app within (Mac) application

### ISSUE THREAD

**Issue by MariusDeReus** [tuist/tuist#4205]
Maybe not common for iOS, but It happens quite often that a macOS app embeds a command line application to execute certain tasks.
For example (in our case) a CLI app that is able to restart the main application.

'Before Tuist' these are the steps to achieve this:
- Configure a separate build target for the CLI, 
- Make the main app target depend on the CLI target 
- And then lastly add a copy build step that copies the CLI into the main app bundle 

<img width="571" alt="App setup before Tuist" src="https://user-images.githubusercontent.com/9931253/156171836-11ab4ad0-63ca-4f87-9a64-212dd374b3bf.png">

The problem is that this is currently not possible to configure in Tuist manifests, which means that we cannot convert our project to be build by Tuist. 
When you add a CLI target as dependency for the main app target it results in this error when trying to generate the project:
`Target <main app> has a dependency with target <CLI target> of type command line tool for platform 'macOS' which is invalid or not supported yet.`

**Comment by serejahh** [comment]
I've opened a PR with the fix. The only thing you need is to implement a copy phase using a custom script. You can use `TARGET_BUILD_DIR` variable to find the location of the launcher

**Comment by fortmarek** [comment]
Hey @serejahh 👋 

Thanks a lot for fixing this. As this issue was related to a [bounty](https://github.com/tuist/tuist/discussions/4982), we want to send you 50$ as a thank you for your work 🙏 

You can contact me at [marekfort@me.com](mailto:marekfort@me.com) or send us a DM on [Twitter](https://twitter.com/tuistio) or [Mastodon](https://elk.zone/fosstodon.org/@tuist).
