### ISSUE TITLE
Incorporate SwiftUI

### ISSUE THREAD

**Issue by UncleRic** [tuist/tuist#450]
## Need/problem
Incorporate  SwiftUI.

The current paradigm focuses on the AppDelegate/UIViewController.
SwiftUI introduces the 'SceneDelegate',  etc.

## Motivation

There's a general push toward Declarative vs Imperative design; with SwiftUI being Apple's next-generation UI paradigm.

**Comment by kwridan** [comment]
Hi @UncleRic,

Thanks for flagging this. 

Once Xcode 11 gets release, updating the default template would be a great enhancement. 

Similarly to Xcode this could be an option provided which users can chose from.

```sh
tuist init --template SwiftUI
```

or even via `TuistConfig`

```swift
// TuistConfig.swift
let initOptions = InitOptions(defaultTemplates: [
    .application: .swiftUI
])
```

**Comment by fortmarek** [comment]
I looked at this quickly and it seems to me this will need only really small changes (kudos to [xcdiff](https://github.com/bloomberg/xcdiff)) - the summary of what we might need to change:
- adding `ContentView` (simple `some View`)
- changing initializer from `UIViewController` to `UIHostingController`
- adding `ENABLE_PREVIEWS = YES;` in `buildSetting` in `.pbxproj`
- there's also preview assets folder, but since we do not add assets, I'd skip this step (if not, `DEVELOPMENT_ASSET_PATHS` will need to be added to `buildSettings`, too)

Then there's the whole added default logic of `UISceneDelegate`; but this is something that is now default even without SwiftUI (since it is tied to multiple windows in iPadOS). So, it'd be a good candidate to add everywhere, if it were not only iOS 13.0+. That's why I'd probably leave it out for now and leave it to the users to implement it themselves (until most new projects will be iOS 13.0+), but that's just my opinion.

I'll whip up a basic implementation of the first three differences and will continue with the rest once we're on the same page.

Also, `InitOptions` might be a bit of an overkill IMHO, but it's definitely good to keep this solution in mind in case the `init` options will get overblown in the future.

**Comment by pepibumur** [comment]
> I looked at this quickly and it seems to me this will need only really small changes (kudos to xcdiff) - the summary of what we might need to change:

xcdiff is pure gold ❤️ 

> Then there's the whole added default logic of UISceneDelegate; but this is something that is now default even without SwiftUI (since it is tied to multiple windows in iPadOS). So, it'd be a good candidate to add everywhere, if it were not only iOS 13.0+. That's why I'd probably leave it out for now and leave it to the users to implement it themselves (until most new projects will be iOS 13.0+), but that's just my opinion.

Agree. Keep in mind that this has only been requested here so this is something that not many users might need. If we see more related-requests we can give this one another thought.

I'm planting a seed for thought here. What if we take this and build an scaffolding feature into Tuist using templates. Imagine the following structure inside the `Tuist` directory:

```
Tuist
  Templates
    SwiftUIApp
       DESCRIPTION
       Project.swift
       Sources/
         AppDelegate.swift
    FeatureFramework
      DESCRIPTION
      Project.swift
        Sources/
           AppDelegate.swift
```

With that, developers could run the following commands:

`tuist scaffold list`: That would yield the following:

```bash
Listing all available scaffolding templates:
SwiftPreviewApp - It creates an app ready for SwiftUI
FeatureFramework - It creates a feature framework
```
       
And then developers could run `tuist scaffold FeatureFramework FeatureFramework`

**Comment by fortmarek** [comment]
That's a great idea! I think it'd be interesting to talk with the people who use the project if they would be interested in something like this and how exactly they would use it. This could also maybe be combined with @kwridan idea of `InitOptions` in `TuistConfig` - the teams could describe what their default template for a new framework is etc., so the user does not have to make that choice every time a new part of the project is created. 

Back to the topic of SwiftUI: you can find WIP implementation here: https://github.com/tuist/tuist/pull/785
