### ISSUE TITLE
Embedding frameworks wrapping static libraries

### ISSUE THREAD

**Issue by zdnk** [tuist/tuist#454]
**Describe the bug**
There are some frameworks (Firebase) that are just wrapping static libraries and dont need emdedding. Embedding causes compile/installation error saying there are multiple frameworks havinf the same bundle id.

**To Reproduce**
Cartfile:
```
binary "https://dl.google.com/dl/firebase/ios/carthage/FirebaseAnalyticsBinary.json"
```

Project.swift
```
.framework(path: "../Carthage/Build/iOS/FirebaseInstanceID.framework"),
                .framework(path: "../Carthage/Build/iOS/FIRAnalyticsConnector.framework"),
                .framework(path: "../Carthage/Build/iOS/nanopb.framework"),
                .framework(path: "../Carthage/Build/iOS/GoogleUtilities.framework"),
                .framework(path: "../Carthage/Build/iOS/FirebaseAnalytics.framework"),
                .framework(path: "../Carthage/Build/iOS/FirebaseCore.framework"),
                .framework(path: "../Carthage/Build/iOS/Firebase.framework"),
```

**Expected behavior**
Builds and install just fine.

**Proposed solution**
Optional parameter in dependency definition:
```
.framework(path: "../Carthage/Build/iOS/Firebase.framework", embed: false),
```

**Comment by pepibumur** [comment]
Thanks for bringing this up @zdnk. Are those frameworks dynamic?

**Comment by zdnk** [comment]
Please refer to this https://github.com/firebase/firebase-ios-sdk/blob/master/Carthage.md for more information :)

**Comment by ollieatkinson** [comment]
They are static frameworks, so will not need embedding.

It seems like there's two problems at play here:

1. The frameworks are being embedded by `tuist embed` even though they are static and do not require being. https://github.com/tuist/tuist/blob/master/Sources/TuistKit/Embed/FrameworkEmbedder.swift#L33

We should be checking the MACHO_TYPE before embedding, we do some parsing to check the architectures, we should do the same here.

2. They are being added to the embed build phase. Fixing the above will mitigate this but it might cause some confusion if left as it's not really true to what is happening.  https://github.com/tuist/tuist/blob/master/Sources/TuistGenerator/Generator/LinkGenerator.swift#L118

I think it may be a good idea to provide the option like @zdnk suggested as there might be scenarios in which you do not want Tuist to automatically embed for you.

**Comment by ollieatkinson** [comment]
From looking at the Firebase frameworks there's also another inherent issue with linking them using Tuist. Google require you to copy a bundle to the application main bundle from one stored inside of their frameworks folder as they are static and cannot hold resources. 

```
Carthage/Build/iOS/FirebaseFirestore.framework/gRPCCertificates.bundle
```

The problem lies with trying to include this file in the resources for a Tuist target. It seems to ignore anything inside of another framework (probably for other good reason) - I haven't investigated to why yet. 

However it's possible to work around this by symbolically linking the file elsewhere outside of the framework:

```sh
ln -s Carthage/Build/iOS/FirebaseFirestore.framework/gRPCCertificates.bundle Google/gRPCCertificates.bundle
```

With the above I was able to get the example app for Firebase working with Tuist.

**Comment by zdnk** [comment]
Great. Now just implementation :)
I would try myself but I had quick look and had no idea where to start, I might try later because we are in need of this being in Tuist.

**Comment by pepibumur** [comment]
While adding `embed: true/false` might solve the problem by leaving it up to the developer to decide, I think that's a decision that Tuist can make and therefore simplify the definition of the project.

From your comment @ollieatkinson it seems that there's a bug in the logic that determines whether a framework needs to be embedded or not. If that's the case, I'd fix that instead of adding a new attribute that might confuse users a bit.

**Comment by zdnk** [comment]
I see, well, I am not sure how to fix that as I am not so fluent in these things.

**Comment by pepibumur** [comment]
I'd start by debugging [this method](https://github.com/tuist/tuist/blob/master/Sources/TuistGenerator/Graph/PrecompiledNode.swift#L80) which is the one that returns whether a framework should be dynamically linked or not. Also [this other](https://github.com/tuist/tuist/blob/7923e06480521aac40f93b9b430f646eb25c5c3d/Sources/TuistGenerator/Graph/Graph.swift#L259) method that returns all the frameworks that are embeddable.

Those method have tests so you can run the tests pointing to your frameworks and see the output that you get.
