### ISSUE TITLE
Tuist generates TuistStrings+Module from wrong localization strings file

### ISSUE THREAD

**Issue by bozongiggsa** [tuist/tuist#4627]
## Describe the bug and the expected behavior

If project contains several languages with different regions, ex. en, en-GB, en-NG and "ru" is set as Development Language through Options in Project, then Tuist gets en-GB.lproj/Localizable.strings as a source for generation of TuistStrings+Module file. But I expect that ru.lproj/Localizable.strings would be used as a source for keys when Tuist are generating TuistStrings+Module

## Reproduction steps

Steps to reproduce the bug:

1. Add Localizable.strings for framework Module and add several languages for it. For instance: en, en-GB, fi, de
2. Set "de" as a Development Language. The main thing that it should differs from "en", "en-GB" 
3. Make "tuist generate"
4. Look at TuistStrings+Module.swift file. 

Results: keys in TuistStrings+Module.swift are generated from en-GB.lproj/Localizable.strings file
Expected: keys are generated from de.lproj/Localizable.strings.

### Error screenshots

![image](https://user-images.githubusercontent.com/21315282/180009824-c8c795b0-cbaf-45b8-99e2-c8c5c376385e.png)
![image](https://user-images.githubusercontent.com/21315282/180010028-ca7326a2-43f9-4d75-a639-c8118587d245.png)
![image](https://user-images.githubusercontent.com/21315282/180010188-73d2fcb6-5c51-462e-a254-263c8c937934.png)

### Additional context

- macOS version: 12.4
- Tuist version: 3.5.0
- Xcode version: 13.3.1 (13E500a)

**Comment by fortmarek** [comment]
Hey @bozongiggsa 👋 

You can find the file used for generating these accessors [here](https://github.com/tuist/tuist/blob/main/Sources/TuistGenerator/Utils/SynthesizedResourceInterfacesGenerator.swift). That being said, shouldn't the keys be the same regardless of your current development language? That's the point of keys, they stay the same across the languages 🤔

**Comment by danyf90** [comment]
> Hey @bozongiggsa 👋 
> 
> 
> 
> You can find the file used for generating these accessors [here](https://github.com/tuist/tuist/blob/main/Sources/TuistGenerator/Utils/SynthesizedResourceInterfacesGenerator.swift). That being said, shouldn't the keys be the same regardless of your current development language? That's the point of keys, they stay the same across the languages 🤔 

I think they might be different in case you have some strings not localized in all locales, for example for experiments or features available only in some specific languages/regions

**Comment by AllDmeat** [comment]
> That being said, shouldn't the keys be the same regardless of your current development language? 

Yes, but no. 
We support over 13 languages, and that for today. In a few month we may have more.
During new features development we're adding keys for development language only, because we simply don't know all other supported languages. 
But translators do know. We've integrated translation service — it ships all news keys from development language to translators, they translate, and we receive the result back. That is the time when key with it's translated string is added into the project for the specific language by translation service. Until that time some languages may have not all supported keys. Expect for development language, because it's, well, a development language.

**Comment by danyf90** [comment]
Hi @bozongiggsa @AllDmeat , if you'd like to contribute to the feature, feel free to start from the pointer that Marek lined above, and if you have any question feel free to ask 🙏

**Comment by fortmarek** [comment]
Hey 👋 

Nice find! Can we rewrite the line, so it takes the region for `defaultKnownRegions` from the `developmentRegion` instead?

**Comment by leszko11** [comment]
Yes,

I think default values in `var regionPriorityQueue = defaultKnownRegions ?? ["Base", "en"]` are not needed, because `developmentRegion` is used in the [next line](https://github.com/tuist/tuist/blob/3c97e536e2af576ccefd6e92755735f726d2859a/Sources/TuistGenerator/Mappers/SynthesizedResourceInterfaceProjectMapper.swift#L166). 
Without `["Base", "en"]` it will use:
- `developmentRegion` language if set, and exists in localizables list
- first language from the languages list

**Comment by fortmarek** [comment]
Makes sense, would you be up to implement this change? 😇

**Comment by leszko11** [comment]
On it 🫡
