### ISSUE TITLE
Root plist from Settings Bundle is not synthesised.

### ISSUE THREAD

**Issue by jesus-mg-ios** [tuist/tuist#4761]
### What happened?

If you add a settings bundle inside the app, I expect to get the resources of the bundle in a enum (Derived files). But it does not happen.

### How do we reproduce it?

1. Add new file 
2. Choose Settings
3. Regenerate the project
4. No Settings enum provided.
 
[ios_app_with_Settings.zip](https://github.com/tuist/tuist/files/9606386/ios_app_with_Settings.zip)

As you can see a settings bundle has one or more plist inside it, in one or more levels. Also it has one or more localisable strings, and even it could enclose one or more images.
<img width="339" alt="image" src="https://user-images.githubusercontent.com/85997060/191229289-bfde33fe-4c34-4390-83e6-5d258145f3dc.png">

### Error log

No log

### macOS version

12.0

### Tuist version

3.9.0

### Xcode version

13.4.1

**Comment by danyf90** [comment]
Hi @jesus-mg-ios, it's probably a limitation of resource accessors generation. Would you like to have a look at it? We can provide all the required support 🙏

**Comment by jesus-mg-ios** [comment]
@danyf90, could you guide me about it? 

Thanks in advance, I really appreciate your hard work.

**Comment by jesus-mg-ios** [comment]
Any advice on how, and where start to looking to code the change? @danyf90 @kwridan

**Comment by danyf90** [comment]
Sorry @jesus-mg-ios , I missed the previous message 🙏 
I'm not super confident with this part of the codebase, maybe @kwridan or @fortmarek know this better. Otherwise I can try to have a look myself

**Comment by jesus-mg-ios** [comment]
Thanks @danyf90 I really appreciate your hard work on tuist (I mean, by far your the greatest contributor on issue solving), if you can take a look to guide me I'll be much obliged.

**Comment by jesus-mg-ios** [comment]
@kwridan or @fortmarek could give me any tips to code this? 

Thanks in advance

**Comment by kwridan** [comment]
Hi @jesus-mg-ios sorry for the delay just spotted this.

To my knowledge type safe accessors for resources within a standalone bundle included in a target wasn't something Tuist supported before. The generated types are for direct resources of a target.

Trying to find some reference material - looks like this is the original PR https://github.com/tuist/tuist/pull/2746 that introduced the ability to control the templates used to generate the code via plugins and an example in https://github.com/tuist/tuist/tree/main/projects/tuist/fixtures/app_with_plugins/LocalPlugin 

That said, it's for direct resources rather than resources of an arbitrary bundle.

**Comment by jesus-mg-ios** [comment]
Thanks for the reference @kwridan
