### ISSUE TITLE
"tuist generate" results an error with stream-chat-swift (might be related to xcdatamodeld files?)

### ISSUE THREAD

**Issue by salqueng** [tuist/tuist#4796]
### What happened?

I'm using [stream-chat-swift](https://github.com/GetStream/stream-chat-swift) for developing my application. 
When I use tuist 3.11.0 and below, there isn't any problem. However, after upgrading to tuist 3.12.0, `tuist generate` gives errors related to xcdatamodeld files of stream-chat-swift package.

### How do we reproduce it?

1. Clone https://github.com/salqueng/tuist-with-stream-chat-swift-bug
2. Run `tuist fetch`
3. Run `tuist generate`, and you can see the error log

NOTE:
You can test `tuist generate` works when using 3.11.0, but you need to 
1. Modify .tuist-version as `3.11.0`
2. Run `tuist fetch` again
3. Run `tuist generate`, and you can see it works.

### Error log

```
Resolved cache profile 'Development' from Tuist's defaults
Generating workspace TuistWithStreamChatSwiftBug.xcworkspace
Generating project StreamChat
Generating project TuistWithStreamChatSwiftBug
Trying to add a file at path (REDACTED)/tuist-with-stream-chat-swift-bug/Tuist/Dependencies/SwiftPackageManager/.build/checkouts/stream-chat-swift/Sources/StreamChat/Database/StreamChatModel.xcdatamodeld to a build phase that hasn't been added to the project.
Consider creating an issue using the following link: https://github.com/tuist/tuist/issues/new/choose
```

### macOS version

12.6

### Tuist version

3.12.0

### Xcode version

14.0.1

**Comment by danyf90** [comment]
@alexanderwe I think this might be related to your changes [here](https://github.com/tuist/tuist/pull/4733), would you like to take a look at this? 🙏

**Comment by alexanderwe** [comment]
@danyf90 I will try to have look at it on the weekend

**Comment by alexanderwe** [comment]
I had a first investigation on the issue. The actual error is thrown in `BuildPhaseGenerator.generateResourcesBuildFile(files:fileElements:)`line 397.

```
guard let fileReference = fileElements.file(path: buildFilePath) else {
     throw BuildPhaseGenerationError.missingFileReference(buildFilePath)
}
```

The `buildFilePath` which is searched is: 
`<redacted>/tuist-with-stream-chat-swift-bug/Tuist/Dependencies/SwiftPackageManager/.build/checkouts/stream-chat-swift/Sources/StreamChat/Database/StreamChatModel.xcdatamodeld`

It is actually part of `fileElements`, which is confirmed by running when a breakpoint in line 397 is hit
```
po fileElements.elements[buildFilePath]
▿ Optional<PBXFileElement>
  ▿ some : <XCVersionGroup: 0x600003714540>
```

But the interestingly the element seems to be `XCVersionGroup` which cannot be cast to a `PBXFileReference` which is required within the `ProjectFileElements.file(path:)` methods. That's why the method returns `nil` and the error is thrown.

Just for trying, the following works, but there I am not familiar enough with the `XCodeProj` project to judge if this is correct. 
```
(fileElements.elements[buildFilePath] as! XCVersionGroup).children.first as? PBXFileReference
```

So it seems that `fileElements: [AbsolutePath: PBXFileElement]` can contain types that are not castable to `PBXFileReference`, like `XCVersionGroup` which then lead to the mentioned error. 

@danyf90 Maybe you can shed a little bit more light into the different types ? Is it wrong that a `XCVersionGroup` file is part of  `fileElements: [AbsolutePath: PBXFileElement]` ?

**Comment by alexanderwe** [comment]
Another question that just came up for me. Maybe the `handleCopyResource(resourceAbsolutePath:)` inside `static ResourceFileElements.from(sources:resources:path:excluding:)` is handling it wrongly. If the in general the `StreamChatModel.xcdatamodeld` is a directory, but maybe by using a `.folderReference` for `.copy` rule this is messing something else up because for Xcode it is just a file and not a directory ?

**Comment by danyf90** [comment]
Not super confident with that part of the generation, maybe @kwridan  can shed some light on it 🙏

**Comment by alexanderwe** [comment]
@salqueng The PR that should fix the issue got merged, if you want you can have a test with the current main branch or wait for the next release

**Comment by salqueng** [comment]
Thanks, @alexanderwe :D
