### ISSUE TITLE
Embed precompiled frameworks build phase not working

### ISSUE THREAD

**Issue by santosdiez** [tuist/tuist#485]
## Context 🕵️‍♀️

Xcode 10.3
Tuist 0.17.0

## What 🌱

When setting up a project with tuist and Carthage dependencies, I'm unable to build it from Xcode. It always fails at the `Embed precompiled frameworks` build phase without any clue of the error (no message).

```
Embedding framework Carthage/Build/iOS/PureLayout.framework
Error: Command exited with error code 1 and error: 
Error: Command exited with error code 1 and error: 
```

When running the commands through the command line (exporting the same environment variables as the build phase), it apparently works.

```
> tuist embed Carthage/Build/iOS/PureLayout.framework
Embedding framework Carthage/Build/iOS/PureLayout.framework
Success: Framework embedded
```

**Comment by pepibumur** [comment]
Hi @santosdiez. Thanks for opening this.

It's hard to say from the logs what's going on, which makes me thing that we need to improve that to facilitate debugging.

We can either do that so that you can run it in your project and tell us the exact error that you are getting, or you can debug it yourself pulling the project and running it from Xcode. If you decide for the latter, you can follow these steps:

1. Clone this repository.
2. Run `swift package generate-xcodeproj`
3. Open the project with Xcode and edit the Run section of the `tuist` scheme to pass the `embed` launch argument.
4. Set the Xcode environment variables in code, for example [here](https://github.com/tuist/tuist/blob/master/Sources/TuistKit/Commands/EmbedCommand.swift#L59).
5. Add a breakpoint [in this line](https://github.com/tuist/tuist/blob/master/Sources/TuistKit/Commands/EmbedCommand.swift#L61) and debug from there.
6. Run the scheme.

At some point you should see something being thrown.

Please let me know if that works. Otherwise we can debug it ourselves.

**Comment by santosdiez** [comment]
Hi @pepibumur. Will try to provide some more info, of course! Thanks for the hints :)

**Comment by santosdiez** [comment]
In the end there was an issue with the codesign. The identity was set to `iPhone Developer` and the `xcrun` command was complaining about that identity being ambiguous (I have two certificates matching `iPhone Developer` locally).

Sorry for any inconvenience, and thanks for the tips for debugging!
