### ISSUE TITLE
Definition of umbrella / bridging header not supported

### ISSUE THREAD

**Issue by flowinhoBSCH** [tuist/tuist#486]
Good day,

I think the definition of a custom obj-c bridging header is a very vital point when migrating older projects to Tuist.

Maybe i am overlooking this in the documentation, but from my POV this is not possible yet, correct?

**Comment by kwridan** [comment]
hi @flowinhoBSCH, 

Indeed, defining this is very important for many projects.

You should be able to define it via specifying some custom build settings:

e.g. 

```swift
let settings = Settings(base: [
    "SWIFT_OBJC_BRIDGING_HEADER": "path/to/App-Bridging-Header.h"
])

let project = Project(name: "App",
                      targets: [
                          Target(name: "App",
                                 platform: .iOS,
                                 product: .app,
                                 bundleId: "io.tuist.App",
                                 infoPlist: "App-Info.plist",
                                 sources: "Sources/**",
                                 dependencies: [
                                     // ...
                                ], settings: settings)
])
```

Hope this helps.

**Comment by flowinhoBSCH** [comment]
That's perfect! Thank you!

However i have another issue: the product is a framework that imports the header files in the umbrella like this

```
#import <Framework/FWA.h>
#import <Framework/FWB.h>
#import <Framework/FWC.h>
...

However the files themselves are stored in subdirectories. This means the umbrella header is now copied, but the referenced headers themselves cannot be found.

@kwridan any idea?

**Comment by kwridan** [comment]
ah for Frameworks you wouldn't need to specify the bridging header build setting, just the umbrella header needs to be present.

you can include headers in Targets via specifying headers (see [Target](https://docs.tuist.io/usage-project-swift#target) & [Headers](https://docs.tuist.io/usage-project-swift#headers)).

We also have a fixture we use for testing headers which can also act as a nice demo :)

[`fixtures/ios_app_with_headers/Framework1`](https://github.com/tuist/tuist/blob/master/fixtures/ios_app_with_headers/Framework1/Project.swift)

**Comment by flowinhoBSCH** [comment]
Ah! Thx for sharing that snippet i found the issue i was originally facing.
I did not specify the productName which ended up in the umbrella-header not being correctly generated. 

Low-level suggestion for Tuist: if the product is a framework, ensure the productName is set.

TY @kwridan !

**Comment by kwridan** [comment]
Glad to hear you got it working!

By default the `productName` is set to match the name of the target. Generally would only need to set it in situations where the target name mismatches, or in the case where you have multiple targets that need to share a common product name (e.g. `Framework1-iOS`, `Framework1-macOS`, etc...)

Thanks for the suggestions @flowinhoBSCH

**Comment by smara128** [comment]
Hello, good night

I have a project generated by Tuist and recently started to migrate to XCode 15 due to Apple's requirements, when I start to get some errors that might be related to this thread. 
Would someone be able to take a look and maybe point me to the right direction please ?

My project was working just fine in XCode 14-13-12, but now with XCode15, I keep getting too many errors related to swiftmodule, swiftdoc, abi.json, swiftsourceinfo.

Apparently, XCode is looking for them inside the DerivedData folder deep down into the Objects-normal/x86_64 subdirectory but gets an error: **No such file or directory**

![Screenshot 2024-02-29 at 00 52 12](https://github.com/tuist/tuist/assets/5369844/de762c3c-fae0-4fe5-b28f-c203f828fed3)


I also got a **No type or protocol named 'nw_proxy_config_t'** error too, related to Webkit that isn't even a dependency in that module.

![Screenshot 2024-02-29 at 00 53 35](https://github.com/tuist/tuist/assets/5369844/6088726f-f9a4-4afe-86ff-2f3b55b5751b)


I've tried to update cocoapods, tuist (4.4.0) and even ruby, add postInstall configs I found at StackOverflow, but nothing worked.

I also tried to configure Tuist to add Bridging files for each module like this:

![Screenshot 2024-02-29 at 01 12 44](https://github.com/tuist/tuist/assets/5369844/f4496233-132f-469b-977d-77b6b58edcea)


But no success yet. Appreciate any help.
