### ISSUE TITLE
[Dependencies.swift][SPM] Compile errors when install DatadogCrashReporting through tuist dependencies

### ISSUE THREAD

**Issue by Dmitry-Pliushchai** [tuist/tuist#4901]
### What happened?

Hi. I faced the issue that compiler fails with "Redefinition of enumerator..' errors. The issue reproduces only with installing DatadogCrashReporting as spm dependency via tuist dependencies. It works ok if I use native spm integration.

### How do we reproduce it?

- add [datadog](https://github.com/DataDog/dd-sdk-ios) through Dependencies.swift
- add DatadogCrashReporting  as external dependency to app target
- tuist fetch
- tuist generate
- run project

Sample project with tuist spm dependecies
[DatadogCrashReportingTuistSpm.zip](https://github.com/tuist/tuist/files/10131540/DatadogCrashReportingTuistSpm.zip)

Sample project with native spm
[DatadogCrashReportingNativeSpm.zip](https://github.com/tuist/tuist/files/10131547/DatadogCrashReportingNativeSpm.zip)

### Error log

<img width="505" alt="Screenshot 2022-12-01 at 13 25 25" src="https://user-images.githubusercontent.com/59007906/205028858-efb1b395-b832-4490-bb1f-300f6ccae6a4.png">

### macOS version

13.0.1

### Tuist version

3.12.1

### Xcode version

14.1

**Comment by Sakhanko-Pavel** [comment]
Hi! Could you please help with this bug?

**Comment by Sakhanko-Pavel** [comment]
@danyf90 hi! Any updates here? Could you please help?

**Comment by danyf90** [comment]
Nope, added a bounty to the ticket in case someone wants to have a look at it 🙏

**Comment by MartinStrambach** [comment]
The issue is with `USE_HEADERMAP` build setting. In the original project (https://github.com/microsoft/plcrashreporter) it is set to `YES`. In Tuist, inside `PackageInfoMapper` it is always set to `NO`. Maybe @danyf90 can explain why it's needed. 
If you change this build setting in the generated `PLCrashReporter` dependency project the whole example app builds just fine.

**Comment by danyf90** [comment]
Hi @MartinStrambach looking at the code seems like we are trying to mimick SPM behavior and that looked the default in SPM, but maybe there is some logic to change it in some scenarios.

> In the original project (https://github.com/microsoft/plcrashreporter) it is set to YES

Where to you see this?

**Comment by MartinStrambach** [comment]
> In the original project (https://github.com/microsoft/plcrashreporter) it is set to YES
I meant the framework in the original repository. Since SPM modifief settings, anything can happen during the build phase. It would be really helpful to have a command which would produce similar output like `xcodebuild -scheme "schemeName" -showBuildSettings >> mynew.xcconfig` but for packages integrated via SPM. Maybe I'm missing something, but I cound't find settings which are used for packages in Xcode nor build logs.

**Comment by DimaMishchenko** [comment]
Workaround:
``` swift
targetSettings: [
  "CrashReporter": [
    "USE_HEADERMAP": "YES"
  ]
]
```

**Comment by lpbas** [comment]
> ```swift
> targetSettings
> ```

We are facing the exact same issue with our Datadog integration with Tuist.

Setting the `USE_HEADERMAP` flag to `YES` manually in the project does indeed fix the issue, but adding the target settings that @DimaMishchenko suggested still keeps the flag set to `NO` when running `tuist generate`. Other target settings we are using in our project are working fine on the generated project. Is there any clue to why this happens and how can we resolve this?

(the build settings does not get applied neither in the provided example project, not in our own project that we are trying to integrate Datadog)
