### ISSUE TITLE
 New Carthage dependency not being fetched when tuist fetch executed

### ISSUE THREAD

**Issue by louis-prudhomme** [tuist/tuist#4969]
### What happened?

Hi !! 

I encountered exactly the same issue as #4731. When adding a new Carthage dependency to a project which already has one, `tuist fetch` will seemingly overlook changes in the `Cartfile` and will not fetch the new dependency.

I am not sure why the original author stopped responding (leading to the subsequent closure of the issue), but I strongly believe this is an unwanted behavior.

Moreover, I tried to run `tuist clean` to get rid of the `Cartfile.resolved`, in order to force refetching all dependencies.

However, while `tuist clean` wiped the `Tuist/Carthage` folder, it preserved the `Tuist/Lockfiles` folder.

This, in turn, forces to `rm` the `Cartfile.resolved` manually in order to fix the problem. 

Thanks!

### How do we reproduce it?

1. Create a new tuist based project
2. Create the file `Tuist/Dependencies.swift`
3. Add the following Carthage dependency:

    ```
    .github(path: "airbnb/lottie-ios", requirement: .upToNext("3.3.0"))
4. Save and run tuist fetch
 
    Note the command will run with the following output:

    ```
    Installing Carthage dependencies.
    *** Checking out lottie-ios at "3.4.3"
    *** xcodebuild output can be found in /var/folders/r7/5xrc03195199mmn2yq9rt1r40000gr/T/carthage-xcodebuild.BZelBc.log
    *** Valid cache found for lottie-ios, skipping build
    Carthage dependencies installed successfully
5. Next add the following as a Carthage dependency:

    ```
    .github(path: "krzyzanowskim/CryptoSwift", requirement: .upToNext("1.0.0")),
6. Re-run tuist fetch.
   
    Note the following output:

    ```
    Installing Carthage dependencies.
    *** Checking out lottie-ios at "3.4.3"
    *** xcodebuild output can be found in /var/folders/r7/5xrc03195199mmn2yq9rt1r40000gr/T/carthage-xcodebuild.BZelBc.log
    *** Valid cache found for lottie-ios, skipping build
    Carthage dependencies installed successfully.

### Error log

No error is shown. 

### macOS version

12.6

### Tuist version

3.14.0

### Xcode version

14A309

**Comment by danyf90** [comment]
Assuming you would use pure Carthage, which command would you run after you change the `Cartfile`?

**Comment by louis-prudhomme** [comment]
Honestly, I'm not sure, I'm quite green and not at all familiar with Carthage

**Comment by danyf90** [comment]
I assume it's due to the package manager to update the lockfile is not aligned with the dependencies definition, and it is how it works with SPM or CocoaPods, but I don't know Carthage either so can't reply about that.

Is there any reason you want to use Carthage over SPM?

**Comment by danyf90** [comment]
> Regardless, I think tuist clean should remove the Tuist/Lockfiles/ folder.

That's not correct (at least for SPM and CocoaPods): if I add a new dependency to my Package.swift I still want the other dependencies to not change and respect what is reported in the `Package.resolved` file, regardless of the fact that I've run `tuist clean` or not

**Comment by louis-prudhomme** [comment]
> and respect what is reported in the Package.resolved file

I see your point. Do you commit your `Package.resolved` / `Cartfile.resolved` files ? We assumed Tuist would compute them anew every time and that we'd be fine.

> if I add a new dependency to my Package.swift I still want the other dependencies to not change 

On the other hand, when I update the list of Carthage dependencies and run `tuist fetch`, I'd expect tuist to fetch any new depdendency ; if it does not work this way because the `Cartfile.resolved` is what actually matters, in return I'd expect to be able to clean it with `tuist clean`

**Comment by kientux** [comment]
I used to use Carthage as main dependencies management tool and as I remember, this is an issue of Carthage itself. It will completely ignore your `Cartfile` if `Cartfile.resolved` exists. Except when you run `carthage update`, it will resolves deps again based on `Cartfile`.

I'm not sure about how Tuist run carthage commands, but I think it will let carthage run exactly like above.

> We assumed Tuist would compute them anew every time and that we'd be fine.

Usually it's not good because you wouldn't want your dependencies to be changed between developers computers each time they run `tuist fetch`. Dependencies versions should be declared in a lock file.

**Comment by PierreCapo** [comment]
@kientux thanks for your insights, I am not super familiar with Carthage either, so that's interesting to know.
Now, I am digging into the[ Carthage documentation](https://github.com/Carthage/Carthage#upgrading-frameworks) and I have found exactly what you are saying:

> Upgrading frameworks
> If you’ve modified your [Cartfile](https://github.com/Carthage/Carthage/blob/master/Documentation/Artifacts.md#cartfile), or you want to update to the newest versions of each framework (subject to the requirements you’ve specified), simply run the carthage update command again.

To sum up, right now the correct workflow between Tuist and Carthage is: 
1. I add a carthage dependency to Tuist
1 bis. Or I update a carthage dependency
2. If I already have a `Cartfile.resolved`, I need to run `carthage update myDependency`.

@danyf90 In terms of Tuist API, would it make sense to open a PR so that when running `tuist fetch` also executes `carthage update` ? A side-effect is that it will also update the other carthage dependencies (subject to the requirements specified in `Dependencies.swift`), but I think it would be an improvement compared to the current situation.

**Comment by danyf90** [comment]
> I see your point. Do you commit your Package.resolved / Cartfile.resolved files ?

Yes, that's the point of the lock file 👍 

> @danyf90 In terms of Tuist API, would it make sense to open a PR so running tuist fetch also executes carthage update ?

I wouldn't do it by default, because unexpected dependency updates are risky, but there is already a `--update` parameter that should do exactly that. Could you please confirm it works as expected, and close the issue if it is the case?

**Comment by PierreCapo** [comment]
Oh nice, I didn't know such a flag existed. Looks good to me then, thanks for the help 👍
