### ISSUE TITLE
Change the Target Membership of file in Xcode interface is ignored

### ISSUE THREAD

**Issue by GuilhermeTrevisan** [tuist/tuist#5030]
### What happened?

Hi all, I need to change the target membership of some files, but when I do it through the Xcode interface this modification works just locally. 
Running a `tuist generate` revert the changes, also there are no changes in my git diff, so I cannot push these target modifications to the repo, and the CI breaks.
I looked so much but couldn't find anyone talking about this. Didn't find anything about this in the docs too.

**I have a critical demand that depends on it, so if you guys have some workaround it would be nice too!** 

(prints from the left sidebar, the inspector of the files in Xcode)
### original
![image](https://user-images.githubusercontent.com/43553759/217079367-72926bc4-f7f9-4122-aaf8-50a03b894d7c.png)

### modify
![image](https://user-images.githubusercontent.com/43553759/217082086-52098bcf-bc4c-4e45-b868-3a9b1bfabd99.png)

### my git
running a `git status` I just get `nothing to commit, working tree clean`
the interface shows the same:
<img width="328" alt="image" src="https://user-images.githubusercontent.com/43553759/217082596-f7c26446-43ba-45ea-a41a-c0f312c6f06f.png"> 

### after running a `tuist generate`
![image](https://user-images.githubusercontent.com/43553759/217092582-d47d0234-6b8e-4ca6-828a-89a258d8aead.png)

The version used in my project is the `2.7.2`, but I also try updating it to `3.15.0` and the behavior stays the same.

Is there another way to change it? Is it a bug?

Thanks!

### How do we reproduce it?

- Add a file to another target through the left sidebar of Xcode (File inspector), in the Target Membership section
- Look at your git diff, nothing changes (so it cannot be pushed to a repo)
- Run a `tuist generate`, you can see the blue checkmark disappearing in the Xcode interface right after the command ends
- Now the file is no longer in the target you added before

### Error log

There is no error message, just the weird behavior

### macOS version

12.6.3

### Tuist version

2.7.2 (I also tried in 3.15.0)

### Xcode version

14.0

**Comment by kientux** [comment]
This is how tuist (or any Xcode project generation tool) works. You can't change target membership directly in Xcode and expect it to be saved, because `.xcodeproj` file will be overwritten everytime tuist run. You have to put the file in correct directory that you specify in `sources:` path of the target.

**Comment by kwridan** [comment]
As @kientux mentioned this is the expected behaviour and workflow of project generation tools. For Tuist, the project manifest (`Project.swift`) acts as the source of truth that declares which sources go to which targets.

```swift
Target(
    name: "FasterCore",
    // ...
    sources: [
        "Sources/**",
    ]
)
Target(
    name: "FasterCoreTests",
    // ...
    sources: [
        "Tests/**",
    ]
)
``` 

If you require some files to be part of both, the simplest option is to create another directory which is added to both target sources.

```swift
Target(
    name: "FasterCore",
    // ...
    sources: [
        "Sources/**",
        "Shared/**",
    ]
)
Target(
    name: "FasterCoreTests",
    // ...
    sources: [
        "Tests/**",
        "Shared/**",
    ]
)
``` 

There are alternate more elaborate options using exclude sources too to allow sharing sources in the same directory if needed

**Comment by GuilhermeTrevisan** [comment]
Thank you guys, your answers helped me a lot, I appreciate it!
