### ISSUE TITLE
Support for multiple entitlements

### ISSUE THREAD

**Issue by bolshedvorsky** [tuist/tuist#5197]
### What happened?

We support building Prod, Stage and Beta targets. Each of these have few configurations like Debug, Ad-Hoc or App Store. The relationship between Target -> configuration for the Prod app would look like that:

Target: Prod
- configuration: Debug
- configuration: Ad-Hoc
- configuration: Prod

Each configuration has it's own set of settings in the entitlements file. The majority of the settings do not cause issues, except for the Apple Wallet specific `com.apple.developer.in-app-payments` and `com.apple.developer.payment-pass-provisioning` These settings need to be present only in the configurations where we deploy our app to our users (Prod, Beta) and they should be omitted in the others. Xcode fails to build a project if there is a mismatch between entitlements file and corresponding provisioning profile. Effectively, it means that we need to provide a custom entitlements file for each of the configurations. Our current project setup does exactly that.

Tuist, in turn, [allows](https://docs.tuist.io/1/manifests/project/#target) to specify only single entitlements file per target. It's restricted at the API level. There is an advised workaround for handling [multiple entitlements](https://github.com/tuist/tuist/issues/4596) that I've implemented, but it does not allow to exclude entire keys with values from the plist files.

I've also noticed that Tuist ignores the setting `CODE_SIGN_ENTITLEMENTS` and overrides it if pas a path to entitlements in target definition

### How do we reproduce it?

It's the same issue as reported here: https://github.com/tuist/tuist/issues/4596

### Error log

No error, missing functionality

### macOS version

13.2.1

### Tuist version

3.19.0

### Xcode version

14.2.0

**Comment by fortmarek** [comment]
I think this use case warrants adding support for configuration-specific entitlement files. What do you think, @kwridan?

**Comment by kwridan** [comment]
Hi @bolshedvorsky 

Thanks for flagging this.

currently specifying `entitlements` is optional omitting it from the manifest would allow you to specify it as a build setting where you'll have much more control. The trick with the variable key/values indeed only works for differences in values rather than exclusions as you have rightfully pointed out. 

e.g.

```
// Debug.xcconfig
CODE_SIGN_ENTITLEMENTS = App/debug.entitlements
```

```
// Ad-Hoc.xcconfig
CODE_SIGN_ENTITLEMENTS = App/ad-hoc.entitlements
```

```
// Prod.xcconfig
CODE_SIGN_ENTITLEMENTS = App/prod.entitlements
```

An alternative if you'd like to retain visibility to the entitlements file in the manifest is via specifying a variable which is controlled via the target configurations:

```swift
Target(
            settings: .settings(
                base: [
                    "CODE_SIGN_ENTITLEMENTS": "$(APP_ENTITLEMENTS_FILE)",
                ],
)
```

And then within the xcconfig files or even within the manifest itself you can specify a different value 

```
// Debug.xcconfig
APP_ENTITLEMENTS_FILE = App/debug.entitlements
```

```
// Ad-Hoc.xcconfig
APP_ENTITLEMENTS_FILE = App/ad-hoc.entitlements
```

```
// Prod.xcconfig
APP_ENTITLEMENTS_FILE = App/prod.entitlements
```

I think falling back to explicit build settings / config for some use cases should suffice, as this isn't unique to entitlements, similar requires have been made for bundle IDs , info plists etc... 🤐

Hope this helps!
