### ISSUE TITLE
Tuist/Package.swift not included in Xcode when running "tuist edit"

### ISSUE THREAD

**Issue by bdbergeron** [tuist/tuist#5537]
### What problem or need do you have?

After adopting the latest release (3.31.0) that introduced `Package.swift` support for defining SPM dependencies (#5503), the Xcode workspace generated with `tuist edit` does not include the `Tusit/Package.swift` file.

### macOS version

14.1

### Tuist version

3.31.0

### Xcode version

15.0.1

**Comment by danyf90** [comment]
Ciao @bdbergeron , it totally makes sense to include it, would you like to open a PR to add support for this? 🙏

**Comment by bdbergeron** [comment]
@danyf90 Sure, I can give it a go here in a bit; I unfortunately had to pause migrating to the new `Package.swift` dependencies format due to my project no longer building successfully with it. Started getting duplicate file warnings from a couple third-party dependencies that are transitively included in my project.

**Comment by ImaginativeShohag** [comment]
Please add `Package.swift` to `tuist edit`. As the old system is already deprecated, new users will get confused when they don't find the file in project view.

**Comment by pepicrft** [comment]
This will be addressed as part of the Tuist 4 release, which we are aiming to release in January 2024.

**Comment by shahzadmajeed** [comment]
@pepicrft @danyf90 couple of thoughts/clarifying questions:

1. We need to make sure none of the Manifest project targets are importable in `Tuist/Package.swift`
2. We need to import the correct version of the developer framework `PackageDescriptions`into Manifest project's framework as dependency (according to toolchain specified in package comments or file name itself). Is this right or am I thinking wrong here?
3. OR instead of #2 we can include Package.swift as a local package so that it can resolve in `Manifest` project when we make changes? I know we will be back to SPM quirks but that will make it standalone working code.

**Comment by pepicrft** [comment]
I haven't looked much into the implementation details, but we should be able to map a toolchain version to the directory containing the `PackageDescription` of that toolchain version. If that option doesn't work, 3 is another one that we could consider.

**Comment by fortmarek** [comment]
Combination of:
- Setting `-package-description-version x.y.z` for `OTHER_SWIFT_FLAGS` where `.x.y.z` can be extracted from `swift package tools-version` command
- And `/Applications/Xcode-x.y.z.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/swift/pm/ManifestAPI` `SWIFT_INCLUDE_PATHS`

Seems to do the trick. I will soon prepare a PR for this.

**Comment by danyf90** [comment]
> Combination of:
> 
> * Setting `-package-description-version x.y.z` for `OTHER_SWIFT_FLAGS` where `.x.y.z` can be extracted from `swift package tools-version` command
> * And `/Applications/Xcode-x.y.z.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/swift/pm/ManifestAPI` `SWIFT_INCLUDE_PATHS`
> 
> Seems to do the trick. I will soon prepare a PR for this.

Amazing 😍

**Comment by pepicrft** [comment]
Sweet! Nice findings
