### ISSUE TITLE
Allow downloading SPM packages which require auth tokens from ~/.netrc

### ISSUE THREAD

**Issue by StylianosGakis** [tuist/tuist#5804]
### What problem or need do you have?

I am publishing a SPM artifact from one of our Github Repositories in GitHub, and in order to be able to bring it in to our iOS project we need to auth with our GH credentials.
The way we do this can be pretty much explained here https://touchlab.co/kmmbridge-quick-start#xcode and here https://touchlab.co/kmmbridge-quick-start#add-the-framework-to-xcode

When we do this in a sample project without Tuist this process simply works, as Xcode knows to read the credentials from there. When trying to make this work with Tuist it seems like those credentials are not taken into consideration.

Is there something we can do here to make it all work with Tuist?

### macOS version

14.1.1

### Tuist version

3.40.0

### Xcode version

15.1

**Comment by StylianosGakis** [comment]
When running tuist, we get an error like this:
```
Resolving package dependencies using xcodebuild
2024-01-16 15:41:09.698 xcodebuild[98471:7050216] Writing error result bundle to /var/folders/zz/yvxv6fxvn_n0000000000000/T/ResultBundle_2024-16-01_15-41-0009.xcresult

xcodebuild: error: Could not resolve package dependencies:
 failed downloading 'https://maven.pkg.github.com/org/libname-1.1.0.zip' which is required by binary target 'libname': badResponseStatusCode(401)
 fatalError


The 'xcodebuild' command exited with error code 74 and message:
2024-01-16 15:41:09.698 xcodebuild[98471:7050216] Writing error result bundle to /var/folders/zz/yvxv6fxvn_n0000000000000/T/ResultBundle_2024-16-01_15-41-0009.xcresult
xcodebuild: error: Could not resolve package dependencies:
 failed downloading 'https://maven.pkg.github.com/org/libname/com/org/libname/libname/1.1.0/libname-1.1.0.zip' which is required by binary target 'libname': badResponseStatusCode(401)
 fatalError


Consider creating an issue using the following link: https://github.com/tuist/tuist/issues/new/choose
```
Which is what has lead me to believe that this is the problem.
Again to make sure this is clear, without Tuist importing the artifact works without any problems, so we're a bit stuck as to what else we can try here.

**Comment by pepicrft** [comment]
Hey @StylianosGakis 
I believe we already have a solution for this. If you look at [this piece of code](https://github.com/tuist/tuist/blob/main/Sources/TuistGenerator/Utils/SwiftPackageManagerInteractor.swift#L75C37-L75C69), you'll notice that when `Config.generationOptions.resolveDependenciesWithSystemScm` is set to true, it invokes `xcodebuild` for resolving packages but telling it to use the system credentials, which I believe are the ones you want to use. Otherwise, it'll default to using the ones managed by Xcode. Could you try to set that option in your `Tuist/Config.swift` and tell me if it works?

**Comment by StylianosGakis** [comment]
Hey thanks for the quick response here.

I have to unfortunately mention that ever after using `generationOptions: .options(resolveDependenciesWithSystemScm: true)` I encounter the same issue when I try to run Tuist, this doesn't seem to resolve my issue.

The interesting thing is that when I then try to build my project it does properly get resolved by Xcode so it works locally, but since Tuist fails for me it's something that will mess up the way our CI works, since it will consider it a failure.

Is there something else that you can imagine may be playing a role here?

**Comment by pepicrft** [comment]
Hey @StylianosGakis.
I'm sorry to hear that. Let's do a test. Could you try to create a `Package.swift` in a directory, add the private dependencies there, and invoke the following command in the CLI pipeline:

```bash
swift package resolve --package-path /path/to/directory
```

I guess the command will also fail because Swift Package Manager is not picking the credentials from the CI environments. If so, we need to figure out how to make it pick them, and then make sure that's something that we allow to configure, or that we do automatically so that users don't have to worry about this at all.

**Comment by sladan-hedvig** [comment]
First of all, thank you @StylianosGakis for opening this issue.
I am developer who encountered this issue and we managed to run everything fine on one of our computers.
Apparently issue was with tuist cache. 

It works like a charm now.

Thank you @pepicrft. This issue can be closed.

**Comment by Gladkov-Art** [comment]
Having similar issue with using credentials from ~/.netrc file:

```
❯ swift package --package-path <truncated>ios/Tuist resolve
Computing version for <truncated>
error: failed fetching <truncated> releases list from https://<truncated>/spm-registry: missing or invalid authentication credentials

❯ swift package --package-path <truncated>ios/Tuist resolve --netrc
Computing version for yandexsuperapp.DivKit
Computed yandexsuperapp.DivKit at 30.9.0 (3.62s)
Computing version for yandexsuperapp.BCRunner
Computed yandexsuperapp.BCRunner at 24.6.80007 (2.55s)
Computing version for spm-external.Adjust
Computed spm-external.Adjust at 4.35.2+20c2666082c372f9f2c0adf871d8cef195d011f7 (2.21s)
Computing version for yandexsuperapp.VGSL
Computed yandexsuperapp.VGSL at 6.4.0 (4.20s)
Computing version for yandexsuperapp.BCCommon
Computed yandexsuperapp.BCCommon at 24.6.80007 (5.94s)
Fetching spm-external.Adjust from cache
Fetched spm-external.Adjust from cache (0.48s)
Fetching yandexsuperapp.BCCommon from cache
Fetched yandexsuperapp.BCCommon from cache (0.00s)
Fetching yandexsuperapp.BCRunner from cache
Fetched yandexsuperapp.BCRunner from cache (0.00s)
Fetching yandexsuperapp.DivKit from cache
Fetched yandexsuperapp.DivKit from cache (0.52s)
Fetching yandexsuperapp.VGSL from cache
Fetched yandexsuperapp.VGSL from cache (0.16s)
```

It seems that `resolveDependenciesWithSystemScm` doesn't affect `swift package` calls.

Is there any way to make Tuist run `swift package resolve` with `--netrc` option?

**Comment by sladan-hedvig** [comment]
Make sure you have everything set properly inside .netrc file since you got this message
`missing or invalid authentication credentials
`

If it is still happening,

Try running this from the command line - spm and tuist cleaning
```
tuist clean
rm -rf ~/Library/Caches/org.swift.swiftpm
rm -rf ~/Library/org.swift.swiftpm
```

and deleting folder related to your project inside
/Users/youruser/Library/Developer/Xcode/DerivedData/
(or everything inside that folder if not sure)

**Comment by fortmarek** [comment]
The `resolveDependenciesWithSystemScm` is only meant for packages defined in `Project.swift`, not `Tuist/Package.swift`. For those, you currently need to run the `swift package resolve` manually to pass the extra flag instead of running `tuist install`. Note we'll soon support codifying the extra flags in the `Config.swift`: https://github.com/tuist/tuist/pull/6612
