### ISSUE TITLE
Update DeploymentTargets API

### ISSUE THREAD

**Issue by fortmarek** [tuist/tuist#5844]
The `DeploymentTargets` struct should be an array of `DeploymentTarget` instead.

**Comment by waltflanagan** [comment]
im a little curious about the motivation here, what friction was the current API causing?
The original choice here was to enforce one value per platform at the initializer level and providing static methods for the single platform case.  As an array nothing would prevent multiple definitions for a single platform.  IMO, it'd be preferable to fail at the compilation phase instead of the listing phase, but curious to learn more about what brought this up.

**Comment by fortmarek** [comment]
>  IMO, it'd be preferable to fail at the compilation phase instead of the listing phase, but curious to learn more about what brought this up.

I feel the current API is slightly weird if you want to use multiple platforms. Sure, with an array you can specify a platform multiple times but that's the same design of `Package.platforms` property.  But we can also keep it as-is, I ran into it and thought the `public init` is slightly awkward (i.e., you have to specify all platforms as soon as you want to define the deployment target for more than one)
