### ISSUE TITLE
Improve the init template

### ISSUE THREAD

**Issue by pepicrft** [tuist/tuist#5897]
Our template should include a `.mise.toml` file with the Tuist tool pointing to the exact version that was used to create the project, and also a skeleton`Package.swift` that serves as a starting point for people to add dependencies.

**Comment by dxmvsh** [comment]
Hi, @pepicrft!

I was working on this issue for a couple of hours and I've succeeded with adding `.mise.toml` file in init command default template. I have some problems with including skeleton of `Package.swift` file, because I can't quite understand what kind of code template should be there. I looked through fixtures/ folder for appropriate `Package.swift` as dependencies adding point and couldn't find anything. Maybe I missed something, would really appreciate any help here 🙏🏿

Since this issue is open for more than a month, I think the requirements might be changed. I can already open PR with `.mise.toml` file in default template.

**Comment by fortmarek** [comment]
I think it would be good if the generated `Tuist/Package.swift` would look something like:
```
// swift-tools-version: 5.9
import PackageDescription

#if TUIST
    import ProjectDescription
    import ProjectDescriptionHelpers

    let packageSettings = PackageSettings(
        productTypes: [
            // Customize the product types for specific package product
            // Default is .staticFramework
            // "Alamofire": .framework,
        ]
    )
#endif

let package = Package(
    name: "PackageName",
    dependencies: [
        // Add your own dependencies here:
        // .package(url: "https://github.com/Alamofire/Alamofire", from: "5.0.0"),
    ]
)
```

Does that answer your question, @dxmvsh? Feel free to open a draft PR, it may be easier to talk over a specific piece of code 🙂

**Comment by dxmvsh** [comment]
@fortmarek, Thank you for reaching out! It really helped me to successfully add `Package.swift` template and before that I had to make some corrections:

When `tuist build` command is executed, it ends up with an error. I guess it couldn't find `ProjectDescriptionHelpers` module. 
```
The 'swift' command exited with error code 1 and message:
/Users/strong/workspace/trash/NewCo/Tuist/Package.swift:6:12: error: no such module 'ProjectDescriptionHelpers'
    import ProjectDescriptionHelpers
           ^

Consider creating an issue using the following link: https://github.com/tuist/tuist/issues/new/choose[0m
Program ended with exit code: 1
```

Removed the `import ProjectDescriptionHelpers` line and it failed with error that `productTypes` should be empty dictionary with `:`. 

Changed it to this:
```
let packageSettings = PackageSettings(
    // Customize the product types for specific package product
    // Default is .staticFramework
    // productTypes: ["Alamofire": .framework,]
    productTypes: [:]
)

```

Created PR [here](https://github.com/tuist/tuist/pull/6044)
