### ISSUE TITLE
Multiplatform capabilities broken

### ISSUE THREAD

**Issue by thebarndog** [tuist/tuist#5918]
### What happened?

The multiplatform fixtures seem to be broken, in particular `multiplatform_app_with_sdk`. I was building something similar on by own and encountered this error:

```sh
We received an error that we couldn't handle:
    - Localized description: The operation couldn’t be completed. (TuistKit.UnspecifiedPlatformError error 1.)
    - Error: Only single platform targets supported. The target DataModels specifies multiple supported platforms (watchos, ios).
```

When trying to run `tuist build` on the multiplatform fixture, I encountered the same error.  Doesn't seem to be tied to a specific version of Tuist; the fixture uses 3.4.0 and I was using 4.0.0, same issue. If this is a real issue and not something simple I'm missing, I suspect it hasn't been found because it's rare to have multiple platforms for the same app within a project, necessitating a multiplatform framework. 

### How do we reproduce it?

1. Run `tuist build` on the `multiplatform_app_with_sdk` fixture
2. Observe build error

### Error log

We received an error that we couldn't handle:
    - Localized description: The operation couldn’t be completed. (TuistKit.UnspecifiedPlatformError error 1.)
    - Error: Only single platform targets supported. The target DataModels specifies multiple supported platforms (watchos, ios).

### macOS version

14.1.2

### Tuist version

3.4.0

### Xcode version

15.2

**Comment by pepicrft** [comment]
Thanks a lot for reporting this @thebarndog. The issue is that we haven't yet updated the `build`, `test` and `run` CLI commands to support multi-platform targets. I've created a PR to [improve the presentation of the error message](https://github.com/tuist/tuist/pull/5919), and created an [issue](https://github.com/tuist/tuist/issues/5920) to add support for it.
Let's continue the discussion in the latter.
