### ISSUE TITLE
`tuist generate <modulename>` from root folder fails for manifest defined at module level

### ISSUE THREAD

**Issue by vijaytholpadi** [tuist/tuist#5950]
### What happened?

With a project structure like:
- ParentModule Project (Package.swift defined here)
  - UIComponents project (Project.swift defined at this level)
  
  Calling `tuist generate <submodule name>` from ParentModule level throws the following error
  
  ```
  Manifest not found at path /ParentModule
  ```

Note: Calling `tuist generate <submodule name>` from the ParentModule level with a `Project.swift` at the ParentModule containing UIComponents module definitions level works.

### How do we reproduce it?

Attaching a sample project below
[ParentModule.zip](https://github.com/tuist/tuist/files/14329901/ParentModule.zip)

### Error log

  ```
  Manifest not found at path /ParentModule
  ```

### macOS version

14.1

### Tuist version

4.2.5

### Xcode version

15.2

**Comment by pepicrft** [comment]
Here's the working version of it @vijaytholpadi. Note the following:
- There's no concept of parent module in Tuist. I'd recommend not using that terminology because it's misleading. Instead, there's an **entrypoint**, which is either a `Workspace.swift` or a `Project.swift` and Tuist expects them to be present in the directory from where you run Tuist commands, or the directory that you are pointing to through the `--path` flag.
- The other concept is **root directory**, which is the directory that contains the `/Tuist` directory, and that's the directory that Tuist uses as a reference to find your dependencies. They are either in the `Package.swift` at the root directory or under `{rootdirectory}/Tuist/`. Your fixture contained no `/Tuist` directory.
- Because you want to generate from the root, you need a `Workspace.swift` at the root, which references the projects in the repository. In your case that's a reference to the `UIComponents` directory. Note that the reference is a relative path pointing to the directory containing the project. 

[ParentModule.zip](https://github.com/tuist/tuist/files/14356699/ParentModule.zip)

I'll close the issue. Please, don't hesitate to re-open it if you think your issue remains unaddressed.
