### ISSUE TITLE
`error: no such module 'ProjectDescription'`

### ISSUE THREAD

**Issue by kapitoshka438** [tuist/tuist#5961]
### What happened?

`tuist edit` and even `tuist version` produces the error

### How do we reproduce it?

-

### Error log

```
error: no such module 'ProjectDescription'
import ProjectDescription
       ^

zsh: trace trap  tuist version
```

### macOS version

14.2.1

### Tuist version

4.3.1

### Xcode version

15.2

**Comment by JackieQi** [comment]
same here

**Comment by pepicrft** [comment]
Hey folks 👋🏼 
Apologies for this, we released a faulty version that causes that issue, but after that we pushed a new version that should be working fine. You'll have to uninstall your install version, `mise uninstall tuist@4.3.1` and install it again.
We've created an issue to improve our release scripts so that this doesn't happen again.

**Comment by seekcx** [comment]
same issue in 4.65.0
