### ISSUE TITLE
Tuist links an additional framework leading to duplication errors

### ISSUE THREAD

**Issue by mflknr** [tuist/tuist#6081]
### What happened?

Hello,
when trying to add [Usercentrics](https://bitbucket.org/usercentricscode/usercentrics-spm-sdk/src/master/) packages to our app, we get a duplication error because a `.framework` is added during the `Link Binary With Libraries` build phase although a `.xcframework` is already there. This leads to duplication errors during compilation.

However using the same packages with a vanilla Xcode / SPM project ([tuist-uc-issue-spm.zip](https://github.com/tuist/tuist/files/14614022/tuist-uc-issue-spm.zip)) it works just as expected. And also, if I use an older version of the package in a tuist project (2.9.1 instead of 2.13.0 for example) it also works ([tuist-uc-issue-tuist_working.zip](https://github.com/tuist/tuist/files/14614024/tuist-uc-issue-tuist_working.zip)). It seems like the package comes with additional frameworks which tuist cannot interpret correctly? 

On a sidenote: Removing `UsercentricsUI.framework` from the `Link Binary With Libraries` build phase manually resolves the issue.

### How do we reproduce it?

1. Download the sample project [tuist-uc-issue-tuist_error.zip](https://github.com/tuist/tuist/files/14614013/tuist-uc-issue-tuist_error.zip)
2. Run `tuist install`
3. Run `tuist generate -n`
4. Open the workspace and run the project

### Error log

```sh
error: Multiple commands produce '/Users/mflknr/Library/Developer/Xcode/DerivedData/TuistUcIssueTuist-aekkyzcjiqxwmtavswaiqzkremsg/Build/Products/Debug-iphonesimulator/UsercentricsUI.framework'
    note: Command: ProcessXCFramework /Users/mflknr/Developer/Repositories/tuist-uc-issue-tuist/Tuist/.build/artifacts/usercentrics-spm-ui/UsercentricsUIFramework/UsercentricsUI.xcframework /Users/mflknr/Library/Developer/Xcode/DerivedData/TuistUcIssueTuist-aekkyzcjiqxwmtavswaiqzkremsg/Build/Products/Debug-iphonesimulator/UsercentricsUI.framework ios simulator
    note: Target 'UsercentricsUI' (project 'UsercentricsUI') has create directory command with output '/Users/mflknr/Library/Developer/Xcode/DerivedData/TuistUcIssueTuist-aekkyzcjiqxwmtavswaiqzkremsg/Build/Products/Debug-iphonesimulator/UsercentricsUI.framework'
error: Multiple commands produce '/Users/mflknr/Library/Developer/Xcode/DerivedData/TuistUcIssueTuist-aekkyzcjiqxwmtavswaiqzkremsg/Build/Products/Debug-iphonesimulator/UsercentricsUI.framework/UsercentricsUI'
    note: Command: ProcessXCFramework /Users/mflknr/Developer/Repositories/tuist-uc-issue-tuist/Tuist/.build/artifacts/usercentrics-spm-ui/UsercentricsUIFramework/UsercentricsUI.xcframework /Users/mflknr/Library/Developer/Xcode/DerivedData/TuistUcIssueTuist-aekkyzcjiqxwmtavswaiqzkremsg/Build/Products/Debug-iphonesimulator/UsercentricsUI.framework ios simulator
    note: Target 'UsercentricsUI' (project 'UsercentricsUI'): Libtool /Users/mflknr/Library/Developer/Xcode/DerivedData/TuistUcIssueTuist-aekkyzcjiqxwmtavswaiqzkremsg/Build/Products/Debug-iphonesimulator/UsercentricsUI.framework/UsercentricsUI normal
```

### macOS version

Sonoma 14.3.1

### Tuist version

4.6.0

### Xcode version

15.1.0

**Comment by pepicrft** [comment]
Hi @mflknr 👋🏼 
Thanks for reporting this one. Based on your description, it seems it's a legit bug in the logic that maps Swift Packages to Xcode projects. Thanks for including a project where we can reproduce the issue 🙏🏼.
Note that we are a bit overloaded with requests, so it might take us a while to get to this issue. If you want to look into it, I can share some pointers with you to debug the culprit of the issue, and ship a fix yourself :)

**Comment by mflknr** [comment]
Hey thanks for answering! Yes, would love to get some hints on where to start. How do we go about it?

**Comment by anuragajwani** [comment]
Any pointers here? I am willing to help too if still required

**Comment by pepicrft** [comment]
👋 Here are some pointers:
1. Go through the [get started](https://docs.tuist.io/contributors/get-started.html) for contributors
2. Run Tuist (from the sources) against that project. 
3. Add a breakpoint [here](https://github.com/tuist/tuist/blob/main/Sources/TuistGenerator/Generator/LinkGenerator.swift#L390), which is the logic that obtains the linkable frameworks for a given target.

3 should shed some light on why we might be including a framework that shouldn't included. Feel free to bring it up here for further discussion.

**Comment by angelolloqui** [comment]
Hello! I am running the exact same issue. I used to have this randomly in CI from Firebase and Facebook frameworks, but now with UserCentrics it seems to be reproducable 100% of the times. Has anyone found a solution? or a potential workaround? thanks!

**Comment by angelolloqui** [comment]
Let me try to add some more info:

## Project Configuration:

For this Package.swift:
```
// swift-tools-version: 5.9
import PackageDescription

let package = Package(
    name: "PackageName",
    dependencies: [
        .package(url: "https://bitbucket.org/usercentricscode/usercentrics-spm-sdk.git", exact: "2.13.0"),
        .package(url: "https://bitbucket.org/usercentricscode/usercentrics-spm-ui.git", exact: "2.13.0")
    ]
)
```
and tuist Project:
```
import ProjectDescription

let project = Project(
    name: "TuistUcIssueTuist",
    targets: [
        .target(
            name: "TuistUcIssueTuist",
            destinations: .iOS,
            product: .app,
            bundleId: "io.tuist.TuistUcIssueTuist",
            infoPlist: .extendingDefault(
                with: [
                    "UILaunchStoryboardName": "LaunchScreen.storyboard",
                ]
            ),
            sources: ["TuistUcIssueTuist/Sources/**"],
            resources: ["TuistUcIssueTuist/Resources/**"],
            dependencies: [
                .external(name: "Usercentrics"),
                .external(name: "UsercentricsUI")
            ]
        ),
        .target(
            name: "TuistUcIssueTuistTests",
            destinations: .iOS,
            product: .unitTests,
            bundleId: "io.tuist.TuistUcIssueTuistTests",
            infoPlist: .default,
            sources: ["TuistUcIssueTuist/Tests/**"],
            resources: [],
            dependencies: [.target(name: "TuistUcIssueTuist")]
        ),
    ]
)
```

## Build log

```
Showing Recent Issues
Prepare packages
Prepare build
Multiple commands produce '/Users/angelgarcia/Library/Developer/Xcode/DerivedData/TuistUcIssueTuist-aokykkqvcwlhhifkqglgohdbhdhq/Build/Products/Debug-iphonesimulator/UsercentricsUI.framework'

Multiple commands produce '/Users/angelgarcia/Library/Developer/Xcode/DerivedData/TuistUcIssueTuist-aokykkqvcwlhhifkqglgohdbhdhq/Build/Products/Debug-iphonesimulator/UsercentricsUI.framework/UsercentricsUI'

Build target UsercentricsUI
/Users/angelgarcia/Downloads/tuist-uc-issue-tuist/Tuist/.build/tuist-derived/UsercentricsUI/UsercentricsUI.xcodeproj: DEFINES_MODULE was set, but no umbrella header could be found to generate the module map

duplicate output file '/Users/angelgarcia/Library/Developer/Xcode/DerivedData/TuistUcIssueTuist-aokykkqvcwlhhifkqglgohdbhdhq/Build/Products/Debug-iphonesimulator/UsercentricsUI.framework/_CodeSignature' on task: CodeSign /Users/angelgarcia/Library/Developer/Xcode/DerivedData/TuistUcIssueTuist-aokykkqvcwlhhifkqglgohdbhdhq/Build/Products/Debug-iphonesimulator/UsercentricsUI.framework

duplicate output file '/Users/angelgarcia/Library/Developer/Xcode/DerivedData/TuistUcIssueTuist-aokykkqvcwlhhifkqglgohdbhdhq/Build/Products/Debug-iphonesimulator/UsercentricsUI.framework' on task: MkDir /Users/angelgarcia/Library/Developer/Xcode/DerivedData/TuistUcIssueTuist-aokykkqvcwlhhifkqglgohdbhdhq/Build/Products/Debug-iphonesimulator/UsercentricsUI.framework

duplicate output file '/Users/angelgarcia/Library/Developer/Xcode/DerivedData/TuistUcIssueTuist-aokykkqvcwlhhifkqglgohdbhdhq/Build/Products/Debug-iphonesimulator/UsercentricsUI.framework/Headers' on task: MkDir /Users/angelgarcia/Library/Developer/Xcode/DerivedData/TuistUcIssueTuist-aokykkqvcwlhhifkqglgohdbhdhq/Build/Products/Debug-iphonesimulator/UsercentricsUI.framework/Headers

duplicate output file '/Users/angelgarcia/Library/Developer/Xcode/DerivedData/TuistUcIssueTuist-aokykkqvcwlhhifkqglgohdbhdhq/Build/Products/Debug-iphonesimulator/UsercentricsUI.framework/Info.plist' on task: ProcessInfoPlistFile /Users/angelgarcia/Library/Developer/Xcode/DerivedData/TuistUcIssueTuist-aokykkqvcwlhhifkqglgohdbhdhq/Build/Products/Debug-iphonesimulator/UsercentricsUI.framework/Info.plist /Users/angelgarcia/Downloads/tuist-uc-issue-tuist/Tuist/.build/tuist-derived/UsercentricsUI/InfoPlists/UsercentricsUI-Info.plist

duplicate output file '/Users/angelgarcia/Library/Developer/Xcode/DerivedData/TuistUcIssueTuist-aokykkqvcwlhhifkqglgohdbhdhq/Build/Products/Debug-iphonesimulator/UsercentricsUI.framework/UsercentricsUI' on task: Libtool /Users/angelgarcia/Library/Developer/Xcode/DerivedData/TuistUcIssueTuist-aokykkqvcwlhhifkqglgohdbhdhq/Build/Products/Debug-iphonesimulator/UsercentricsUI.framework/UsercentricsUI normal



Activity Log Complete    20/8/24, 10:24    0.2 seconds
```

## Debug session

For what I understand (my knowledge here is weak), I believe the linkable dependencies are correct:

`LinkGenerator.generateLinkingPhase()`
```
Printing description of linkableDependencies:
▿ 2 elements
  ▿ 0 : GraphDependencyReference
    ▿ xcframework : 6 elements
      ▿ path : <AbsolutePath:"tuist-uc-issue-tuist/Tuist/.build/artifacts/usercentrics-spm-sdk/Usercentrics/Usercentrics.xcframework">
        ▿ _impl : UNIXPath
          - string : "tuist-uc-issue-tuist/Tuist/.build/artifacts/usercentrics-spm-sdk/Usercentrics/Usercentrics.xcframework"
      ▿ infoPlist : XCFrameworkInfoPlist
        ▿ libraries : 4 elements
          ▿ 0 : Library
            - identifier : "ios-arm64_x86_64-simulator"
            ▿ path : Usercentrics.framework
              ▿ _impl : UNIXPath
                - string : "Usercentrics.framework"
            - mergeable : false
            - platform : XcodeGraph.XCFrameworkInfoPlist.Library.Platform.iOS
            ▿ architectures : 2 elements
              - 0 : XcodeGraph.BinaryArchitecture.arm64
              - 1 : XcodeGraph.BinaryArchitecture.x8664
          ▿ 1 : Library
            - identifier : "tvos-arm64"
            ▿ path : Usercentrics.framework
              ▿ _impl : UNIXPath
                - string : "Usercentrics.framework"
            - mergeable : false
            - platform : XcodeGraph.XCFrameworkInfoPlist.Library.Platform.tvOS
            ▿ architectures : 1 element
              - 0 : XcodeGraph.BinaryArchitecture.arm64
          ▿ 2 : Library
            - identifier : "ios-arm64"
            ▿ path : Usercentrics.framework
              ▿ _impl : UNIXPath
                - string : "Usercentrics.framework"
            - mergeable : false
            - platform : XcodeGraph.XCFrameworkInfoPlist.Library.Platform.iOS
            ▿ architectures : 1 element
              - 0 : XcodeGraph.BinaryArchitecture.arm64
          ▿ 3 : Library
            - identifier : "tvos-arm64_x86_64-simulator"
            ▿ path : Usercentrics.framework
              ▿ _impl : UNIXPath
                - string : "Usercentrics.framework"
            - mergeable : false
            - platform : XcodeGraph.XCFrameworkInfoPlist.Library.Platform.tvOS
            ▿ architectures : 2 elements
              - 0 : XcodeGraph.BinaryArchitecture.arm64
              - 1 : XcodeGraph.BinaryArchitecture.x8664
      ▿ primaryBinaryPath : <AbsolutePath:"tuist-uc-issue-tuist/Tuist/.build/artifacts/usercentrics-spm-sdk/Usercentrics/Usercentrics.xcframework/ios-arm64_x86_64-simulator/Usercentrics.framework/Usercentrics">
        ▿ _impl : UNIXPath
          - string : "tuist-uc-issue-tuist/Tuist/.build/artifacts/usercentrics-spm-sdk/Usercentrics/Usercentrics.xcframework/ios-arm64_x86_64-simulator/Usercentrics.framework/Usercentrics"
      ▿ binaryPath : <AbsolutePath:"tuist-uc-issue-tuist/Tuist/.build/artifacts/usercentrics-spm-sdk/Usercentrics/Usercentrics.xcframework/ios-arm64_x86_64-simulator/Usercentrics.framework/Usercentrics">
        ▿ _impl : UNIXPath
          - string : "tuist-uc-issue-tuist/Tuist/.build/artifacts/usercentrics-spm-sdk/Usercentrics/Usercentrics.xcframework/ios-arm64_x86_64-simulator/Usercentrics.framework/Usercentrics"
      - status : XcodeGraph.FrameworkStatus.required
      - condition : nil
  ▿ 1 : GraphDependencyReference
    ▿ xcframework : 6 elements
      ▿ path : <AbsolutePath:"tuist-uc-issue-tuist/Tuist/.build/artifacts/usercentrics-spm-ui/UsercentricsUIFramework/UsercentricsUI.xcframework">
        ▿ _impl : UNIXPath
          - string : "tuist-uc-issue-tuist/Tuist/.build/artifacts/usercentrics-spm-ui/UsercentricsUIFramework/UsercentricsUI.xcframework"
      ▿ infoPlist : XCFrameworkInfoPlist
        ▿ libraries : 4 elements
          ▿ 0 : Library
            - identifier : "tvos-arm64"
            ▿ path : UsercentricsUI.framework
              ▿ _impl : UNIXPath
                - string : "UsercentricsUI.framework"
            - mergeable : false
            - platform : XcodeGraph.XCFrameworkInfoPlist.Library.Platform.tvOS
            ▿ architectures : 1 element
              - 0 : XcodeGraph.BinaryArchitecture.arm64
          ▿ 1 : Library
            - identifier : "ios-arm64"
            ▿ path : UsercentricsUI.framework
              ▿ _impl : UNIXPath
                - string : "UsercentricsUI.framework"
            - mergeable : false
            - platform : XcodeGraph.XCFrameworkInfoPlist.Library.Platform.iOS
            ▿ architectures : 1 element
              - 0 : XcodeGraph.BinaryArchitecture.arm64
          ▿ 2 : Library
            - identifier : "ios-arm64_x86_64-simulator"
            ▿ path : UsercentricsUI.framework
              ▿ _impl : UNIXPath
                - string : "UsercentricsUI.framework"
            - mergeable : false
            - platform : XcodeGraph.XCFrameworkInfoPlist.Library.Platform.iOS
            ▿ architectures : 2 elements
              - 0 : XcodeGraph.BinaryArchitecture.arm64
              - 1 : XcodeGraph.BinaryArchitecture.x8664
          ▿ 3 : Library
            - identifier : "tvos-arm64_x86_64-simulator"
            ▿ path : UsercentricsUI.framework
              ▿ _impl : UNIXPath
                - string : "UsercentricsUI.framework"
            - mergeable : false
            - platform : XcodeGraph.XCFrameworkInfoPlist.Library.Platform.tvOS
            ▿ architectures : 2 elements
              - 0 : XcodeGraph.BinaryArchitecture.arm64
              - 1 : XcodeGraph.BinaryArchitecture.x8664
      ▿ primaryBinaryPath : <AbsolutePath:"tuist-uc-issue-tuist/Tuist/.build/artifacts/usercentrics-spm-ui/UsercentricsUIFramework/UsercentricsUI.xcframework/tvos-arm64/UsercentricsUI.framework/UsercentricsUI">
        ▿ _impl : UNIXPath
          - string : "tuist-uc-issue-tuist/Tuist/.build/artifacts/usercentrics-spm-ui/UsercentricsUIFramework/UsercentricsUI.xcframework/tvos-arm64/UsercentricsUI.framework/UsercentricsUI"
      ▿ binaryPath : <AbsolutePath:"tuist-uc-issue-tuist/Tuist/.build/artifacts/usercentrics-spm-ui/UsercentricsUIFramework/UsercentricsUI.xcframework/tvos-arm64/UsercentricsUI.framework/UsercentricsUI">
        ▿ _impl : UNIXPath
          - string : "tuist-uc-issue-tuist/Tuist/.build/artifacts/usercentrics-spm-ui/UsercentricsUIFramework/UsercentricsUI.xcframework/tvos-arm64/UsercentricsUI.framework/UsercentricsUI"
      - status : XcodeGraph.FrameworkStatus.required
      - condition : nil
 ```

 You can see 2 frameworks linked, which matches the project and dependency description. 
 
However, the dependency itself has this:


usercentrics-spm-sdk
```
// swift-tools-version:5.3
import PackageDescription

let package = Package(
    name: "Usercentrics",
    platforms: [
        .iOS(.v11),
        .tvOS(.v11)
    ],
    products: [
        .library(
            name: "Usercentrics",
            targets: ["Usercentrics"]
        ),
    ],
    targets: [
        .binaryTarget(
            name: "Usercentrics",
            url: "https://bitbucket.org/usercentricscode/usercentrics-spm-sdk/downloads/Usercentrics-2.15.6.xcframework.zip",
            checksum: "499b9be90ef6bcec00c00a9443c30a2bb139ca305130700aec06d9f608fe702c"
        ),
    ]
)
```

usercentrics-spm-ui
```
// swift-tools-version:5.3
import PackageDescription

let package = Package(
    name: "UsercentricsUI",
    platforms: [
        .iOS(.v11),
        .tvOS(.v11)
    ],
    products: [
        .library(
            name: "UsercentricsUI",
            targets: ["UsercentricsUI"]
        )
    ],
    dependencies: [
        .package(name: "Usercentrics", url: "https://bitbucket.org/usercentricscode/usercentrics-spm-sdk", from: "2.15.6")
    ],
    targets: [
        .binaryTarget(
            name: "UsercentricsUIFramework",
            url: "https://bitbucket.org/usercentricscode/usercentrics-spm-ui/downloads/UsercentricsUI-2.15.6.xcframework.zip",
            checksum: "87bfc21aed34a08ec7d668eb044451602b198452f7dcdbf4d70cff3cc569bffa"
        ),
        .target(
            name: "UsercentricsUI",
            dependencies: ["Usercentrics", "UsercentricsUIFramework"]
        ),
    ]
)
```

The second one (usercentrics-UI) is referencing the first (sdk) as a binary dependency, but our project already adds that framework as dependency, so I believe this results in the duplicated task. The interesting thing is that it does not happen if you use SPM directly without Tuist.

**Comment by dvmrmc** [comment]
I can see the mutiple linking of binaries in my project too, just that after removing the duplication, Usercentrics integration crashes on presenting the banner, so I assume there is some limitation or stripping from Tuist in that dependency

**Comment by angelolloqui** [comment]
A little more info. When added with normal SPM (without Tuist), then I can see the dependency shown differently in Xcode. Not sure if this means anything...
![Screenshot 2024-08-20 at 12 11 37](https://github.com/user-attachments/assets/f7964bb5-148f-4f83-a8ab-9fff8c3b0f54)

![Screenshot 2024-08-20 at 12 11 44](https://github.com/user-attachments/assets/05e953c0-b48d-4d24-9e06-d2d911e1aee4)

**Comment by angelolloqui** [comment]
And some more background info. This same issue was already happening randomly in our project with other well known libraries (Firebase and Facebook) that we use from different microfeatures. Normally, with the other "Duplicated tasks" error, it is a matter of retry and then it normally works (if you are not unlucky heheh). But with UserCentrics it is reproducable 100% of the times.

**Comment by angelolloqui** [comment]
@danieleformichelli @pepicrft I am available to work on this. However, it is too complex for me to just fix it without help, so I will need your feedback and hints to continue...

**Comment by pepicrft** [comment]
Here are some findings.

`Usercentrics` and `UsercentricsUI` declare in their `Package.swift` the sources and the binary representation of those sources. This is odd. Usercentric [uses the sources](https://bitbucket.org/usercentricscode/usercentrics-spm-sdk/src/master/Sources/Usercentrics/) to include the privacy manifest. However, that manifest is already in the XCFramework:

<details>
<summary>Usercentrics.xcframework with the privacy manifest in it</summary>
<br>
<img width="380" alt="image" src="https://github.com/user-attachments/assets/a045605e-8152-4310-bdcf-d8cc01beb559">
</details>

**As a consequence**, there are two graphs, the one through the sources, and the one through the binaries (note the duplicated line (`Target 'UsercentricsUI' in project 'UsercentricsUI'`):

<details>
<summary>The compilation graph that shows how there are two sub-graphs for UsercentricsUI</summary>
<img width="1173" alt="image" src="https://github.com/user-attachments/assets/0c1470b4-535d-4c83-989d-73720bf1dc5e">
</details>

And the build process compiles the resources of UsercentricsUI, which is unnecessary because the bundle already lives inside the XCFramework of `UsercentricsUI`:

<details>
<summary>An image that shows unnecessary compilation steps</summary>
<img width="1195" alt="image" src="https://github.com/user-attachments/assets/01734808-1abf-4772-a187-4070190bbec6">
</details>

**Why does it work in SPM?** I think they must be doing some disambiguation logic, either intentionally because they've seen packages following this pattern, or accidentally by not placing the build products in a flat directory, which is what Xcode does for Xcode projects, and the reason why you get the error that multiple commands produce the same output.

### The proper solution

Usercentrics should have two graphs, one to declare the dependencies among the source targets. And another one to declare the dependencies among binaries. Unfortunately, the latter is not supported by SPM, so packages are "hacking" SPM, which finds itself having to handle these scenarios gracefully. 
I'm inclined to wait a bit longer to copy that logic until we see this becomes a norm across packages. I'm optimistic Apple will do something to prevent this madness from spreading

### But until then...

You can create an umbrella local package, `UsercentricsUmbrella` that's an empty static library that transitively links the dynamic XCFrameworks. Tuist will resolve, link, and embed the Usercentrics XCFrameworks without the error described above. You can check out the following example which includes that setup. Follow these steps:

1. `tuist install`
2. `tuist generate`
3. Build with Xcode

[tuist-uc-issue-tuist.zip](https://github.com/user-attachments/files/16714271/tuist-uc-issue-tuist.zip)

**Comment by angelolloqui** [comment]
Thanks @pepicrft , I will try your suggested approach later this week. However, I just want to mention that this duplicated task issue is not only happening with UserCentrics, we have a bigger project with multiple dependencies, and it is quite frequent (around 1/3 of the times) that our build process fails due to "Duplicated task" error of some other dependencies. Some of the affected ones are (happening randomly):

1. [Lottie](https://github.com/airbnb/lottie-spm/blob/main/Package.swift)
2. [Firebase](https://github.com/firebase/firebase-ios-sdk/blob/main/Package.swift)
3. [Facebook](https://github.com/facebook/facebook-ios-sdk/blob/main/Package.swift)

The stack trace is basically the same, but just with some other libs. It is very frustrating because it is constantly failing our pipeline and we are even considering stop using SPM for them

Example issues:

```

Showing Recent Issues
Prepare packages
Prepare build
Unexpected duplicate tasks
Command: ProcessXCFramework /Users/angelgarcia/playtomic/playtomic-ios/tuist/Tuist/.build/artifacts/lottie-spm/Lottie/Lottie.xcframework /Users/angelgarcia/Library/Developer/Xcode/DerivedData/playtomic-csbeoemsprjxakbvenuueuofongd/Build/Products/Debug-iphonesimulator/Lottie.framework ios simulator

Command: ProcessXCFramework /Users/angelgarcia/playtomic/playtomic-ios/tuist/Tuist/.build/artifacts/lottie-spm/Lottie/Lottie.xcframework /Users/angelgarcia/Library/Developer/Xcode/DerivedData/playtomic-csbeoemsprjxakbvenuueuofongd/Build/Products/Debug-iphonesimulator/Lottie.framework ios simulator

```

**Comment by angelolloqui** [comment]
OK, some progress here... the last provided code with the umbrella project did not work: The bundle was added but not properly loaded by the library, resulting in a runtime crash. However, I changed it a bit to not add the bundle and instead point to a special xcframework they have for static linking. With those changes it seems it works. Here is the code:
[tuist-uc-issue-tuist-umbrella.zip](https://github.com/user-attachments/files/16802095/tuist-uc-issue-tuist-umbrella.zip)

However, I am still wondering why we are still getting the same issue with Duplicated tasks but for other much more popular libraries. What is your suggestion for them @pepicrft ? Not sure if the umbrella trick will work for them (I really do not understand the difference on why this umbrella works) but I still have the feeling that there is something to fix here in Tuist

**Comment by angelolloqui** [comment]
Alright, finally this version working (showing the banner) with the umbrella project: [tuist-uc-issue-tuist-umbrella.zip](https://github.com/user-attachments/files/16814084/tuist-uc-issue-tuist-umbrella.zip). 
To recap the changes, it requires adding the resource bundle to the project as an external reference and the umbrella local SPM package that include both frameworks as static. I also had to change the referenced versions of the UC frameworks to the ones with Unity support (not sure why, but it was crashing due to a missing symbol) and the UI version with manual linking.

Just run the classic `tuist install` and `generate` and they should work.

@pepicrft my question about the other popular frameworks still remain, since this duplicated task issue is not only with UserCentrics but also randomly happening with Firebase, Facebook, Lottie,...

**Comment by mblcdr** [comment]
@angelolloqui One thing to note was that when we integrated the bundle like that and send the app for review it got rejected because the Usercentrics bundle includes an executable. So we had to change the bundle by removing the executable and the respective line in the info.plist included in the bundle and then including the resulting bundle in the project.

**Comment by pepicrft** [comment]
I'm a bit hesitant to add logic in Tuist to gracefully handle cases like this as the SPM does. Otherwise, it incentivizes continuing with those setups as opposed to pushing the SPM to add the capabilities that those packages require. For anyone coming across this issue, please, read through the discussion to understand what the issue is, and pick one of the suggested solutions.

**Comment by angelolloqui** [comment]
Thanks @pepicrft . I understand your concerns but the reality is that a lot of popular frameworks are having similar tricks. Firebase, Facebook or Lottie are some examples that when integrated with Tuist (since version 4) fail randomly with duplicated task error. I believe not providing this inside tuist can be a big issue for many projects like mine. I have already invested like 3 days trying to fix the issue for Firebase and I still did not manage to solve it (I tried moving to umbrella but it is very complex due to the amount of subproducts, and I have tried with Carthage but then tuist imports it as static framework instead of dynamic resulting in duplicated symbols). I have been a happy tuist user for almost 2 years but this is making me consider if we should continue using it or not

**Comment by scarlettmueller96** [comment]
Like @mblcdr mentioned we also faced the issue with the executable having to be removed, so we added a script step to out bitrise pipeline which removes the exetcutable file and the relevant input from the Info.plist for the UserCentrics resources bundle. Basically after tuist generate but before we build the IPA file.

```
# Define the path to the Usercentrics bundle
USERCENTRICS_BUNDLE_PATH=$(find "$BITRISE_SOURCE_DIR" -name "UsercentricsUIResources.bundle" 2>/dev/null)

# Check if the Usercentrics bundle exists
if [ -d "$USERCENTRICS_BUNDLE_PATH" ]; then
    echo "Usercentrics bundle found at: $USERCENTRICS_BUNDLE_PATH"

    # Define the executable name to remove
    EXECUTABLE_NAME="UsercentricsUIResources"

    # Remove the executable file if it exists
    if [ -f "$USERCENTRICS_BUNDLE_PATH/$EXECUTABLE_NAME" ]; then
        echo "Removing executable: $EXECUTABLE_NAME"
        rm "$USERCENTRICS_BUNDLE_PATH/$EXECUTABLE_NAME"
    else
        echo "Executable $EXECUTABLE_NAME not found. Skipping removal."
    fi

    # Define the path to Info.plist
    INFO_PLIST_PATH="$USERCENTRICS_BUNDLE_PATH/Info.plist"

    # Check if Info.plist exists
    if [ -f "$INFO_PLIST_PATH" ]; then
        # Remove the executable reference from Info.plist using PlistBuddy
        echo "Removing reference from Info.plist"
        /usr/libexec/PlistBuddy -c "Delete :CFBundleExecutable" "$INFO_PLIST_PATH"
    else
        echo "Info.plist not found at $INFO_PLIST_PATH. Skipping modification."
    fi   
else
    echo "Usercentrics bundle not found. Check the build settings or path."
fi
```
