### ISSUE TITLE
What's the diff whith package in Project.swift and Workspace.swift?

### ISSUE THREAD

**Issue by cdoky** [tuist/tuist#6101]
### What problem or need do you have?

```swift
Project.swift

let project = Project(
    name: "iOSApp",
    organizationName: "com.domain",
    packages: [
        .remote(
            url: "https://github.com/CoderMJLee/MJRefresh.git",
            requirement: .upToNextMajor(from: "3.7.6")
        ),
    ],
    targets: [
....
```
The package(`MJRefresh`) must defined in Project.swift
if put the package in Workspace.swift
the app will could't load package's asset(`MJRefresh.bundle`)

### macOS version

14.2.1

### Tuist version

4.7.0

### Xcode version

15.1

**Comment by pepicrft** [comment]
Hi @cdoky
As far as I know, the packages need to be defined at the project level. Please, correct me if I'm wrong. If you are able to do what you are suggesting via Xcode's UI (without Tuis) and everything works, please, would you mind including the project that you used so that we can have a look at it closely?
I recommend using [XcodeProj-based](https://docs.tuist.io/documentation/tuist/dependencies#Tuists-XcodeProj-based-integration) integration, which can be validated and optimized by Tuist, over the standard integration.
