### ISSUE TITLE
Support folder references with SPM sources

### ISSUE THREAD

**Issue by NachoSoto** [tuist/tuist#6161]
### What problem or need do you have?

I couldn't find a way to do this. Consider a `Project` with a (local) SPM dependency:

**Project.swift:**
```swift
let project = Project(
    name: "TuistTest",
    targets: [
        .target(
            name: "TuistTest",
            destinations: .iOS,
            product: .app,
            bundleId: "io.tuist.TuistTest",
            infoPlist: .extendingDefault(
                with: []
            ),
            sources: ["TuistTest/Sources/**"],
            resources: ["TuistTest/Resources/**"],
            dependencies: [
                .external(name: "LocalPackage"),
           ]
    ]
)
```
**Package.swift:**
```swift
// swift-tools-version: 5.9
import PackageDescription

#if TUIST
    import ProjectDescription

    let packageSettings = PackageSettings(
        productTypes: [
          "LocalPackage": .framework
        ]
    )
#endif

let package = Package(
    name: "TuistTest",
    dependencies: [
        .package(path: "../LocalPackage")
    ]
)
```

After `tuist install && tuist generate`, we get regular folders:
<img width="119" alt="Screenshot 2024-04-09 at 09 19 21" src="https://github.com/tuist/tuist/assets/685609/2626a53b-c6a2-46b4-81f4-8576d81a46af">

This makes it harder to work with, as adding a new file to the package inside of the generate project/workspace forces the user to pick what target it needs to be added to (or to re-run `tuist generate`). 

Compare this with how SPM packages work inside of a project:
<img width="174" alt="Screenshot 2024-04-09 at 09 23 23" src="https://github.com/tuist/tuist/assets/685609/97f6a823-f527-45f5-b7a2-db3de2d318da">

Using folder references makes it much easier to add new files.

### macOS version

14.4.1

### Tuist version

4.9.0

### Xcode version

15.2.0

**Comment by fortmarek** [comment]
Because we turn SPM packages into Xcode projects, I don't think we can do what you're asking for. Being explicit is actually a feature, not a bug. Sure, SPM's way is convenient but it also breaks at scale (we go deeper into the reasons [here](https://docs.tuist.io/guide/introduction/adopting-tuist/migrate-local-swift-packages.html#using-spm-as-a-project-management) and [here](https://docs.tuist.io/guide/introduction/cost-of-convenience.html)).

If you want the convenience over explicitness, you can still use the [vanilla SPM integration](https://docs.tuist.io/guide/project/dependencies.html#xcode-s-default-integration).
