### ISSUE TITLE
Firebase version 7.13.3 fails to build with Tuist projects

### ISSUE THREAD

**Issue by shahzadmajeed** [tuist/tuist#6284]
### What happened?

As mentioned in this firebase thread https://github.com/firebase/firebase-ios-sdk/issues/12949, Tuist users are facing a build issue with their latest version 7.13.3 which doesn't happen in 7.13.2

I will provide a reproducible project but it might just be a matter of updating dependency version to latest in https://github.com/tuist/tuist/tree/main/fixtures/multiplatform_app_with_sdk fixture.

Slack thread is here https://tuist-community.slack.com/archives/C018QG7U7SN/p1715691408936109

### How do we reproduce it?

Update firebase dependency to 7.13.3 and build project you will see https://github.com/firebase/firebase-ios-sdk/issues/12949 issue

### Error log

/xxx/project-name/Tuist/Dependencies/SwiftPackageManager/.build/checkouts/firebase-ios-sdk/FirebaseCore/Internal/Sources/HeartbeatLogging/HeartbeatsPayload.swift:176:16: error: type 'NSData' has no member 'gul_data'
    try NSData.gul_data(byGzippingData: self)
        ~~~~~~ ^~~~~~~~
/xxx/project-name/Tuist/Dependencies/SwiftPackageManager/.build/checkouts/firebase-ios-sdk/FirebaseCore/Internal/Sources/HeartbeatLogging/HeartbeatsPayload.swift:183:16: error: type 'NSData' has no member 'gul_data'
    try NSData.gul_data(byInflatingGzippedData: self)

### macOS version

14

### Tuist version

3.42.3

### Xcode version

15.2

**Comment by fortmarek** [comment]
As confirmed by @ajkolean [here](https://github.com/firebase/firebase-ios-sdk/issues/12949#issuecomment-2108944942), Tuist 4 integration works well. We no longer support Tuist 3 and don't plan to backport any fixes to it. There has been a lot of work done to improve the integration of SPM dependencies in the latest version that's hard to backport.

Most of the work was around modulemaps and header search paths, but it's hard to say what exactly is missing in this instance.

We recommend migrating to Tuist 4 or using the vanilla SPM integration instead of the XcodeProj-based one (using `.package` instead of `.external`)
