### ISSUE TITLE
Binary caching with swift-system v1.3.0 as a dependency fails

### ISSUE THREAD

**Issue by roanutil** [tuist/tuist#6313]
### What happened?

After updating swift-system from v1.2.1 to v1.3.0, binary caching external dependencies fails

### How do we reproduce it?

I've reproduced the problem in this branch of my fork: https://github.com/roanutil/tuist/tree/repro/swift-system-cache-failure

The command_line_tool_basic fixture is the project used to reproduce it.

`tuist install && tuist cache --external-only`

Also, https://github.com/roanutil/tuist/tree/repro/swift-system-cache-failure-working-with-v1.2.1 branch has swift-system reverted to v1.2.1 which successfully binary caches the dependency.

### Error log

```
** BUILD FAILED **
The following build commands failed:
	SwiftEmitModule normal x86_64 Emitting\ module\ for\ SystemPackage (in target 'SystemPackage' from project 'swift-system')
	SwiftCompile normal x86_64 /Users/user/projects/tuist/fixtures/command_line_tool_basic/Tuist/.build/checkouts/swift-system/Sources/System/Internals/Syscalls.swift (in target 'SystemPackage' from project 'swift-system')
	SwiftCompile normal x86_64 Compiling\ CInterop.swift,\ Constants.swift /Users/user/projects/tuist/fixtures/command_line_tool_basic/Tuist/.build/checkouts/swift-system/Sources/System/Internals/CInterop.swift /Users/user/projects/tuist/fixtures/command_line_tool_basic/Tuist/.build/checkouts/swift-system/Sources/System/Internals/Constants.swift (in target 'SystemPackage' from project 'swift-system')
	SwiftCompile normal x86_64 /Users/user/projects/tuist/fixtures/command_line_tool_basic/Tuist/.build/checkouts/swift-system/Sources/System/Internals/CInterop.swift (in target 'SystemPackage' from project 'swift-system')
	SwiftCompile normal x86_64 /Users/user/projects/tuist/fixtures/command_line_tool_basic/Tuist/.build/checkouts/swift-system/Sources/System/Internals/Constants.swift (in target 'SystemPackage' from project 'swift-system')
(5 failures)
```

### macOS version

14.5

### Tuist version

4.14.0

### Xcode version

15.4.0

**Comment by pepicrft** [comment]
I did a bit of investigation, and the issue seems to be related to [this Swift setting](https://github.com/apple/swift-system/blob/b642f54526c3f07ef7ab0cae0ae286986b0733d4/Package.swift#L41), which we are not propagating as expected. 
@roanutil, you should be able to reproduce it outside of the context of cache, too. If you run `tuist generate` on your changes and try to compile the generated project it won't.

If you are interested in looking into this issue yourself, or anyone reading this issue, you can look into the [logic here](https://github.com/tuist/tuist/blob/main/Sources/TuistLoader/SwiftPackageManager/PackageInfoMapper) to figure out why the setting is not being propagated.

**Comment by roanutil** [comment]
Looked into this a little yesterday and it seems likely that the lack of explicit supported platforms at the package level is causing the `SYSTEM_PACKAGE_DARWIN` compilation condition to be dropped because of platform conditions on the setting level. Will dig in more today or over the weekend to verify.

@pepicrft, I assume there's a reason the logic doesn't apply settings that has platform conditions but no package platforms specified? If so, I'll need some guidance on how it should be fixed.

**Comment by roanutil** [comment]
Confirmed the cause is as described above. I have a minimal change that fixes the problem for swift-system v1.3 but has some unintended effects: https://github.com/roanutil/tuist/blob/2935812980faa401d5db04fcc315a716d6398aac/Sources/TuistLoader/SwiftPackageManager/SettingsMapper.swift#L145

**Comment by waltflanagan** [comment]
Nice find.  This logic actually is from the initial multi-platform work when i had assumed that the defined platforms in a package are what it supports, SPM assumes all packages provide support for all platforms, so in the case of a package like this where it defines no platforms it breaks the assumptions of the initial logic.  I'll think some on the proposed changes and impacts.

**Comment by waltflanagan** [comment]
Alright, so, the initial call to `settingsDictionary()` in `settingsForPlatforms()` will pass nil which is intended to create a base dictionary of all settings that dont have any conditions applied to them.  Then, for each platform (which should be all for external SPM packages, and internal ones should have them explicitly set in the Package.swift of the project), we check for settings that have a condition for each platform.  It appears the proprosed changes invert the current logic,  `.hasConditions` checks that conditions is non-nil and not empty and returns the inverse (!hasConditions) but the new logic returns `true` for that case.    My guess is the bug is somewhere in `setting.condition?.platformNames.contains(platformName)` and how `platformName` is being passed in for this package.  It would be nice to know more details about the different settings returned from `settingsDictionary(for:)` as we iterate over the platforms for caching.

**Comment by pepicrft** [comment]
For anyone coming across this, you can workaround the issue until we provide a proper fix by explicitly passing the Swift active compilation condition:

```swift
#if TUIST
import ProjectDescription

let packageSettings = PackageSettings(
    // Customize the product types for specific package product
    // Default is .staticFramework
    // productTypes: ["Alamofire": .framework,]
    productTypes: [:], targetSettings: [
        "SystemPackage": ["SWIFT_ACTIVE_COMPILATION_CONDITIONS": "$(inherited) SYSTEM_PACKAGE_DARWIN"]
    ]
)
#endif
```
