### ISSUE TITLE
Post compile script relative path is incorrect.

### ISSUE THREAD

**Issue by TomerHacohen** [tuist/tuist#6366]
### What problem or need do you have?

When trying to set a post script build phase, I can only set a script path relatively to the Tuist executable.
For example, in my case the script file is shared in an outer directory `BuildTools` and serves multiple projects:
```swift

let project = Project(
  ...,
  targets: [
    .target(
      ...,
      scripts: [
        .post(
          // Expected to work but it doesn't:
          tool: Path.relativeToManifest("../../BuildTools/copy-generated-header-phase.sh").pathString,
          // The following does WORK when script file is located in `~/.local/share/mise/installs/tuist/4.11.0/bin`
//          tool: Path.relativeToManifest("copy-generated-header-phase.sh").pathString,
          name: ...,
          inputPaths: ...,
          outputPaths: ,,,
        )
      ]
    )
  ]
)

```
tuist generate finish with an error:
```
The script tool '../../BuildTools/copy-generated-header-phase.sh' was not found in the environment
Fatal linting issues found
```

I tried to use also `Path.relativeToCurrentFile`, `Path.relativeToRoot` but the actual path remains relative to the tuist executable path.

A project reproducing the issue is attached here:  [tuist-script-issue.zip](https://github.com/user-attachments/files/15534282/tuist-script-issue.zip)
Thanks in advance.

### macOS version

14.1

### Tuist version

4.11.0

### Xcode version

15.4

**Comment by pepicrft** [comment]
Thanks for reporting this @TomerHacohen and including a reproducible project. I added it to our backlog but it might take some time for us to get to it. If you want to go ahead with debugging it yourself, [this is the place](https://github.com/tuist/tuist/blob/main/Sources/TuistLoader/Models%2BManifestMappers/TargetAction%2BManifestMapper.swift#L44) where the path is resolved. I'd put a breakpoint there and see why the `Path.relativeToCurrentFile` and `Path.relativeToRoot` is not resolved as expected. My hunch is that it might be a minor thing.

**Comment by rofle100lvl** [comment]
The issue is not with the Tuist Loader. The actual problem arises from using the incorrect function for the post script. If you perform a "Cmd + click" on the function, it directs you to:

<img width="1099" alt="Screenshot 2024-06-22 at 18 18 49" src="https://github.com/tuist/tuist/assets/45801227/f4e12738-ef73-408d-9b16-598cb87b4c9a">

However, you should be using a different function, as shown below:

<img width="1119" alt="Screenshot 2024-06-22 at 18 20 11" src="https://github.com/tuist/tuist/assets/45801227/d333f712-6572-4d2a-9c9a-e10b0c371086">

Please replace the code with the following snippet, and it should work:

```
.post(
    path: Path.relativeToManifest("../BuildTools/copy-generated-header-phase.sh"),
    name: "Run Script - Copy Generated Swift.h File",
    inputPaths: ["$(DERIVED_SOURCES_DIR)/$(PRODUCT_MODULE_NAME)-Swift.h"],
    outputPaths: ["$(BUILT_PRODUCTS_DIR)/include/$(PRODUCT_MODULE_NAME)/$(PRODUCT_MODULE_NAME)-Swift.h"]
)
```

This approach is documented in the code details, as well as in the Tuist documentation. Given the vast number of functions available in TargetScript, it might be beneficial to consider a future enhancement that unifies these functions for better clarity and usability @pepicrft

**Comment by TomerHacohen** [comment]
Thanks! it definitely works now!
