### ISSUE TITLE
Tuist removes custom shared schemes from workspace

### ISSUE THREAD

**Issue by DmitrySerovWise** [tuist/tuist#6480]
### What problem or need do you have?

Consider a project that does not use Tuist's scheme autogeneration in favour of manually creating shared schemes and committing them to the repo. The setup of the project would look like this:

```
let project = Project(
    name: "MyProject",
    organizationName: "My Company Ltd.",
    options: .options(
        automaticSchemesOptions: .disabled
    )
)
```

After generating the workspace with `tuist generate`, I only get a single scheme, MyProject-Workspace.xcscheme.
Suppose I add a new scheme, MyScheme, with Xcode's GUI, add it to the workspace (suppose I'm also using Workspace.swift) and make it shared to share with teammates.

Then I close the project and run `tuist generate` again.

Expected behaviour:
* I see two schemes in the generated workspace, MyProject-Workspace and MyScheme.

Actual behaviour:
* MyScheme is removed and is nowhere to be seen. It is removed from the file system.

This behaviour makes it impossible to use custom schemes with Tuist, and autogenerated ones still can't do everything I need (I'll create a separate issue to address this)

### Potential solution

Do not remove custom schemes when regenerating the workspace. Only replace those that have the same name, or give an option to the user what to do.

### macOS version

14.5

### Tuist version

3.20.0

### Xcode version

15.4

**Comment by fortmarek** [comment]
> After generating the workspace with tuist generate, I only get a single scheme, MyProject-Workspace.xcscheme.
Suppose I add a new scheme, MyScheme, with Xcode's GUI, add it to the workspace (suppose I'm also using Workspace.swift) and make it shared to share with teammates.

Only _non-shared_ schemes are preserved across generations. Any other schemes are supposed to be created via the `schemes` property either in your [Project.swift](https://docs.tuist.io/generated/manifest/structs/Project.html#schemes) or [Workspace.swift](https://docs.tuist.io/generated/manifest/structs/Workspace.html#schemes).

The behavior you're describing is by design. The Project.swift is supposed to be the source of truth for your projects, not what you do in Xcode GUI.

**Comment by fortmarek** [comment]
See [this fixture](https://github.com/tuist/tuist/tree/main/fixtures/ios_app_with_custom_scheme) for how to configure custom schemes.
