### ISSUE TITLE
Enable support swift version

### ISSUE THREAD

**Issue by marko1503** [tuist/tuist#657]
**Describe the bug**
I have Xcode 11.2, I do start guide, during executing the command `tuist generate` I have an error.

**To Reproduce**

1. Install latest Xcode 11.2
2. Install tuist https://docs.tuist.io/
3. tuist init --platform ios --product application
4. `tuist generate`
5. Error: Command exited with error code 1 and error: /Users/user/test/TuistConfig.swift:1:8: error: module compiled with Swift 5.1 cannot be imported by the Swift 5.1.2 compiler: /Users/user/.tuist/Versions/0.18.1/ProjectDescription.swiftmodule
import ProjectDescription
       ^

**Expected behavior**
the command generates xcode project file

**Desktop (please complete the following information):**

- OS: macOS
- Version: 10.15.1 
- Xcode: 11.2

**Additional context**
As I understand `Build Libraries for Distribution` should be enabled.

**Comment by pepibumur** [comment]
Hi @marko1503, first of all, thanks for reporting this. We are already aware of this and we are working on fixing it as soon as possible. To unblock you, you can follow the steps below:
1. Run `tuist local master`.
2. Then run `tuist generate`.

That'll create a `.tuist-version` file in your project's directory. Tuist will compile the latest version from master and install it in your local environment. Since you are compiling it with the latest version of Swift, it should be compatible with it.

**Comment by marko1503** [comment]
fixed in 0.19

**Comment by rowwingman** [comment]
@pepibumur I've tried 
1. `tuist local master`
2. `tuist generate` # doesn't download latest master.
3. `tuist version` # outputs 0.18.1

What I'm doing wrong?
