### ISSUE TITLE
No Such Module error for  ProjectDescriptionHelpers - Starting Tuist project from scratch

### ISSUE THREAD

**Issue by bugrahaneefe** [tuist/tuist#6581]
### What happened?

- I created new project from scratch. When I enter 'tuist scaffold default --name NetworkKit --path Kit/NetworkKit' it creates module with its own Tuist file. Also, since Tuist did not generate ProjectDescriptionHelpers itself, I created it and I import ProjectDescriptionHelpers in NetworkKit. Now, it causes no such module error while I enter 'tuist generate' command inside NetworkKit. I realized that deleting additional Tuist file inside of NetworkKit solves the problem but it take a while for me to figure it out. FYI. 

### How do we reproduce it?

1. tuist init
2. tuist scaffold --name NetworkKit --path Kit/NetworkKit
3. create ProjectDescriptionHelpers file and modify.
4. import ProjectDescriptionHelpers in NetworkKit
5. tuist generate
6. You will get an error unless you delete additional Tuist file in NetworkKit

### Error log

'''The 'swift' command exited with error code 1 and message:
/Users/xxx/xxx/xxx/xxx/xxx/Kit/NetworkKit/Project.swift:2:8: error: no such module 'ProjectDescriptionHelpers'
import ProjectDescriptionHelpers
       ^

Consider creating an issue using the following link: https://github.com/tuist/tuist/issues/new/choose'''

### macOS version

14.5

### Tuist version

4.x.x

### Xcode version

15.1

**Comment by pm-dev** [comment]
same

**Comment by fortmarek** [comment]
Could either of you provide a reproducible sample? 🙏

**Comment by cemaltuysuz** [comment]
Hi @bugrahaneefe,

I had this problem too. I think the problem is related to the method you installed Tuist tool.

I downloaded it via Brew. When I started using it with Mise, I saw that this problem disappeared.

Try deleting Tuist from your computer:
`brew uninstall tuist`
and
`brew cleanup`

If mise is not installed on your Mac, you can install mise with brew:
`brew install mise`
and
`mise install tuist`

You have installed Tuist. Now specify which version of Tuist you will use. I will not specify a version.
`mise use tuist`

You can check the version to verify:
`mise x -- tuist version`

If everything is ok up to this point, close Xcode completely and reopen the project with mise/tuist.
`mise x -- tuist edit`

![Ekran Resmi 2024-09-29 14 45 47](https://github.com/user-attachments/assets/d8594c62-ea9e-4880-84b8-734c10850cec)

**Comment by pepicrft** [comment]
@cemaltuysuz my hunch is that the issue happens with the Homebrew installation because you were using a formula that's no longer maintained and that we don't have a way to delete from their registry. Do you experience if you install it using our formula? In essence, by running the [suggested](https://docs.tuist.io/guides/quick-start/install-tuist#alternative-homebrew) installation steps:

```
brew tap tuist/tuist
brew install --formula tuist
```

**Comment by fortmarek** [comment]
Hey 👋 

We haven't heard from anybody for some time here, so we consider the issue resolved. If you still run into this, I'd recommend opening a new issue with a reproducible sample.
