### ISSUE TITLE
Broken root groups references

### ISSUE THREAD

**Issue by pepibumur** [tuist/tuist#66]
**Describe the bug**
The root groups in the generated projects don't refer the systems folder properly. If you do right click, and then "Show in Finder" it misleads to another folder.

**To Reproduce**
1. Generate a project using xpm.
2. Right click on one of the root groups.
3. Select "Show in Finder"

**Expected behavior**
Open the right folder on Finder.

**Comment by pepibumur** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Broken root groups references](https://trello.com/c/iAP2ZsmN/23-broken-root-groups-references)

**Comment by santos88** [comment]
@pepibumur It looks like this issue was resolved. Let me know if there is something pending. 

![screen shot 2018-10-04 at 4 26 46 pm](https://user-images.githubusercontent.com/144450/46497967-75f7fe80-c7f2-11e8-9401-62b6f48ca01b.png)

![screen shot 2018-10-04 at 4 27 11 pm](https://user-images.githubusercontent.com/144450/46497974-7beddf80-c7f2-11e8-8624-42bee125a1fb.png)

**Comment by pepibumur** [comment]
I might have solved it already 😜. Nothing to be done here then.
