### ISSUE TITLE
Undefined symbol: _OBJC_CLASS_$_RealmSwiftObject, Realm is not linked.

### ISSUE THREAD

**Issue by c128128** [tuist/tuist#6790]
### What happened?

I can't make it work with RealmSwift. It looks like the issue is related to Realm being `.dynamic`. Please check sample project.

### How do we reproduce it?

[TuistBug.zip](https://github.com/user-attachments/files/17213599/TuistBug.zip)

1. tuist install
2. tuist generate
3. build from Xcode

alternative:
1. tuist install
2. tuist build

### Error log

```
Undefined symbols for architecture arm64:
  "_OBJC_CLASS_$_RealmSwiftObject", referenced from:
      full type metadata for Test.Wtf in TestApp.o
  "_OBJC_METACLASS_$_RealmSwiftObject", referenced from:
      _OBJC_METACLASS_$__TtC4Test3Wtf in TestApp.o
ld: symbol(s) not found for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

### macOS version

14.6.1

### Tuist version

4.28.1

### Xcode version

16.0.0

**Comment by fortmarek** [comment]
Hey 👋 

I'm closing this as a duplicate of: https://github.com/tuist/tuist/issues/6790

I created a dedicated fixture for Realm to clear any confusion: https://github.com/tuist/tuist/pull/6793

What your sample is missing is the extra dependency on `Realm` (not just `RealmSwift`). That should _not_ be necessary and is probably due to some differences between SPM and our approach. I'll keep the original issue opened to investigate that further.

**Comment by c128128** [comment]
Thank you, @fortmarek. I can confirm that everything is working now.
