### ISSUE TITLE
Missing TEST_HOST Setting in Essential Configuration

### ISSUE THREAD

**Issue by danielmoro** [tuist/tuist#6926]
### Issue Summary
The TEST_HOST setting is not being configured when using .essential defaultSettings for test targets, contrary to previous behavior.
### Current Behavior
When using .essential defaultSettings, the TEST_HOST setting is not set for test targets.
### Expected Behavior
The TEST_HOST setting should be automatically configured when using .essential defaultSettings for test targets, as it was in previous versions.
### Regression
This appears to be a regression from previous versions where the TEST_HOST was properly set under .essential configuration.

### How do we reproduce it?

1. Make a directory
2. inside run `tuist init`
3. run `tuist edit`
4. change test target by adding: `settings: .settings(base: [:], defaultSettings: .essential)`
5. close editor
6. run `tuist generate`
7. Go to Build Settings and search for “TEST_HOST”
8. TEST_HOST is empty

### Error log

-

### macOS version

15.0

### Tuist version

4.31.1

### Xcode version

16.0

**Comment by fortmarek** [comment]
Thanks for flagging this issue @danielmoro! @gustn3965, would you have some time to take a look as a follow-up to the initial PR you did? That'd be much appreciated 🙏

**Comment by gustn3965** [comment]
@danielmoro  Apologies! This side effect occurred while fixing an issue where the `TEST_HOST` value was being overridden when using xcconfig.

To maintain the original behavior, I will add it to the [essentialTargetSettings](https://github.com/tuist/tuist/blob/f9e4537730932e0dd47581a782cffc620c72caad/Sources/TuistGenerator/Settings/DefaultSettingsProvider.swift#L49) in `DefaultSettingsProvider` so that `TEST_HOST` can be generated for essential cases even without exclusions.

@fortmarek I will add the necessary code and test cases and submit a PR.

Thank you for reporting this.
