### ISSUE TITLE
Unable to set the repository URL for my app

### ISSUE THREAD

**Issue by hiltonc** [tuist/tuist#7054]
### What happened?

I'm unable to set the repository URL for my app.

### How do we reproduce it?

```
tuist project update REDACTED --repository-url https://github.com/ORG/REPO/
```

I tried `tuist logout && tuist auth` to reauth, but still it doesn't work.

### Error log

```
Failed to update the repository due to: Unexpected status code when getting the access token url: 401. Body: {"documentation_url":"https://docs.github.com/rest","message":"Bad credentials","status":"401"}
```

### macOS version

15.1

### Tuist version

4.34.0

### Xcode version

16.0

**Comment by fortmarek** [comment]
Hey @hiltonc!

Thanks for reporting this issue.

> I tried tuist logout && tuist auth to reauth, but still it doesn't work.

That's expected, the error message is coming from the server and it happens when authenticating the GitHub app. It's not tied to your local authentication.

However, I am not able to reproduce the issue. I ran the following command for one of the test projects that we have on the production server:
```sh
tuist project update tuist/ios_app_with_frameworks --repository-url https://github.com/tuist/tuist
```

And the repository URL got successfully updated. Could you try rerunning the command? If that doesn't help, would you mind reaching out on Slack and providing some extra details, so we can debug the issue? Thank you!

**Comment by fortmarek** [comment]
We found the issue was happening because of the trailing slash. We're updating the server to handle this scenario.
