### ISSUE TITLE
Adding a Test Host breaks builds due to cycle in dependencies

### ISSUE THREAD

**Issue by rgnns** [tuist/tuist#7063]
### What happened?

There's an example about how to reproduce this issue. If there's a framework target and a test target which uses a test host, Tuist will create a "executable dependency" build phase that causes builds to fail due to cycle in dependencies. This was working before 4.32.1.

The example:
https://gitlab.com/gabriellievano/tuist_test_host_example

### How do we reproduce it?

1. Clone the repo https://gitlab.com/gabriellievano/tuist_test_host_example.
2. `mise install`
3. `tuist install`
4. `tuist generate`
5. Try to build

### Error log

`Cycle in dependencies between targets 'TestHost' and 'ATests'; building could produce unreliable results`

### macOS version

14.7

### Tuist version

4.34.0

### Xcode version

15.3

**Comment by fortmarek** [comment]
Thanks for reporting!

@TamarMilchtaich, do you think you could take a look? I believe this regression got introduced in https://github.com/tuist/tuist/pull/6820

**Comment by TamarMilchtaich** [comment]
Hi, 
Note that:
1. Cleaning Xcode between running the test host and the workspace fixes the issue (which makes sense, since there isn't really a cycle in the dependencies). I see complains about it over the internet, e.g. https://stackoverflow.com/questions/50709330/cycle-inside-building-could-produce-unreliable-results-xcode-error, but none of the solutions there worked for me in this project yet
2. While it used to compile before https://github.com/tuist/tuist/pull/6820, it should produce a runtime error when running the test target, since before this PR declaring a dependency in the manifest of a test host from a different project would be ignored

I'll keep looking into it

**Comment by TamarMilchtaich** [comment]
First - thank you for pointing it out!

After looking more into it, seems like the "Exectuable Dependencies" phase is redundant, since the executable are already part of the "Dependencies" phase (it was added there are part of the test host PR), so I opened a PR to remove it:
https://github.com/tuist/tuist/pull/7136
(maybe as part of the test host PR process some code was added that made it no longer needed)

Seems like everything (the example project here, the fixture) is working fine after this change, but feel free to also makes sure yourselves.

I still think it's a bug on Apple's side that this will lead to cyclic dependency, especially that the as part of the build there's a calculation of the dependency graph, and the output indicates no dependencies for test host. So also opened a bug report to them via Feedback, will let you know if anything interesting comes up there.
