### ISSUE TITLE
Add support for detecting unused code

### ISSUE THREAD

**Issue by pepicrft** [tuist/tuist#780]
## Context 🕵️‍♀️
I just came across [this tool](https://github.com/woshiccm/Pecker) that can be run from a build phase and warns the user about unused code.

## What 🌱
I think this is a feature that we could add to Tuist and help the developers keep their projects free of unused code. The tool parses the information dumped by SourceKit and generates diagnosing messages using SwiftSyntax's utilities.

**Comment by lakpa** [comment]
I am wondering, how feasible would it be to allow user to run any tools with proper abstraction around such as `build rule` in `xcodegen` instead of users being forced to use this tool or none, do we have any such configuration in existence?

**Comment by kwridan** [comment]
> I am wondering, how feasible would it be to allow user to run any tools with proper abstraction around such as build rule in xcodegen instead of users being forced to use this tool or none, do we have any such configuration in existence?

+1

Agree with @lakpa , it’s cool to have Tuist enable such integrations but not necessarily bundle in the integration itself. As I’m sure there are other examples and tools where integrations would be desired.

**Comment by kwridan** [comment]
Reading through the readme - Tuist is able to support this already via TargetActions. 

With the introduction of project description helpers having this applied to all targets is now really easy too 👍

**Comment by pepibumur** [comment]
> I am wondering, how feasible would it be to allow user to run any tools with proper abstraction around such as build rule in xcodegen instead of users being forced to use this tool or none, do we have any such configuration in existence?

It wouldn't be forcing users, just providing a default on what we believe are best practices for the project. Some projects might want to use their own tool, and that's fine, but if we provide them with a built-in feature, that's one less thing most projects will have to think about.

For instance, if you think about programming languages like Go, projects don't have to think about code formatting because the language provides it out of the box. I see something like that on Tuist too, you can do `tuist format`, and we'll format your code automatically. We'll do it too during the build process in Xcode. Maybe you don't want to use the feature? That's fine, you can just disable it and define your custom target actions.

Another example that comes to my mind is Rails. They provide `ActiveRecord`, an ORM for interacting with a database. Are you obliged to use it? No, since you can bring your own implementation on how to deal with the models.

A huge upside of this is that running the tool is well integrated into the CLI interface and the build phases. The command that users use from the CLI and the command run as a build phase will yield the same results because Tuist makes sure those are identicals.

**Comment by danyf90** [comment]
Given the direction we are taking with plugins (moving lint to separate plugin), I agree this should not be part of tuist, but should rather be integrated by developer as target action or via plugins
