### ISSUE TITLE
Codecov integration

### ISSUE THREAD

**Issue by lakpa** [tuist/tuist#851]
## Need/problem

We have good test coverage but there is no tool for us to gauge it. [Codecov](https://codecov.io) is free for open source project and has support for `Swift` programming language.

## Motivation

Codecov provides highly integrated tools to compare coverage reports and encourage us to do add more test coverage.

# Adoption strategy

This is not a breaking change and should not affect our current workflow

**Comment by lakpa** [comment]
it appears as if we already have codecov integration. Hence closing this issue

**Comment by pepibumur** [comment]
I'm adding a bit of context. [Codecov](https://github.com/tuist/tuist/blob/2a58161538ede2c97798d42d128f1a1d2f094769/.github/workflows/tuist.yml#L18) seems to be configured, but the integration is broken because it doesn't output the results to the PR.

Let me know if you need any especial permissions to set this up @lakpa. And thanks for opening the issue 🙏

**Comment by lakpa** [comment]
Fixes https://github.com/tuist/tuist/pull/855
