### ISSUE TITLE
API stability guidelines

### ISSUE THREAD

**Issue by vytis** [tuist/tuist#889]
## Need/problem

There are quite a lot of types that are available as part of `ProjectDescription` module. It could be considered as Tuist's public API and we should have some guidelines how to introduce changes to it.

## Motivation

As part of thinking about #705 there was a [discussion](https://github.com/tuist/tuist/issues/705#issuecomment-567153714) about unifying the way we include files and resources to the generated project. We currently have several different types that handle this and tweaking them would potentially introduce a breaking change for people using Tuist. Of course not touching anything in ProjectDescription module is not a viable option, so I think we should have some sort of information on how to approach the problem.

# Unresolved questions

- [ ] Is this something that feels relevant for everyone else working on Tuist?
- [ ] Should we avoid doing breaking changes at all costs or introduce them if we feel it improves the experience considerably?
- [ ] Making additive changes should be fine, but what exactly is considered an additive change?
- [ ] Would there be a way to automate checking for breaking changes or we just try to flag it in code review?

**Comment by kwridan** [comment]
Thanks for raising @vytis 

Indeed, `ProjectDescription` is one Tuist's public APIs, any breaking changes there would cases users of Tuist to update their manifest files.

Pre- 1.0 the approach was marking certain properties or methods as "deprecated" along side the introduction of the new API if it could be made compatible, and then later removing the deprecated API in a later release. 

Post 1.0 I believe the idea would be the same, except the removal would take place in the next major release. An aspect that could be improved is somehow printing warnings for deprecated methods if we can detect them reliably.

Once there's a good amount of those breaking changes we could make a major release and remove all the deprecated methods.

To help us manage this, perhaps we could maintain a document similar to the change log, but listing breaking changes and the migration strategy:

As an example: (dummy details)
````
# Next

## Paths
All paths now include an `exclude:` property to allow excluding a subset of the specified paths ...

### Impact
The following definitions no longer accept `FileElements`
- `Headers`
- `Project` 

### Migration
Any occurrence of `FileElement` can be replaced with ....

# 1.0

````

This information can then become part of the documentation or possibly part of a blog post for that release.

Some examples from other projects: 

- [Migrating to Swift 5](https://swift.org/migration-guide-swift5/) & [Migrating to Swift 4](https://swift.org/migration-guide-swift4/)
- [Vapor - Upgrading](https://docs.vapor.codes/3.0/version/upgrading/)
- [Laravel Upgrade Guide](https://laravel.com/docs/5.8/upgrade)
- [Upgrading ruby on rails](https://edgeguides.rubyonrails.org/upgrading_ruby_on_rails.html#upgrading-from-rails-6-0-to-rails-6-1)

> Would there be a way to automate checking for breaking changes or we just try to flag it in code review?

Usually the fixtures are good at catching breaking changes (assuming the exercise all the public API) - which can be identified during code review. On a related note, I believe @ollieatkinson proposed the use of Guise in #221 which could possibly add some automation here too.

cc: @tuist/core

**Comment by pepibumur** [comment]
>  Is this something that feels relevant for everyone else working on Tuist?

It does. It's one of those things that the people that work on this more actively have in their mind, but we should document somewhere. As @kwridan pointed out, the good thing is that we have a pretty expense list of acceptance tests that should catch breaking changes. I'd add a section to the documentation describing what's the public interface:
- Public models in the `ProjectDescription` models.
- The CLI commands (names, arguments, ...)
- The behaviour of the CLI commands.

I was thinking about the format of the generated Xcode project but I'd not include that. What do you think?

>  Should we avoid doing breaking changes at all costs or introduce them if we feel it improves the experience considerably?

We should avoid them at all the costs. Breaking changes are painful and they break the users' trust on the tool. If we feel there's a new API that would be better, we can think about a path to get there so that it's not painful for the users. If we feel it's worth a breaking change, we can open an issue to tackle it before the next major release.

>  Making additive changes should be fine, but what exactly is considered an additive change?

Worth including in the documentation too. Adding new attributes to the models, arguments to existing commands...

>  Would there be a way to automate checking for breaking changes or we just try to flag it in code review?

Acceptance tests are right for that. We cover many end-to-end flows and project scenarios. We are probably missing some, but I think is enough to feel confident because we also have code reviews down the pipeline.

**Comment by pepibumur** [comment]
@vytis would you like to add a new page to the documentation?

**Comment by vytis** [comment]
@pepibumur I will look through the other examples @kwridan linked and try to compile something.

**Comment by vytis** [comment]
It seems a new tool just got released recently that can easily print all public API - https://github.com/SwiftDocOrg/swift-doc#swift-api-inventory
